@BookDemo
Feature: Book a Demo frontend to SaaS Admin end to end workflow

  @BookDemoE2E
  Scenario Outline: Submit Book a Demo request for <Form_Selected_Product> and complete the SaaS Admin workflow

    Given Book a Demo form data is provided from the feature file
      | Selected Product | <Form_Selected_Product> |
      | First Name       | <Form_First_Name>       |
      | Last Name        | <Form_Last_Name>        |
      | Email            | <Form_Email>            |
      | Company Name     | <Form_Company_Name>     |
      | Country Code     | <Form_Country_Code>     |
      | Phone Number     | <Form_Phone_Number>     |
      | Message          | <Form_Message>          |

    And Book a Demo lead plan data is provided from the feature file
      | Checkout App Type  | checkout                           |
      | Checkout Plan Name | Ayan Checkout New Yearly Plan      |
      | Spaces App Type    | spaces                             |
      | Spaces Plan Name   | Ayan New Professional Diamond Plan |
      | Hr App Type        | hr                                 |
      | Hr Plan Name       | Ayan HR New Weekly Plan            |
      | Hire App Type      | hire                               |
      | Hire Plan Name     | Ayan Monthly Hire Business Plan    |

    And Book a Demo upgrade billing data is provided from the feature file
      | First Name | Adrian                             |
      | Last Name  | Keller                             |
      | Address    | 18 Lindenstrasse, Business Tower 4 |
      | Country    | Germany                            |
      | City       | Berlin                             |
      | State      | Berlin                             |
      | Zip        | 10115                              |

    And Book a Demo account data is provided from the feature file
      | First Name         | Lorenz                                                                                                                                                                                         |
      | Middle Name        | Matthias                                                                                                                                                                                       |
      | Last Name          | Baumgartner                                                                                                                                                                                    |
      | Company Name       | Baumgartner Unified Systems GmbH                                                                                                                                                                |
      | Country            | Germany                                                                                                                                                                                        |
      | Email              | lorenz.matthias.baumgartner.account166@yopmail.com                                                                                                                                             |
      | Subscribe News     | Yes                                                                                                                                                                                            |
      | Country Code       | +49                                                                                                                                                                                            |
      | Phone Number       | 15728493610                                                                                                                                                                                    |
      | App Type           | all                                                                                                                                                                                            |
      | App Name           | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire                                                                                                                         |
      | App Enabled        | Yes                                                                                                                                                                                            |
      | Checkout Plan Name | Ayan Monthly Checkout Business Plan                                                                                                                                                             |
      | Spaces Plan Name   | Ayan Monthly Spaces Business Plan                                                                                                                                                               |
      | Hire Plan Name     | Ayan Monthly Hire Business Plan                                                                                                                                                                 |
      | Hr Plan Name       | Ayan Monthly HR Business Plan                                                                                                                                                                   |
      | Users              | 47                                                                                                                                                                                             |
      | Group              | Gold II                                                                                                                                                                                        |
      | Account Manager    | Ayan Test Manager                                                                                                                                                                               |
      | Staff Notes        | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |

    When the Book a Demo end to end flow is executed

    Examples:
      | Form_Selected_Product                                                   | Form_First_Name   | Form_Last_Name | Form_Email                                                   | Form_Company_Name                       | Form_Country_Code | Form_Phone_Number | Form_Message                                                                                                                                                                                                                 |
      | Simplified Checkout                                                     | Ansgar Volker     | Kraneburg      | ansgar.volker.kraneburg.checkout326@yopmail.com              | Kraneburg Digital Commerce GmbH         | +49               | 15726483910       | We are evaluating Simplified Checkout to streamline payment processing, reduce cart abandonment, improve transaction visibility, simplify customer purchases, and strengthen digital commerce reporting.                    |
      | Simplified Hire                                                         | Sidonie Blanche   | Montferrand    | sidonie.blanche.montferrand.hire327@yopmail.com              | Montferrand Talent Advisory SAS         | +33               | 752638491         | Our recruitment team wants to review Simplified Hire for vacancy management, candidate tracking, recruiter collaboration, interview feedback, hiring-stage movement, and recruitment analytics.                              |
      | Simplified HR                                                           | Otso Viljami      | Kettunen       | otso.viljami.kettunen.hr328@yopmail.com                      | Kettunen People Services Oy             | +358              | 458936271         | We are exploring Simplified HR for employee record management, attendance monitoring, leave approvals, department administration, role permissions, internal communication, and workforce reporting.                         |
      | Simplified Spaces                                                       | Rinaldo Ettore    | Gherardi       | rinaldo.ettore.gherardi.spaces329@yopmail.com                | Gherardi Workspace Management SRL       | +39               | 3539461827        | We manage multiple flexible offices and want to evaluate Simplified Spaces for desk reservations, meeting-room scheduling, customer inquiries, branch availability, and workspace utilization reporting.                     |
      | Simplified Checkout, Simplified Hire                                    | Neville Ambrose   | Pembroke       | neville.ambrose.pembroke.checkout.hire330@yopmail.com        | Pembroke Commerce and Talent Ltd        | +44               | 7583164920        | Our UK-based company wants to combine online payment management with recruitment workflows, including transaction monitoring, candidate pipelines, recruiter collaboration, and operational reporting.                     |
      | Simplified HR, Simplified Spaces                                        | Annelot Marijke   | Van Heusden    | annelot.marijke.vanheusden.hrspaces331@yopmail.com           | Van Heusden People and Offices BV       | +31               | 684297531         | We need an integrated solution for employee administration, attendance, leave requests, desk reservations, meeting rooms, office availability, and internal operational reporting.                                           |
      | Simplified Checkout, Simplified HR                                      | Korbinian Severus | Aichinger      | korbinian.severus.aichinger.checkouthr332@yopmail.com        | Aichinger Business Operations GmbH      | +43               | 6778421935        | We want to review Simplified Checkout and Simplified HR for transaction processing, payment visibility, employee administration, attendance management, leave approvals, and consolidated reporting.                         |
      | Simplified Hire, Simplified HR                                          | Miloslawa Halina  | Jankowska      | miloslawa.halina.jankowska.hirehr333@yopmail.com             | Jankowska Workforce Platforms Sp z oo   | +48               | 518372946         | Our organization needs connected recruitment and HR workflows covering applications, interviews, hiring decisions, onboarding, employee records, attendance, and leave administration.                                      |
      | Simplified Checkout, Simplified Hire, Simplified HR                     | Rogier Quinten    | Van Renssen    | rogier.quinten.vanrenssen.enterprise334@yopmail.com          | Van Renssen Enterprise Services BV      | +31               | 639825174         | Our enterprise team is comparing platforms for checkout operations, recruitment management, and HR administration, including access control, workflow configuration, reporting, and implementation support.                 |
      | Simplified Checkout, Simplified Hire, Simplified HR, Simplified Spaces  | Heidemarie Berta  | Kirchberg      | heidemarie.berta.kirchberg.fullsuite335@yopmail.com          | Kirchberg Integrated Solutions GmbH     | +49               | 16359284710       | We are evaluating the complete Simplified suite for checkout processing, recruitment workflows, HR administration, workspace booking, branch coordination, and cross-department reporting.                                   |
      | Simplified Checkout                                                     | Eusebio Ramon     | Valcarcel      | eusebio.ramon.valcarcel.checkout336@yopmail.com              | Valcarcel Digital Transactions SL       | +34               | 612847395         | Our digital commerce team wants to improve checkout reliability, increase successful payment completion, reduce purchase friction, monitor transactions, and analyze online sales performance.                              |
      | Simplified Hire                                                         | Clarissa Donata   | Bellocchi      | clarissa.donata.bellocchi.hire337@yopmail.com                | Bellocchi Recruitment Partners SRL      | +39               | 3487162950        | We are managing several hiring campaigns and want Simplified Hire for candidate profiles, job pipelines, interview coordination, recruiter assignments, hiring-stage updates, and recruitment reports.                       |
      | Simplified HR                                                           | Isak Melker       | Norstrom       | isak.melker.norstrom.hr338@yopmail.com                       | Norstrom People Management AB           | +46               | 702583946         | We are searching for an HR platform to manage employee profiles, organizational structures, attendance records, leave workflows, user permissions, internal communication, and workforce analytics.                         |
      | Simplified Spaces                                                       | Pieterjan Stijn   | De Smet        | pieterjan.stijn.desmet.spaces339@yopmail.com                 | De Smet Flexible Offices BV             | +32               | 472638915         | We operate shared-office locations and want Simplified Spaces for desk booking, room scheduling, customer requests, resource availability, location coordination, and workspace performance analysis.                        |
      | Simplified Checkout, Simplified Hire                                    | Maud Perrine      | Rochat         | maud.perrine.rochat.checkout.hire340@yopmail.com             | Rochat Commerce Talent AG               | +41               | 765294831         | Our business wants to connect checkout operations with recruitment management for improved payment visibility, applicant tracking, recruiter collaboration, hiring decisions, and centralized reporting.                   |
      | Simplified HR, Simplified Spaces                                        | Veit Alois        | Hohenacker     | veit.alois.hohenacker.hrspaces341@yopmail.com                | Hohenacker Corporate Services GmbH      | +49               | 15468392710       | We need HR and workspace modules to manage employee information, attendance, leave requests, desk reservations, meeting-room availability, office utilization, and internal reports.                                         |
      | Simplified Checkout, Simplified HR                                      | Ronja Tilde       | Svanberg       | ronja.tilde.svanberg.checkouthr342@yopmail.com               | Svanberg Business Systems AB            | +46               | 736829145         | We are evaluating Checkout and HR modules for online payment operations, transaction monitoring, employee profile management, attendance visibility, leave approvals, and consolidated reporting.                           |
      | Simplified Hire, Simplified HR                                          | Orsola Fiammetta  | Albrizzi       | orsola.fiammetta.albrizzi.hirehr343@yopmail.com              | Albrizzi Workforce Solutions SRL        | +39               | 3459362810        | Our workforce team wants an integrated recruitment and HR system supporting candidate tracking, interview feedback, onboarding, employee records, attendance, leave approvals, and HR reporting.                            |
      | Simplified Spaces                                                       | Asbjorn Leif      | Hvidberg       | asbjorn.leif.hvidberg.spaces344@yopmail.com                  | Hvidberg Workspace Services ApS         | +45               | 42831597          | We manage shared workspaces and want to review Simplified Spaces for desk allocation, meeting-room scheduling, customer requests, branch availability, multi-location coordination, and utilization reports.                 |
      | Simplified Checkout, Simplified Hire, Simplified HR, Simplified Spaces  | Seraina Fabienne  | Meierhans      | seraina.fabienne.meierhans.allmodules345@yopmail.com         | Meierhans Strategic Operations AG       | +41               | 798426315         | We are comparing complete business platforms and would like a demonstration of all Simplified modules covering checkout, recruitment, HR administration, workspace operations, pricing, configuration, and implementation. |