@BookDemo
Feature: Book a Demo frontend to SaaS Admin end to end workflow

  @BookDemoE2E
  Scenario Outline: Submit Book a Demo request for <Form_Selected_Product> and complete the SaaS Admin workflow

    Given Book a Demo form data is provided from the feature file
      | Selected Product | <Form_Selected_Product> |
      | First Name       | <Form_First_Name>       |
      | Last Name        | <Form_Last_Name>        |
      | Email            | <Form_Email>            |
      | Company Name     | <Form_Company_Name>     |
      | Country Code     | <Form_Country_Code>     |
      | Phone Number     | <Form_Phone_Number>     |
      | Message          | <Form_Message>          |

    And Book a Demo lead plan data is provided from the feature file
      | Checkout App Type  | checkout                           |
      | Checkout Plan Name | Ayan Checkout New Yearly Plan      |
      | Spaces App Type    | spaces                             |
      | Spaces Plan Name   | Ayan New Professional Diamond Plan |
      | Hr App Type        | hr                                 |
      | Hr Plan Name       | Ayan HR New Weekly Plan            |
      | Hire App Type      | hire                               |
      | Hire Plan Name     | Ayan Monthly Hire Business Plan    |

    And Book a Demo upgrade billing data is provided from the feature file
      | First Name | Adrian                             |
      | Last Name  | Keller                             |
      | Address    | 18 Lindenstrasse, Business Tower 4 |
      | Country    | Germany                            |
      | City       | Berlin                             |
      | State      | Berlin                             |
      | Zip        | 10115                              |

    And Book a Demo account data is provided from the feature file
      | First Name         | Lorenz                                                                                                                                                                                         |
      | Middle Name        | Matthias                                                                                                                                                                                       |
      | Last Name          | Baumgartner                                                                                                                                                                                    |
      | Company Name       | Baumgartner Unified Systems GmbH                                                                                                                                                                |
      | Country            | Germany                                                                                                                                                                                        |
      | Email              | lorenz.matthias.baumgartner.account166@yopmail.com                                                                                                                                             |
      | Subscribe News     | Yes                                                                                                                                                                                            |
      | Country Code       | +49                                                                                                                                                                                            |
      | Phone Number       | 15728493610                                                                                                                                                                                    |
      | App Type           | all                                                                                                                                                                                            |
      | App Name           | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire                                                                                                                         |
      | App Enabled        | Yes                                                                                                                                                                                            |
      | Checkout Plan Name | Ayan Monthly Checkout Business Plan                                                                                                                                                             |
      | Spaces Plan Name   | Ayan Monthly Spaces Business Plan                                                                                                                                                               |
      | Hire Plan Name     | Ayan Monthly Hire Business Plan                                                                                                                                                                 |
      | Hr Plan Name       | Ayan Monthly HR Business Plan                                                                                                                                                                   |
      | Users              | 47                                                                                                                                                                                             |
      | Group              | Gold II                                                                                                                                                                                        |
      | Account Manager    | Ayan Test Manager                                                                                                                                                                               |
      | Staff Notes        | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |

    When the Book a Demo end to end flow is executed

    Examples:
  | Form_Selected_Product                                                   | Form_First_Name | Form_Last_Name | Form_Email                                                 | Form_Company_Name                    | Form_Country_Code | Form_Phone_Number | Form_Message                                                                                                                                                                                | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name                  | Account_Country | Account_Email                                              | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name                                                      | Account_App_Enabled | Account_Checkout_Plan_Name              | Account_Spaces_Plan_Name              | Account_Hire_Plan_Name                   | Account_Hr_Plan_Name             | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes                                                                                                                                                                           |
  | Simplified Checkout                                                     | Anselm Dieter   | Wolfsberg      | anselm.dieter.wolfsberg.checkout366@yopmail.com            | Wolfsberg Digital Payments GmbH      | +49               | 15197284630       | We are reviewing Simplified Checkout to improve payment completion, transaction visibility, refund tracking, purchase flow reliability, and commerce reporting.                            | Berthold           | Kasimir             | Eichenwald        | Eichenwald Unified Systems GmbH      | Germany         | berthold.kasimir.eichenwald.bookdemo.account386@yopmail.com | Yes                    | +49                  | 16048372915          | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Weekly Spaces Growth Plan        | Ayan Monthly Hire Business Plan          | Ayan Weekly HR Growth Plan       | 58            | Gold II       | Ayan Test Manager       | Creating this Germany-based all-app account with completely fresh identity, email, phone, plan, user, group, newsletter, and manager data.                                                     |
  | Simplified Hire                                                         | Severine Lucile | Marceau        | severine.lucile.marceau.hire367@yopmail.com                | Marceau Talent Strategy SAS          | +33               | 786294153         | Our hiring team wants to evaluate Simplified Hire for vacancy publishing, candidate pipelines, recruiter collaboration, interviews, hiring decisions, and analytics.                       | Sabine             | Margaux             | Delorme           | Delorme Enterprise Platforms SAS    | France          | sabine.margaux.delorme.bookdemo.account387@yopmail.com      | No                     | +33                  | 739615284            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Monthly Spaces Business Plan     | Ayan Custom Months Hire Premium Plan     | Ayan Daily HR Starter Plan       | 33            | Diamond       | Ayan Test Manager       | Validating a France-based all-app account using new contact information, unique plan combinations, users, subscription preference, and group mapping.                                         |
  | Simplified HR                                                           | Yrjo Tapani     | Mikkola        | yrjo.tapani.mikkola.hr368@yopmail.com                      | Mikkola People Operations Oy         | +358              | 468271935         | We are exploring Simplified HR for employee records, attendance, leave workflows, department structures, permissions, communication, and workforce insights.                               | Kauko              | Juhani              | Paavola           | Paavola Integrated Cloud Oy         | Finland         | kauko.juhani.paavola.bookdemo.account388@yopmail.com        | Yes                    | +358                 | 507294681            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Yearly Checkout Enterprise Plan   | Ayan Daily Spaces Starter Plan        | Ayan Custom Weeks Hire Flex Plan         | Ayan Yearly HR Enterprise Plan   | 61            | Silver        | Ayan Test Manager       | Testing this Finland-based all-app account with newly generated account identity, email, phone number, plans, user count, and staff notes.                                                     |
  | Simplified Spaces                                                       | Donato Cesare   | Belluzzi       | donato.cesare.belluzzi.spaces369@yopmail.com               | Belluzzi Workspace Services SRL      | +39               | 3627491850        | We operate flexible offices and want Simplified Spaces for desk booking, meeting-room scheduling, branch availability, customer requests, and utilization reports.                           | Renzo              | Fabrizio            | Contarini         | Contarini Business Operations SRL   | Italy           | renzo.fabrizio.contarini.bookdemo.account389@yopmail.com    | No                     | +39                  | 3796284150           | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Custom Days Checkout Premium Plan | Ayan New Professional Diamond Plan    | Ayan Custom Months Hire Premium Plan     | Ayan Custom Days HR Flex Plan    | 37            | Gold          | Ayan Test Manager       | Creating this Italy-based all-app account to verify Book a Demo conversion with fresh customer, contact, plan, user, group, and manager details.                                               |
  | Simplified Checkout, Simplified Hire                                    | Cormac Eamon    | Wetherby       | cormac.eamon.wetherby.checkout.hire370@yopmail.com         | Wetherby Commerce Talent Ltd         | +44               | 7429183650        | We want connected payment and recruitment workflows covering transaction monitoring, candidate tracking, recruiter collaboration, and consolidated reporting.                              | Ruairi             | Declan              | Carrick           | Carrick Unified Services Ltd        | United Kingdom  | ruairi.declan.carrick.bookdemo.account390@yopmail.com       | Yes                    | +44                  | 7715268493           | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Yearly Spaces Enterprise Plan    | Ayan Custom Weeks Hire Flex Plan         | Ayan Monthly HR Business Plan    | 69            | Gold II       | Ayan Test Manager       | Testing this United Kingdom-based all-app account with new identity, email, phone, newsletter, users, group, and application plan values.                                                      |
  | Simplified HR, Simplified Spaces                                        | Lotte Evelien   | Van Kessel     | lotte.evelien.vankessel.hrspaces371@yopmail.com            | Van Kessel People and Offices BV     | +31               | 671842935         | We need HR and workspace workflows for employee administration, leave, attendance, desk reservations, meeting rooms, and office utilization.                                                 | Marit              | Jolanda             | Van Aken          | Van Aken Corporate Systems BV       | Netherlands     | marit.jolanda.vanaken.bookdemo.account391@yopmail.com       | No                     | +31                  | 621597843            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Monthly Spaces Business Plan     | Ayan Custom Months Hire Premium Plan     | Ayan Yearly HR Enterprise Plan   | 44            | Diamond       | Ayan Test Manager       | Creating this Netherlands-based all-app account using newly generated customer, account, contact, users, plans, group, and subscription information.                                          |
  | Simplified Checkout, Simplified HR                                      | Leopold Tassian | Grunwald       | leopold.tassian.grunwald.checkouthr372@yopmail.com         | Grunwald Business Operations GmbH    | +43               | 6507382914        | We are evaluating Checkout and HR modules for payment visibility, transaction processing, employee records, attendance, leave approvals, and reporting.                                      | Ottokar            | Rainer              | Falkenhayn        | Falkenhayn Integrated Solutions GmbH | Austria         | ottokar.rainer.falkenhayn.bookdemo.account392@yopmail.com   | Yes                    | +43                  | 6773159284           | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Custom Days Checkout Advance Plan | Ayan Daily Spaces Starter Plan        | Ayan Monthly Hire Business Plan          | Ayan Daily HR Starter Plan       | 55            | Silver        | Ayan Test Manager       | Validating this Austria-based all-app account through the complete workflow with fresh identity, email, phone, plans, users, group, and manager data.                                          |
  | Simplified Hire, Simplified HR                                          | Bogumila Renata | Sobczak        | bogumila.renata.sobczak.hirehr373@yopmail.com              | Sobczak Workforce Platforms Sp z oo  | +48               | 523946178         | We need integrated recruitment and HR processes covering candidates, interviews, hiring decisions, onboarding, employee records, attendance, and leave.                                      | Wioletta           | Grazyna             | Krolikowska       | Krolikowska Enterprise Systems Sp z oo | Poland        | wioletta.grazyna.krolikowska.bookdemo.account393@yopmail.com | No                   | +48                  | 579138462            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Yearly Checkout Enterprise Plan   | Ayan Weekly Spaces Growth Plan        | Ayan Custom Months Hire Premium Plan     | Ayan Custom Days HR Flex Plan    | 48            | Gold          | Ayan Test Manager       | Creating this Poland-based all-app account with new personal details, email, phone, account configuration, users, subscription, and group selection.                                          |
  | Simplified Checkout, Simplified Hire, Simplified HR                     | Frits Maurits   | De Graaf       | frits.maurits.degraaf.enterprise374@yopmail.com            | De Graaf Enterprise Services BV      | +31               | 613849275         | Our enterprise team is reviewing checkout, recruitment, and HR capabilities including permissions, workflow configuration, collaboration, and analytics.                                   | Boudewijn          | Casper              | Van Ommeren       | Van Ommeren Unified Technology BV   | Netherlands     | boudewijn.casper.vanommeren.bookdemo.account394@yopmail.com | Yes                    | +31                  | 687215439            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Monthly Spaces Business Plan     | Ayan Custom Weeks Hire Flex Plan         | Ayan Yearly HR Enterprise Plan   | 73            | Gold II       | Ayan Test Manager       | Testing this Netherlands-based all-app account using unique newly generated name, email, phone, users, plan assignments, and account notes.                                                    |
  | Simplified Checkout, Simplified Hire, Simplified HR, Simplified Spaces  | Adelgunde Irma  | Rosenfeld      | adelgunde.irma.rosenfeld.fullsuite375@yopmail.com          | Rosenfeld Integrated Solutions GmbH  | +49               | 17649283510       | We are evaluating the full Simplified suite for checkout, recruitment, HR, workspace operations, configuration, implementation, and reporting.                                               | Hedwig             | Almut               | Dornbach          | Dornbach Complete Business GmbH     | Germany         | hedwig.almut.dornbach.bookdemo.account395@yopmail.com       | No                     | +49                  | 15578319420          | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Yearly Spaces Enterprise Plan    | Ayan Custom Months Hire Premium Plan     | Ayan Monthly HR Business Plan    | 35            | Diamond       | Ayan Test Manager       | Creating this Germany-based full-suite account using fresh account identity, unique contact values, users, group, subscription, and application plans.                                        |
  | Simplified Checkout                                                     | Xabier Inigo    | Zubizarreta    | xabier.inigo.zubizarreta.checkout376@yopmail.com           | Zubizarreta Digital Commerce SL      | +34               | 693174825         | Our commerce team wants to improve checkout reliability, payment completion, transaction monitoring, refund visibility, and online sales reporting.                                          | Aitor              | Eneko               | Aramburu          | Aramburu Enterprise Cloud SL        | Spain           | aitor.eneko.aramburu.bookdemo.account396@yopmail.com        | Yes                    | +34                  | 618537294            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Weekly Spaces Growth Plan        | Ayan Custom Weeks Hire Flex Plan         | Ayan Monthly HR Business Plan    | 64            | Silver        | Ayan Test Manager       | Validating this Spain-based all-app account with never-repeated identity, email, phone, user count, group, manager, and plan combination.                                                       |
  | Simplified Hire                                                         | Nicoletta Sabina | Malfatti      | nicoletta.sabina.malfatti.hire377@yopmail.com              | Malfatti Recruitment Partners SRL    | +39               | 3448192760        | We are managing multiple hiring campaigns and want candidate profiles, job pipelines, interview coordination, recruiter assignments, and hiring reports.                                    | Ginevra            | Alessia             | Montanari         | Montanari Digital Systems SRL       | Italy           | ginevra.alessia.montanari.bookdemo.account397@yopmail.com  | No                     | +39                  | 3537281940           | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Monthly Spaces Business Plan     | Ayan Custom Months Hire Premium Plan     | Ayan Daily HR Starter Plan       | 41            | Gold          | Ayan Test Manager       | Creating this Italy-based all-app account to test new contact information, account setup, plan mapping, users, group assignment, and notes.                                                    |
  | Simplified HR                                                           | Eskil Torvald   | Lindqvist      | eskil.torvald.lindqvist.hr378@yopmail.com                  | Lindqvist People Management AB       | +46               | 714928365         | We need an HR platform for employee profiles, organizational structure, attendance records, leave workflows, permissions, communication, and analytics.                                      | Hampus             | Vilgot              | Stenmark          | Stenmark Business Platforms AB      | Sweden          | hampus.vilgot.stenmark.bookdemo.account398@yopmail.com     | Yes                    | +46                  | 762481539            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Yearly Checkout Enterprise Plan   | Ayan Daily Spaces Starter Plan        | Ayan Custom Weeks Hire Flex Plan         | Ayan Yearly HR Enterprise Plan   | 72            | Gold II       | Ayan Test Manager       | Testing this Sweden-based all-app account in the Book a Demo workflow using fresh identity, email, phone, subscription, users, group, and plans.                                               |
  | Simplified Spaces                                                       | Dries Cornelis  | Verbruggen     | dries.cornelis.verbruggen.spaces379@yopmail.com            | Verbruggen Flexible Offices BV       | +32               | 468291735         | We operate shared workspaces and want desk booking, room scheduling, customer requests, resource availability, location coordination, and utilization analytics.                             | Wouter             | Bastiaan            | De Clercq         | De Clercq Workspace Systems BV      | Belgium         | wouter.bastiaan.declercq.bookdemo.account399@yopmail.com   | No                     | +32                  | 492715638            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Custom Days Checkout Premium Plan | Ayan New Professional Diamond Plan    | Ayan Custom Months Hire Premium Plan     | Ayan Custom Days HR Flex Plan    | 46            | Diamond       | Ayan Test Manager       | Creating this Belgium-based all-app account with entirely fresh customer, email, phone, plan, user, group, newsletter, and manager values.                                                     |
  | Simplified Checkout, Simplified Hire                                    | Apolline Laure  | Maret          | apolline.laure.maret.checkout.hire380@yopmail.com          | Maret Commerce and Talent SAS        | +33               | 754839261         | We want connected checkout and recruitment management for payment visibility, applicant tracking, recruiter collaboration, hiring decisions, and reporting.                                 | Solange            | Mirette             | Chevalier         | Chevalier SaaS Operations SAS       | France          | solange.mirette.chevalier.bookdemo.account400@yopmail.com  | Yes                    | +33                  | 768315942            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Yearly Spaces Enterprise Plan    | Ayan Custom Weeks Hire Flex Plan         | Ayan Monthly HR Business Plan    | 57            | Silver        | Ayan Test Manager       | Validating this France-based all-app account across the complete workflow with newly generated account details and unique application plan values.                                            |
  | Simplified HR, Simplified Spaces                                        | Kaspar Lorenz   | Eberwein       | kaspar.lorenz.eberwein.hrspaces381@yopmail.com             | Eberwein Corporate Services GmbH     | +49               | 17463829150       | We need employee administration and workspace booking features covering attendance, leave, desks, meeting rooms, office availability, and reporting.                                         | Lorcan             | Seamus              | Blackwood         | Blackwood Integrated Services Ltd   | Ireland         | lorcan.seamus.blackwood.bookdemo.account401@yopmail.com    | No                     | +353                 | 861947325            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Monthly Spaces Business Plan     | Ayan Custom Months Hire Premium Plan     | Ayan Yearly HR Enterprise Plan   | 38            | Gold          | Ayan Test Manager       | Creating this Ireland-based all-app account with a fresh identity, email address, phone number, users, group, subscription, and plan configuration.                                             |
  | Simplified Checkout, Simplified HR                                      | Freja Linette   | Nordin         | freja.linette.nordin.checkouthr382@yopmail.com             | Nordin Business Systems AB           | +46               | 731582946         | We are reviewing Checkout and HR modules for online payments, transaction visibility, employee management, attendance, leave approvals, and reports.                                         | Alfhild            | Mette               | Bjornsen          | Bjornsen Unified Platforms AS       | Norway          | alfhild.mette.bjornsen.bookdemo.account402@yopmail.com     | Yes                    | +47                  | 41729683             | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Custom Days Checkout Advance Plan | Ayan Daily Spaces Starter Plan        | Ayan Monthly Hire Business Plan          | Ayan Daily HR Starter Plan       | 68            | Gold II       | Ayan Test Manager       | Testing this Norway-based all-app account with new customer identity, unique email and phone, users, plans, group, subscription, and manager data.                                             |
  | Simplified Hire, Simplified HR                                          | Tiziana Letizia | Orsini         | tiziana.letizia.orsini.hirehr383@yopmail.com               | Orsini Workforce Solutions SRL       | +39               | 3591846270        | Our workforce team needs recruitment and HR integration for candidate tracking, interviews, onboarding, employee records, attendance, leave, and reporting.                                  | Gaia               | Caterina            | Landucci          | Landucci Enterprise Operations SRL  | Italy           | gaia.caterina.landucci.bookdemo.account403@yopmail.com     | No                     | +39                  | 3485729160           | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Yearly Checkout Enterprise Plan   | Ayan Weekly Spaces Growth Plan        | Ayan Custom Months Hire Premium Plan     | Ayan Custom Days HR Flex Plan    | 52            | Diamond       | Ayan Test Manager       | Creating this Italy-based all-app account using newly generated personal details, contact values, application plans, user count, group, and notes.                                            |
  | Simplified Spaces                                                       | Soren Birk      | Madsen         | soren.birk.madsen.spaces384@yopmail.com                    | Madsen Workspace Coordination ApS    | +45               | 28471936          | We manage shared offices and want desk allocation, meeting-room scheduling, customer requests, branch availability, location coordination, and reports.                                      | Mikkel             | Rorik               | Norgaard          | Norgaard Corporate Systems ApS      | Denmark         | mikkel.rorik.norgaard.bookdemo.account404@yopmail.com      | Yes                    | +45                  | 32691847             | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Monthly Checkout Business Plan    | Ayan Monthly Spaces Business Plan     | Ayan Custom Weeks Hire Flex Plan         | Ayan Yearly HR Enterprise Plan   | 63            | Silver        | Ayan Test Manager       | Validating this Denmark-based all-app account through Book a Demo using fresh identity, email, phone, plans, users, group, and subscription values.                                            |
  | Simplified Checkout, Simplified Hire, Simplified HR, Simplified Spaces  | Odile Marguerite | Favre         | odile.marguerite.favre.allmodules385@yopmail.com           | Favre Strategic Operations SA        | +41               | 779463182         | We would like a demonstration of all Simplified modules covering checkout, recruitment, HR administration, workspace operations, pricing, and implementation.                                | Eliane             | Corinne             | Dutoit            | Dutoit Integrated Solutions SA      | Switzerland     | eliane.corinne.dutoit.bookdemo.account405@yopmail.com      | No                     | +41                  | 786215943            | all              | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes                 | Ayan Daily Checkout Starter Plan       | Ayan Yearly Spaces Enterprise Plan    | Ayan Custom Months Hire Premium Plan     | Ayan Monthly HR Business Plan    | 54            | Gold          | Ayan Test Manager       | Creating this Switzerland-based all-app account to verify the end-to-end workflow with unique new name, email, phone, users, group, plans, and manager data.                                   |