@Candidate
Feature: Candidate module feature-driven workflows

  @CandidateSearch
  Scenario Outline: Search Candidate <Candidate_First_Name> <Candidate_Last_Name>
    Given search Candidate using the following feature data
      | Email | <Candidate_Email> |
      | Phone Code | <Candidate_Phone_Code> |
      | Phone Number | <Candidate_Phone_Number> |
      | First Name | <Candidate_First_Name> |
      | Last Name | <Candidate_Last_Name> |
      | Professional Profile Link | <Candidate_Professional_Profile_Link> |
      | Source | <Candidate_Source> |
      | Country | <Candidate_Country> |
      | State | <Candidate_State> |
      | Current Salary Currency | <Candidate_Current_Salary_Currency> |
      | Current Salary | <Candidate_Current_Salary> |
      | Current Salary Duration | <Candidate_Current_Salary_Duration> |
      | Expected Salary Currency | <Candidate_Expected_Salary_Currency> |
      | Expected Salary | <Candidate_Expected_Salary> |
      | Expected Salary Duration | <Candidate_Expected_Salary_Duration> |
      | CV/Resume | <Candidate_CV_Resume> |
      | Skills | <Candidate_Skills> |
      | Relevant Experience | <Candidate_Relevant_Experience> |
      | Relevant Experience Unit | <Candidate_Relevant_Experience_Unit> |
      | Total Experience | <Candidate_Total_Experience> |
      | Total Experience Unit | <Candidate_Total_Experience_Unit> |
      | Notice Period | <Candidate_Notice_Period> |
      | Notice Period Unit | <Candidate_Notice_Period_Unit> |
      | Work Experience | <Candidate_Work_Experience> |
      | Education | <Candidate_Education> |
      | Cover Letter | <Candidate_Cover_Letter> |
      | Owner | <Candidate_Owner> |
      | Recruiter | <Candidate_Recruiter> |
      | Index | <Candidate_Index> |

      Examples:
      | Candidate_Email | Candidate_Phone_Code | Candidate_Phone_Number | Candidate_First_Name | Candidate_Last_Name | Candidate_Professional_Profile_Link | Candidate_Source | Candidate_Country | Candidate_State | Candidate_Current_Salary_Currency | Candidate_Current_Salary | Candidate_Current_Salary_Duration | Candidate_Expected_Salary_Currency | Candidate_Expected_Salary | Candidate_Expected_Salary_Duration | Candidate_CV_Resume | Candidate_Skills | Candidate_Relevant_Experience | Candidate_Relevant_Experience_Unit | Candidate_Total_Experience | Candidate_Total_Experience_Unit | Candidate_Notice_Period | Candidate_Notice_Period_Unit | Candidate_Work_Experience | Candidate_Education | Candidate_Cover_Letter | Candidate_Owner | Candidate_Recruiter | Candidate_Index |
      | saveliy.korenev2026ek@yopmail.com | +91 | 9826147305 | Saveliy | Korenev | https://www.linkedin.com/in/saveliy-korenev-2026-ek | Candidate Portal | India | West Bengal | INR(₹) | 1087000 | Yearly | INR(₹) | 1396000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 15 | Day(s) |  |  |  | Admin Ayan Sengupta | Admin Ayan Sengupta | 0 |
      | thibault.renaudin2026el@yopmail.com | +91 | 9763058421 | Thibault | Renaudin | https://www.linkedin.com/in/thibault-renaudin-2026-el | Consultancy | India | Maharashtra | INR(₹) | 1463000 | Yearly | INR(₹) | 1847000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 18 | Day(s) |  |  |  | Alexei Morozov | Alexei Morozov | 1 |
      | akseli.salminen2026em@yopmail.com | +91 | 9891472630 | Akseli | Salminen | https://www.linkedin.com/in/akseli-salminen-2026-em | Email | India | Karnataka | INR(₹) | 927000 | Yearly | INR(₹) | 1214000 | Yearly |  |  | 3 | Year(s) | 4 | Year(s) | 21 | Day(s) |  |  |  | Guest Alexei Sokolov | Guest Alexei Sokolov | 2 |
      | giacomo.parisi2026en@yopmail.com | +91 | 9718263549 | Giacomo | Parisi | https://www.linkedin.com/in/giacomo-parisi-2026-en | Import | India | Delhi | INR(₹) | 1736000 | Yearly | INR(₹) | 2189000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 24 | Day(s) |  |  |  | Interviewer Ivan Orlov | Interviewer Ivan Orlov | 3 |
      | fridolin.seebacher2026eo@yopmail.com | +91 | 9862507413 | Fridolin | Seebacher | https://www.linkedin.com/in/fridolin-seebacher-2026-eo | Indeed | India | Tamil Nadu | INR(₹) | 1328000 | Yearly | INR(₹) | 1685000 | Yearly |  |  | 5 | Year(s) | 6 | Year(s) | 27 | Day(s) |  |  |  | Nikolai Sidorov | Nikolai Sidorov | 4 |
      | jelle.wijnands2026ep@yopmail.com | +91 | 9784631205 | Jelle | Wijnands | https://www.linkedin.com/in/jelle-wijnands-2026-ep | LinkedIn | India | Telangana | INR(₹) | 1874000 | Yearly | INR(₹) | 2316000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 30 | Day(s) |  |  |  | Owner Mikhail Volkov | Owner Mikhail Volkov | 5 |
      | arkady.grebnev2026eq@yopmail.com | +91 | 9951347286 | Arkady | Grebnev | https://www.linkedin.com/in/arkady-grebnev-2026-eq | Naukri | India | Gujarat | INR(₹) | 856000 | Yearly | INR(₹) | 1123000 | Yearly |  |  | 2 | Year(s) | 3 | Year(s) | 33 | Day(s) |  |  |  | Rahul Chatterjee | Rahul Chatterjee | 6 |
      | zuzana.havelkova2026er@yopmail.com | +91 | 9817063542 | Zuzana | Havelkova | https://www.linkedin.com/in/zuzana-havelkova-2026-er | Candidate Portal | India | Uttar Pradesh | INR(₹) | 1589000 | Yearly | INR(₹) | 1987000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 36 | Day(s) |  |  |  | Admin Ayan Sengupta | Alexei Morozov | 7 |
      | levente.farkas2026es@yopmail.com | +91 | 9705384216 | Levente | Farkas | https://www.linkedin.com/in/levente-farkas-2026-es | Consultancy | India | Rajasthan | INR(₹) | 1116000 | Yearly | INR(₹) | 1428000 | Yearly |  |  | 3 | Year(s) | 4 | Year(s) | 39 | Day(s) |  |  |  | Alexei Morozov | Guest Alexei Sokolov | 8 |
      | siobhan.mckenna2026et@yopmail.com | +91 | 9938246157 | Siobhan | McKenna | https://www.linkedin.com/in/siobhan-mckenna-2026-et | Email | India | Madhya Pradesh | INR(₹) | 1647000 | Yearly | INR(₹) | 2075000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 42 | Day(s) |  |  |  | Guest Alexei Sokolov | Interviewer Ivan Orlov | 9 |
      | vadim.zelenin2026eu@yopmail.com | +91 | 9751604823 | Vadim | Zelenin | https://www.linkedin.com/in/vadim-zelenin-2026-eu | Import | India | Haryana | INR(₹) | 1295000 | Yearly | INR(₹) | 1663000 | Yearly |  |  | 5 | Year(s) | 6 | Year(s) | 45 | Day(s) |  |  |  | Interviewer Ivan Orlov | Nikolai Sidorov | 10 |
      | leonor.duarte2026ev@yopmail.com | +91 | 9885307164 | Leonor | Duarte | https://www.linkedin.com/in/leonor-duarte-2026-ev | Indeed | India | Punjab | INR(₹) | 1782000 | Yearly | INR(₹) | 2226000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 48 | Day(s) |  |  |  | Nikolai Sidorov | Owner Mikhail Volkov | 11 |
      | rune.solheim2026ew@yopmail.com | +91 | 9726841305 | Rune | Solheim | https://www.linkedin.com/in/rune-solheim-2026-ew | LinkedIn | India | Odisha | INR(₹) | 1948000 | Yearly | INR(₹) | 2441000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 51 | Day(s) |  |  |  | Owner Mikhail Volkov | Rahul Chatterjee | 12 |
      | teodora.petrescu2026ex@yopmail.com | +91 | 9962417830 | Teodora | Petrescu | https://www.linkedin.com/in/teodora-petrescu-2026-ex | Naukri | India | Bihar | INR(₹) | 1719000 | Yearly | INR(₹) | 2164000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 54 | Day(s) |  |  |  | Rahul Chatterjee | Admin Ayan Sengupta | 13 |
      | xabier.etxeberria2026ey@yopmail.com | +91 | 9803745261 | Xabier | Etxeberria | https://www.linkedin.com/in/xabier-etxeberria-2026-ey | Candidate Portal | India | Kerala | INR(₹) | 1236000 | Yearly | INR(₹) | 1581000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 57 | Day(s) |  |  |  | Admin Ayan Sengupta | Guest Alexei Sokolov | 14 |
      | domagoj.markovic2026ez@yopmail.com | +91 | 9748152630 | Domagoj | Markovic | https://www.linkedin.com/in/domagoj-markovic-2026-ez | Consultancy | India | Andhra Pradesh | INR(₹) | 1608000 | Yearly | INR(₹) | 2029000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 60 | Day(s) |  |  |  | Alexei Morozov | Interviewer Ivan Orlov | 15 |
      | mael.kerjean2026fa@yopmail.com | +91 | 9916307482 | Mael | Kerjean | https://www.linkedin.com/in/mael-kerjean-2026-fa | Email | India | Jharkhand | INR(₹) | 1492000 | Yearly | INR(₹) | 1907000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 63 | Day(s) |  |  |  | Guest Alexei Sokolov | Nikolai Sidorov | 16 |
      | platon.meshkov2026fb@yopmail.com | +91 | 9792453168 | Platon | Meshkov | https://www.linkedin.com/in/platon-meshkov-2026-fb | Import | India | Assam | INR(₹) | 1839000 | Yearly | INR(₹) | 2293000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 66 | Day(s) |  |  |  | Interviewer Ivan Orlov | Owner Mikhail Volkov | 17 |
      | egle.kazlauskaite2026fc@yopmail.com | +91 | 9837602145 | Egle | Kazlauskaite | https://www.linkedin.com/in/egle-kazlauskaite-2026-fc | Indeed | India | Chhattisgarh | INR(₹) | 1059000 | Yearly | INR(₹) | 1372000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 69 | Day(s) |  |  |  | Nikolai Sidorov | Rahul Chatterjee | 18 |
      | gennady.ustinov2026fd@yopmail.com | +91 | 9684317520 | Gennady | Ustinov | https://www.linkedin.com/in/gennady-ustinov-2026-fd | LinkedIn | India | Goa | INR(₹) | 2017000 | Yearly | INR(₹) | 2529000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 75 | Day(s) |  |  |  | Owner Mikhail Volkov | Admin Ayan Sengupta | 19 |





  @CandidateAdd
  Scenario Outline: Add Candidate <Candidate_First_Name> <Candidate_Last_Name> and assign Job <Job_Job_Posting_Name>
    Given Candidate Add data is provided from the feature file
      | Email | <Candidate_Email> |
      | Phone Code | <Candidate_Phone_Code> |
      | Phone Number | <Candidate_Phone_Number> |
      | First Name | <Candidate_First_Name> |
      | Last Name | <Candidate_Last_Name> |
      | Professional Profile Link | <Candidate_Professional_Profile_Link> |
      | Source | <Candidate_Source> |
      | Country | <Candidate_Country> |
      | State | <Candidate_State> |
      | Current Salary Currency | <Candidate_Current_Salary_Currency> |
      | Current Salary | <Candidate_Current_Salary> |
      | Current Salary Duration | <Candidate_Current_Salary_Duration> |
      | Expected Salary Currency | <Candidate_Expected_Salary_Currency> |
      | Expected Salary | <Candidate_Expected_Salary> |
      | Expected Salary Duration | <Candidate_Expected_Salary_Duration> |
      | CV/Resume | <Candidate_CV_Resume> |
      | Skills | <Candidate_Skills> |
      | Relevant Experience | <Candidate_Relevant_Experience> |
      | Relevant Experience Unit | <Candidate_Relevant_Experience_Unit> |
      | Total Experience | <Candidate_Total_Experience> |
      | Total Experience Unit | <Candidate_Total_Experience_Unit> |
      | Notice Period | <Candidate_Notice_Period> |
      | Notice Period Unit | <Candidate_Notice_Period_Unit> |
      | Work Experience | <Candidate_Work_Experience> |
      | Education | <Candidate_Education> |
      | Cover Letter | <Candidate_Cover_Letter> |
      | Owner | <Candidate_Owner> |
      | Recruiter | <Candidate_Recruiter> |
      | Index | <Candidate_Index> |
    When the Candidate is added using the following Job feature data
      | Select Template | <Job_Select_Template> |
      | Job Posting Name | <Job_Job_Posting_Name> |
      | Expiry Date | <Job_Expiry_Date> |
      | Job Urgency | <Job_Job_Urgency> |
      | Job Title | <Job_Job_Title> |
      | Department / Division | <Job_Department_Division> |
      | Employment Type | <Job_Employment_Type> |
      | Category | <Job_Category> |
      | Required Education | <Job_Required_Education> |
      | Required Experience | <Job_Required_Experience> |
      | Expected Hiring Date | <Job_Expected_Hiring_Date> |
      | Number of Positions | <Job_Number_of_Positions> |
      | When Positions Fulfilled | <Job_When_Positions_Fulfilled> |
      | Job Description | <Job_Job_Description> |
      | Job Requirements | <Job_Job_Requirements> |
      | Benefits | <Job_Benefits> |
      | Country | <Job_Country> |
      | City / State | <Job_City_State> |
      | Remote | <Job_Remote> |
      | Salary From 1 | <Job_Salary_From_1> |
      | Salary To 1 | <Job_Salary_To_1> |
      | Unit 1 | <Job_Unit_1> |
      | Currency 1 | <Job_Currency_1> |
      | Salary From 2 | <Job_Salary_From_2> |
      | Salary To 2 | <Job_Salary_To_2> |
      | Unit 2 | <Job_Unit_2> |
      | Currency 2 | <Job_Currency_2> |
      | Salary From 3 | <Job_Salary_From_3> |
      | Salary To 3 | <Job_Salary_To_3> |
      | Unit 3 | <Job_Unit_3> |
      | Currency 3 | <Job_Currency_3> |
      | Screening Question 1 | <Job_Screening_Question_1> |
      | Screening Question 2 | <Job_Screening_Question_2> |
      | Screening Question 3 | <Job_Screening_Question_3> |
      | Save As Job Posting Template | <Job_Save_As_Job_Posting_Template> |

    Examples:
      | Candidate_Email | Candidate_Phone_Code | Candidate_Phone_Number | Candidate_First_Name | Candidate_Last_Name | Candidate_Professional_Profile_Link | Candidate_Source | Candidate_Country | Candidate_State | Candidate_Current_Salary_Currency | Candidate_Current_Salary | Candidate_Current_Salary_Duration | Candidate_Expected_Salary_Currency | Candidate_Expected_Salary | Candidate_Expected_Salary_Duration | Candidate_CV_Resume | Candidate_Skills | Candidate_Relevant_Experience | Candidate_Relevant_Experience_Unit | Candidate_Total_Experience | Candidate_Total_Experience_Unit | Candidate_Notice_Period | Candidate_Notice_Period_Unit | Candidate_Work_Experience | Candidate_Education | Candidate_Cover_Letter | Candidate_Owner | Candidate_Recruiter | Candidate_Index | Job_Select_Template | Job_Job_Posting_Name | Job_Expiry_Date | Job_Job_Urgency | Job_Job_Title | Job_Department_Division | Job_Employment_Type | Job_Category | Job_Required_Education | Job_Required_Experience | Job_Expected_Hiring_Date | Job_Number_of_Positions | Job_When_Positions_Fulfilled | Job_Job_Description | Job_Job_Requirements | Job_Benefits | Job_Country | Job_City_State | Job_Remote | Job_Salary_From_1 | Job_Salary_To_1 | Job_Unit_1 | Job_Currency_1 | Job_Salary_From_2 | Job_Salary_To_2 | Job_Unit_2 | Job_Currency_2 | Job_Salary_From_3 | Job_Salary_To_3 | Job_Unit_3 | Job_Currency_3 | Job_Screening_Question_1 | Job_Screening_Question_2 | Job_Screening_Question_3 | Job_Save_As_Job_Posting_Template |
      | saveliy.korenev2026ek@yopmail.com | +91 | 9826147305 | Saveliy | Korenev | https://www.linkedin.com/in/saveliy-korenev-2026-ek | Candidate Portal | India | West Bengal | INR(₹) | 1087000 | Yearly | INR(₹) | 1396000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 15 | Day(s) |  |  |  | Admin Ayan Sengupta | Admin Ayan Sengupta | 0 | Custom Template | Adaptive Threat Avoidance Campaign 21 | 22-08-2026 | High | Adaptive Threat Avoidance Systems Engineer | Artificial Intelligence and Autonomy | Full Time | Information Technology | M.Tech | Senior | 15-10-2026 | 1 | Enable Waitlist | Develop real-time threat assessment, evasive routing, and adaptive response logic for autonomous aerial platforms. | Experience in autonomous decision systems, path planning, sensor-driven control, and real-time safety logic. | Insurance, advanced autonomy research, mission systems exposure, and long-term technical growth. | India | Karnataka | Yes | 1950000 | 2600000 | Per Annum | INR(₹) | 2600001 | 3350000 | Per Annum | INR(₹) | 3350001 | 4200000 | Per Annum | INR(₹) | Have you developed autonomous avoidance, path-planning, or safety-control systems? | Have you integrated sensor inputs into real-time vehicle decision logic? | Which autonomy, robotics, or simulation frameworks have you used? | No |
      | thibault.renaudin2026el@yopmail.com | +91 | 9763058421 | Thibault | Renaudin | https://www.linkedin.com/in/thibault-renaudin-2026-el | Consultancy | India | Maharashtra | INR(₹) | 1463000 | Yearly | INR(₹) | 1847000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 18 | Day(s) |  |  |  | Alexei Morozov | Alexei Morozov | 1 | Custom Template | Airborne Cyber Resilience Campaign 22 | 24-08-2026 | High | Airborne Cyber Resilience Engineer | Cybersecurity | Full Time | Information Technology | B.Tech | Senior | 18-10-2026 | 2 | Close Job | Secure airborne computing, telemetry interfaces, firmware communication, and mission data against cyber threats. | Experience in embedded security, secure communications, vulnerability assessment, and defensive system hardening. | Insurance, cybersecurity specialization, mission-critical systems exposure, and certification support. | India | Telangana | No | 1500000 | 2050000 | Per Annum | INR(₹) | 2050001 | 2700000 | Per Annum | INR(₹) | 2700001 | 3400000 | Per Annum | INR(₹) | Do you have embedded or avionics cybersecurity experience? | Have you performed threat modeling or security testing for connected systems? | Which security tools, protocols, or hardening standards have you applied? | No |
      | akseli.salminen2026em@yopmail.com | +91 | 9891472630 | Akseli | Salminen | https://www.linkedin.com/in/akseli-salminen-2026-em | Email | India | Karnataka | INR(₹) | 927000 | Yearly | INR(₹) | 1214000 | Yearly |  |  | 3 | Year(s) | 4 | Year(s) | 21 | Day(s) |  |  |  | Guest Alexei Sokolov | Guest Alexei Sokolov | 2 | Custom Template | Cooperative Navigation Intelligence Campaign 23 | 26-08-2026 | High | Cooperative Navigation Intelligence Engineer | Flight Control Systems | Full Time | Information Technology | M.Tech | Mid-senior | 21-10-2026 | 2 | Enable Waitlist | Build cooperative navigation, formation coordination, and multi-vehicle route intelligence for unmanned systems. | Experience in distributed navigation, control algorithms, state estimation, and multi-agent coordination. | Insurance, autonomy research, algorithm ownership, and cross-functional engineering exposure. | India | Maharashtra | Yes | 1600000 | 2150000 | Per Annum | INR(₹) | 2150001 | 2800000 | Per Annum | INR(₹) | 2800001 | 3500000 | Per Annum | INR(₹) | Have you worked on cooperative navigation or multi-agent control systems? | Do you have experience with state estimation or distributed route planning? | Which numerical, robotics, or control-analysis tools have you used? | No |
      | giacomo.parisi2026en@yopmail.com | +91 | 9718263549 | Giacomo | Parisi | https://www.linkedin.com/in/giacomo-parisi-2026-en | Import | India | Delhi | INR(₹) | 1736000 | Yearly | INR(₹) | 2189000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 24 | Day(s) |  |  |  | Interviewer Ivan Orlov | Interviewer Ivan Orlov | 3 | Custom Template | Multispectral Scene Analytics Campaign 24 | 28-08-2026 | High | Multispectral Scene Analytics Engineer | Computer Vision | Full Time | Information Technology | M.Tech | Mid-senior | 24-10-2026 | 2 | Close Job | Develop multispectral image analysis, object classification, scene understanding, and persistent tracking pipelines. | Experience in computer vision, deep learning, image fusion, model evaluation, and production deployment. | Insurance, applied AI research, high-impact vision projects, and technical leadership opportunities. | India | Haryana | Yes | 1500000 | 2050000 | Per Annum | INR(₹) | 2050001 | 2650000 | Per Annum | INR(₹) | 2650001 | 3250000 | Per Annum | INR(₹) | Have you built image-classification, detection, or tracking pipelines? | Do you have experience combining visible, thermal, or multispectral imagery? | Which model-training and inference frameworks have you used? | No |
      | fridolin.seebacher2026eo@yopmail.com | +91 | 9862507413 | Fridolin | Seebacher | https://www.linkedin.com/in/fridolin-seebacher-2026-eo | Indeed | India | Tamil Nadu | INR(₹) | 1328000 | Yearly | INR(₹) | 1685000 | Yearly |  |  | 5 | Year(s) | 6 | Year(s) | 27 | Day(s) |  |  |  | Nikolai Sidorov | Nikolai Sidorov | 4 | Custom Template | Deterministic Embedded Control Campaign 25 | 30-08-2026 | High | Deterministic Embedded Control Engineer | Embedded Systems | Full Time | Information Technology | B.Tech | Mid-senior | 27-10-2026 | 3 | Close Job | Develop deterministic firmware, device drivers, timing-critical control loops, and fault-tolerant embedded services. | Experience in embedded C or C++, RTOS, hardware interfaces, debugging, and real-time performance analysis. | Insurance, firmware ownership, hardware-lab exposure, and structured technical growth. | India | West Bengal | No | 1000000 | 1450000 | Per Annum | INR(₹) | 1450001 | 1900000 | Per Annum | INR(₹) | 1900001 | 2400000 | Per Annum | INR(₹) | Do you have production experience with embedded C, C++, or RTOS development? | Have you debugged timing, memory, or hardware-interface issues? | Which microcontrollers, debuggers, and communication buses have you used? | No |
      | jelle.wijnands2026ep@yopmail.com | +91 | 9784631205 | Jelle | Wijnands | https://www.linkedin.com/in/jelle-wijnands-2026-ep | LinkedIn | India | Telangana | INR(₹) | 1874000 | Yearly | INR(₹) | 2316000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 30 | Day(s) |  |  |  | Owner Mikhail Volkov | Owner Mikhail Volkov | 5 | Custom Template | Beyond-Line-of-Sight Connectivity Campaign 26 | 01-09-2026 | High | Beyond-Line-of-Sight Connectivity Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 30-10-2026 | 1 | Enable Waitlist | Design resilient long-range communication, relay networking, telemetry continuity, and link-quality monitoring systems. | Experience in RF communication, mesh networking, telemetry, antenna systems, and field link validation. | Insurance, communication systems specialization, field-testing exposure, and career advancement. | India | Tamil Nadu | No | 1550000 | 2100000 | Per Annum | INR(₹) | 2100001 | 2750000 | Per Annum | INR(₹) | 2750001 | 3450000 | Per Annum | INR(₹) | Have you engineered long-range telemetry or beyond-line-of-sight communication links? | Do you have experience with mesh networking, RF planning, or link-budget analysis? | Which RF measurement and network-validation tools have you used? | No |
      | arkady.grebnev2026eq@yopmail.com | +91 | 9951347286 | Arkady | Grebnev | https://www.linkedin.com/in/arkady-grebnev-2026-eq | Naukri | India | Gujarat | INR(₹) | 856000 | Yearly | INR(₹) | 1123000 | Yearly |  |  | 2 | Year(s) | 3 | Year(s) | 33 | Day(s) |  |  |  | Rahul Chatterjee | Rahul Chatterjee | 6 | Custom Template | Precision Landing Intelligence Campaign 27 | 03-09-2026 | High | Precision Landing Intelligence Engineer | UAV Engineering | Full Time | Information Technology | M.Tech | Senior | 02-11-2026 | 1 | Close Job | Develop precision landing, terrain-relative navigation, touchdown validation, and degraded-GNSS recovery logic. | Experience in navigation fusion, estimation algorithms, landing control, and real-world flight validation. | Insurance, advanced navigation ownership, flight-test exposure, and deep systems learning. | India | Uttar Pradesh | No | 1800000 | 2400000 | Per Annum | INR(₹) | 2400001 | 3050000 | Per Annum | INR(₹) | 3050001 | 3700000 | Per Annum | INR(₹) | Have you developed precision landing or terrain-relative navigation systems? | Do you have experience with degraded-GNSS or sensor-fusion recovery logic? | Which navigation algorithms and flight-validation tools have you used? | No |
      | zuzana.havelkova2026er@yopmail.com | +91 | 9817063542 | Zuzana | Havelkova | https://www.linkedin.com/in/zuzana-havelkova-2026-er | Candidate Portal | India | Uttar Pradesh | INR(₹) | 1589000 | Yearly | INR(₹) | 1987000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 36 | Day(s) |  |  |  | Admin Ayan Sengupta | Alexei Morozov | 7 | Custom Template | Stabilized Sensor Platform Campaign 28 | 05-09-2026 | High | Stabilized Sensor Platform Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Mid-senior | 05-11-2026 | 2 | Enable Waitlist | Integrate stabilized gimbals, imaging sensors, control interfaces, and payload health-monitoring systems. | Experience in electromechanical integration, gimbal control, sensor interfaces, and environmental validation. | Insurance, payload ownership, laboratory and field exposure, and technical progression. | India | Gujarat | No | 1100000 | 1550000 | Per Annum | INR(₹) | 1550001 | 2050000 | Per Annum | INR(₹) | 2050001 | 2550000 | Per Annum | INR(₹) | Do you have gimbal, stabilized platform, or imaging-payload integration experience? | Have you validated electromechanical systems under vibration or thermal conditions? | Which sensor interfaces and control tools have you worked with? | No |
      | levente.farkas2026es@yopmail.com | +91 | 9705384216 | Levente | Farkas | https://www.linkedin.com/in/levente-farkas-2026-es | Consultancy | India | Rajasthan | INR(₹) | 1116000 | Yearly | INR(₹) | 1428000 | Yearly |  |  | 3 | Year(s) | 4 | Year(s) | 39 | Day(s) |  |  |  | Alexei Morozov | Guest Alexei Sokolov | 8 | Custom Template | Mission Telemetry Visualization Campaign 29 | 07-09-2026 | Medium | Mission Telemetry Visualization Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Mid-senior | 08-11-2026 | 2 | Close Job | Build real-time telemetry dashboards, alerting workflows, mission replay, and operator-focused visualization tools. | Experience in frontend engineering, streaming data, visualization libraries, and operational monitoring interfaces. | Insurance, mission software exposure, UI ownership, and cross-domain engineering growth. | India | Odisha | Yes | 1100000 | 1600000 | Per Annum | INR(₹) | 1600001 | 2200000 | Per Annum | INR(₹) | 2200001 | 2800000 | Per Annum | INR(₹) | Have you built real-time dashboards or streaming-data visualizations? | Do you have experience designing alerting, replay, or operator-monitoring workflows? | Which frontend and data-visualization technologies have you used? | No |
      | siobhan.mckenna2026et@yopmail.com | +91 | 9938246157 | Siobhan | McKenna | https://www.linkedin.com/in/siobhan-mckenna-2026-et | Email | India | Madhya Pradesh | INR(₹) | 1647000 | Yearly | INR(₹) | 2075000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 42 | Day(s) |  |  |  | Guest Alexei Sokolov | Interviewer Ivan Orlov | 9 | Custom Template | Dynamic Mission Replanning Campaign 30 | 09-09-2026 | High | Dynamic Mission Replanning Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 11-11-2026 | 1 | Enable Waitlist | Develop dynamic route replanning, mission constraint handling, contingency logic, and geospatial decision services. | Experience in geospatial software, optimization algorithms, route planning, and mission-management platforms. | Insurance, strategic software ownership, mapping systems exposure, and leadership growth. | India | Kerala | Yes | 1500000 | 2050000 | Per Annum | INR(₹) | 2050001 | 2650000 | Per Annum | INR(₹) | 2650001 | 3250000 | Per Annum | INR(₹) | Have you developed dynamic routing, optimization, or mission-replanning software? | Do you have experience with geospatial constraints, maps, or waypoint logic? | Which optimization libraries, mapping tools, or backend stacks have you used? | No |
      | vadim.zelenin2026eu@yopmail.com | +91 | 9751604823 | Vadim | Zelenin | https://www.linkedin.com/in/vadim-zelenin-2026-eu | Import | India | Haryana | INR(₹) | 1295000 | Yearly | INR(₹) | 1663000 | Yearly |  |  | 5 | Year(s) | 6 | Year(s) | 45 | Day(s) |  |  |  | Interviewer Ivan Orlov | Nikolai Sidorov | 10 | Custom Template | High-Fidelity Autonomy Simulation Campaign 31 | 11-09-2026 | Medium | High-Fidelity Autonomy Simulation Engineer | Research and Development | Full Time | Information Technology | M.Tech | Mid-senior | 14-11-2026 | 2 | Close Job | Create high-fidelity autonomy simulations, synthetic environments, sensor models, and repeatable scenario libraries. | Experience in simulation engineering, physics modeling, scenario automation, and model validation. | Insurance, research ownership, simulation-lab exposure, and continuous learning support. | India | Rajasthan | Yes | 1150000 | 1600000 | Per Annum | INR(₹) | 1600001 | 2150000 | Per Annum | INR(₹) | 2150001 | 2700000 | Per Annum | INR(₹) | Have you created simulation environments for robotics, autonomy, or aerospace systems? | Do you have experience modeling sensors, physics, or environmental conditions? | Which simulation engines and scenario-automation tools have you used? | No |
      | leonor.duarte2026ev@yopmail.com | +91 | 9885307164 | Leonor | Duarte | https://www.linkedin.com/in/leonor-duarte-2026-ev | Indeed | India | Punjab | INR(₹) | 1782000 | Yearly | INR(₹) | 2226000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 48 | Day(s) |  |  |  | Nikolai Sidorov | Owner Mikhail Volkov | 11 | Custom Template | Environmental Qualification Campaign 32 | 13-09-2026 | High | Environmental Qualification Test Engineer | Testing and Validation | Full Time | Quality Analysis | B.Tech | Mid-senior | 17-11-2026 | 2 | Close Job | Plan and execute vibration, thermal, ingress, endurance, and environmental qualification tests for UAV subsystems. | Experience in hardware qualification, test planning, instrumentation, failure analysis, and compliance reporting. | Insurance, qualification-lab exposure, subsystem ownership, and structured growth. | India | Madhya Pradesh | No | 1000000 | 1400000 | Per Annum | INR(₹) | 1400001 | 1850000 | Per Annum | INR(₹) | 1850001 | 2300000 | Per Annum | INR(₹) | Have you performed vibration, thermal, ingress, or endurance qualification testing? | Do you have experience with instrumentation, test fixtures, or failure analysis? | Which qualification standards and reporting tools have you used? | No |
      | rune.solheim2026ew@yopmail.com | +91 | 9726841305 | Rune | Solheim | https://www.linkedin.com/in/rune-solheim-2026-ew | LinkedIn | India | Odisha | INR(₹) | 1948000 | Yearly | INR(₹) | 2441000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 51 | Day(s) |  |  |  | Owner Mikhail Volkov | Rahul Chatterjee | 12 | Custom Template | Mission Software Verification Campaign 33 | 15-09-2026 | Medium | Mission Software Verification Engineer | Quality Assurance | Full Time | Quality Analysis | B.Tech | Junior | 20-11-2026 | 3 | Enable Waitlist | Verify mission workflows, interface behavior, regression coverage, telemetry accuracy, and release readiness. | Experience in functional testing, API testing, regression design, defect reporting, and traceability. | Insurance, mission-software exposure, automation learning, and a clear QA growth path. | India | Bihar | Yes | 700000 | 950000 | Per Annum | INR(₹) | 950001 | 1200000 | Per Annum | INR(₹) | 1200001 | 1500000 | Per Annum | INR(₹) | Do you have functional, API, or regression testing experience? | Have you validated end-to-end workflows involving multiple system interfaces? | Which QA, API, automation, and defect-tracking tools have you used? | No |
      | teodora.petrescu2026ex@yopmail.com | +91 | 9962417830 | Teodora | Petrescu | https://www.linkedin.com/in/teodora-petrescu-2026-ex | Naukri | India | Bihar | INR(₹) | 1719000 | Yearly | INR(₹) | 2164000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 54 | Day(s) |  |  |  | Rahul Chatterjee | Admin Ayan Sengupta | 13 | Custom Template | Precision Assembly Optimization Campaign 34 | 17-09-2026 | High | Precision Assembly Optimization Engineer | Manufacturing | Full Time | Professional Service | B.Tech | Mid-senior | 23-11-2026 | 2 | Close Job | Optimize precision assembly, workstation design, production controls, and first-pass quality for aerial systems. | Experience in manufacturing engineering, lean improvement, assembly tooling, and production-quality analysis. | Insurance, production ownership, process-improvement exposure, and operations leadership growth. | India | Maharashtra | No | 900000 | 1250000 | Per Annum | INR(₹) | 1250001 | 1650000 | Per Annum | INR(₹) | 1650001 | 2050000 | Per Annum | INR(₹) | Have you improved assembly quality, takt time, or first-pass yield? | Do you have experience with tooling, work instructions, or lean manufacturing? | Which production-analysis and quality-control methods have you applied? | No |
      | xabier.etxeberria2026ey@yopmail.com | +91 | 9803745261 | Xabier | Etxeberria | https://www.linkedin.com/in/xabier-etxeberria-2026-ey | Candidate Portal | India | Kerala | INR(₹) | 1236000 | Yearly | INR(₹) | 1581000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 57 | Day(s) |  |  |  | Admin Ayan Sengupta | Guest Alexei Sokolov | 14 | Custom Template | Lightweight Structural Systems Campaign 35 | 19-09-2026 | High | Lightweight Structural Systems Engineer | Mechanical Design | Full Time | Information Technology | B.Tech | Mid-senior | 26-11-2026 | 2 | Enable Waitlist | Design lightweight airframe structures, equipment mounts, protective housings, and maintainable mechanical assemblies. | Experience in CAD, structural analysis, material selection, tolerance design, and prototype validation. | Insurance, prototype ownership, structural design exposure, and professional development. | India | Jharkhand | No | 1000000 | 1400000 | Per Annum | INR(₹) | 1400001 | 1850000 | Per Annum | INR(₹) | 1850001 | 2300000 | Per Annum | INR(₹) | Do you have experience designing lightweight structural or aerospace components? | Have you performed tolerance, material, or structural analysis for prototypes? | Which CAD and engineering-analysis tools have you used? | No |
      | domagoj.markovic2026ez@yopmail.com | +91 | 9748152630 | Domagoj | Markovic | https://www.linkedin.com/in/domagoj-markovic-2026-ez | Consultancy | India | Andhra Pradesh | INR(₹) | 1608000 | Yearly | INR(₹) | 2029000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 60 | Day(s) |  |  |  | Alexei Morozov | Interviewer Ivan Orlov | 15 | Custom Template | Hybrid Propulsion Performance Campaign 36 | 21-09-2026 | High | Hybrid Propulsion Performance Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 29-11-2026 | 1 | Close Job | Optimize hybrid propulsion, energy management, endurance prediction, and powertrain thermal performance. | Experience in propulsion, batteries, motors, power electronics, thermal analysis, and performance testing. | Insurance, propulsion ownership, advanced hardware testing, and technical leadership opportunities. | India | Uttar Pradesh | No | 1450000 | 1950000 | Per Annum | INR(₹) | 1950001 | 2550000 | Per Annum | INR(₹) | 2550001 | 3200000 | Per Annum | INR(₹) | Have you worked on electric, hybrid, or high-endurance propulsion systems? | Do you have experience with energy management, thermal analysis, or endurance modeling? | Which propulsion, battery, and performance-analysis tools have you used? | No |
      | mael.kerjean2026fa@yopmail.com | +91 | 9916307482 | Mael | Kerjean | https://www.linkedin.com/in/mael-kerjean-2026-fa | Email | India | Jharkhand | INR(₹) | 1492000 | Yearly | INR(₹) | 1907000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 63 | Day(s) |  |  |  | Guest Alexei Sokolov | Nikolai Sidorov | 16 | Custom Template | Autonomous Platform Roadmap Campaign 37 | 23-09-2026 | Medium | Autonomous Platform Roadmap Manager | Product Management | Full Time | Information Technology | MBA | Senior | 02-12-2026 | 1 | Enable Waitlist | Own autonomous platform roadmaps, feature prioritization, customer alignment, and cross-functional delivery planning. | Experience in product strategy, complex engineering programs, stakeholder management, and roadmap governance. | Insurance, strategic ownership, executive visibility, and leadership development. | India | Gujarat | Yes | 1650000 | 2250000 | Per Annum | INR(₹) | 2250001 | 2900000 | Per Annum | INR(₹) | 2900001 | 3550000 | Per Annum | INR(₹) | Have you managed roadmaps for complex hardware-software or autonomous platforms? | Do you have experience balancing customer priorities with engineering constraints? | How do you measure roadmap value, delivery risk, and product readiness? | No |
      | platon.meshkov2026fb@yopmail.com | +91 | 9792453168 | Platon | Meshkov | https://www.linkedin.com/in/platon-meshkov-2026-fb | Import | India | Assam | INR(₹) | 1839000 | Yearly | INR(₹) | 2293000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 66 | Day(s) |  |  |  | Interviewer Ivan Orlov | Owner Mikhail Volkov | 17 | Custom Template | Strategic Aerospace Partnerships Campaign 38 | 25-09-2026 | Medium | Strategic Aerospace Partnerships Manager | Sales and Business Development | Full Time | Marketing | MBA | Senior | 05-12-2026 | 1 | Close Job | Develop aerospace partnerships, solution proposals, market-entry programs, and long-term institutional relationships. | Experience in enterprise partnerships, proposal development, account strategy, and technical solution positioning. | Insurance, strategic client exposure, partnership ownership, and long-term career growth. | India | Tamil Nadu | No | 1350000 | 1850000 | Per Annum | INR(₹) | 1850001 | 2400000 | Per Annum | INR(₹) | 2400001 | 3000000 | Per Annum | INR(₹) | Do you have enterprise partnership, aerospace, or strategic account experience? | Have you led proposals, solution presentations, or multi-party negotiations? | How do you qualify and develop long-cycle institutional opportunities? | No |
      | egle.kazlauskaite2026fc@yopmail.com | +91 | 9837602145 | Egle | Kazlauskaite | https://www.linkedin.com/in/egle-kazlauskaite-2026-fc | Indeed | India | Chhattisgarh | INR(₹) | 1059000 | Yearly | INR(₹) | 1372000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 69 | Day(s) |  |  |  | Nikolai Sidorov | Rahul Chatterjee | 18 | Custom Template | Remote Site Readiness Campaign 39 | 27-09-2026 | High | Remote Site Readiness Engineer | Field Deployment | Full Time | Professional Service | B.Tech | Mid-senior | 08-12-2026 | 3 | Enable Waitlist | Prepare remote deployment sites, verify equipment readiness, coordinate field trials, and resolve operational issues. | Experience in field deployment, site commissioning, technical troubleshooting, and operational documentation. | Insurance, field-mission exposure, travel support, and accelerated operations learning. | India | Kerala | No | 950000 | 1300000 | Per Annum | INR(₹) | 1300001 | 1700000 | Per Annum | INR(₹) | 1700001 | 2150000 | Per Annum | INR(₹) | Have you supported remote-site deployment, commissioning, or field trials? | Are you comfortable with frequent travel and on-site technical troubleshooting? | How do you document readiness gaps, incidents, and corrective actions? | No |
      | gennady.ustinov2026fd@yopmail.com | +91 | 9684317520 | Gennady | Ustinov | https://www.linkedin.com/in/gennady-ustinov-2026-fd | LinkedIn | India | Goa | INR(₹) | 2017000 | Yearly | INR(₹) | 2529000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 75 | Day(s) |  |  |  | Owner Mikhail Volkov | Admin Ayan Sengupta | 19 | Custom Template | Advanced Aerial Concepts Campaign 40 | 29-09-2026 | Medium | Advanced Aerial Concepts Research Engineer | Research and Development | Full Time | Information Technology | M.Tech | Senior | 11-12-2026 | 1 | Close Job | Investigate next-generation aerial architectures, prototype concepts, emerging technologies, and feasibility evidence. | Experience in research engineering, concept development, prototyping, technical experimentation, and evaluation. | Insurance, exploratory R&D ownership, prototype funding, and senior technical growth. | India | Andhra Pradesh | Yes | 1550000 | 2100000 | Per Annum | INR(₹) | 2100001 | 2750000 | Per Annum | INR(₹) | 2750001 | 3400000 | Per Annum | INR(₹) | Have you led advanced-concept research or engineering prototype programs? | Do you have experience turning early technical ideas into testable prototypes? | How do you structure experiments, evaluate feasibility, and communicate research outcomes? | No |


  @CandidateInterview
  Scenario Outline: Schedule interview for Candidate <Candidate_First_Name> <Candidate_Last_Name>
    Given schedule Candidate interview using the following feature data
      | Email | <Candidate_Email> |
      | Phone Code | <Candidate_Phone_Code> |
      | Phone Number | <Candidate_Phone_Number> |
      | First Name | <Candidate_First_Name> |
      | Last Name | <Candidate_Last_Name> |
      | Professional Profile Link | <Candidate_Professional_Profile_Link> |
      | Source | <Candidate_Source> |
      | Country | <Candidate_Country> |
      | State | <Candidate_State> |
      | Current Salary Currency | <Candidate_Current_Salary_Currency> |
      | Current Salary | <Candidate_Current_Salary> |
      | Current Salary Duration | <Candidate_Current_Salary_Duration> |
      | Expected Salary Currency | <Candidate_Expected_Salary_Currency> |
      | Expected Salary | <Candidate_Expected_Salary> |
      | Expected Salary Duration | <Candidate_Expected_Salary_Duration> |
      | CV/Resume | <Candidate_CV_Resume> |
      | Skills | <Candidate_Skills> |
      | Relevant Experience | <Candidate_Relevant_Experience> |
      | Relevant Experience Unit | <Candidate_Relevant_Experience_Unit> |
      | Total Experience | <Candidate_Total_Experience> |
      | Total Experience Unit | <Candidate_Total_Experience_Unit> |
      | Notice Period | <Candidate_Notice_Period> |
      | Notice Period Unit | <Candidate_Notice_Period_Unit> |
      | Work Experience | <Candidate_Work_Experience> |
      | Education | <Candidate_Education> |
      | Cover Letter | <Candidate_Cover_Letter> |
      | Owner | <Candidate_Owner> |
      | Recruiter | <Candidate_Recruiter> |
      | Index | <Candidate_Index> |

    Examples:
      | Candidate_Email | Candidate_Phone_Code | Candidate_Phone_Number | Candidate_First_Name | Candidate_Last_Name | Candidate_Professional_Profile_Link | Candidate_Source | Candidate_Country | Candidate_State | Candidate_Current_Salary_Currency | Candidate_Current_Salary | Candidate_Current_Salary_Duration | Candidate_Expected_Salary_Currency | Candidate_Expected_Salary | Candidate_Expected_Salary_Duration | Candidate_CV_Resume | Candidate_Skills | Candidate_Relevant_Experience | Candidate_Relevant_Experience_Unit | Candidate_Total_Experience | Candidate_Total_Experience_Unit | Candidate_Notice_Period | Candidate_Notice_Period_Unit | Candidate_Work_Experience | Candidate_Education | Candidate_Cover_Letter | Candidate_Owner | Candidate_Recruiter | Candidate_Index |
      | yaromir.kiselov2026cz@yopmail.com | +91 | 9123405014 | Yaromir | Kiselov | https://www.linkedin.com/in/yaromir-kiselov-2026-cz | Import | India | West Bengal | INR(₹) | 1668000 | Yearly | INR(₹) | 2039000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 25 | Day(s) |  |  |  | Interviewer Ivan Orlov | Interviewer Ivan Orlov | 3 |
      | ritobrata.chanda2026da@yopmail.com | +91 | 9123405015 | Ritobrata | Chanda | https://www.linkedin.com/in/ritobrata-chanda-2026-da | Indeed | India | Tamil Nadu | INR(₹) | 1335000 | Yearly | INR(₹) | 1692000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 28 | Day(s) |  |  |  | Nikolai Sidorov | Nikolai Sidorov | 4 |
      | bogdan.vedenev2026db@yopmail.com | +91 | 9123405016 | Bogdan | Vedenev | https://www.linkedin.com/in/bogdan-vedenev-2026-db | LinkedIn | India | Telangana | INR(₹) | 1811000 | Yearly | INR(₹) | 2208000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 31 | Day(s) |  |  |  | Owner Mikhail Volkov | Owner Mikhail Volkov | 5 |
      | udayon.sur2026dc@yopmail.com | +91 | 9123405017 | Udayon | Sur | https://www.linkedin.com/in/udayon-sur-2026-dc | Naukri | India | Gujarat | INR(₹) | 878000 | Yearly | INR(₹) | 1146000 | Yearly |  |  | 2 | Year(s) | 3 | Year(s) | 34 | Day(s) |  |  |  | Rahul Chatterjee | Rahul Chatterjee | 6 |
      | matvey.krutov2026dd@yopmail.com | +91 | 9123405018 | Matvey | Krutov | https://www.linkedin.com/in/matvey-krutov-2026-dd | Candidate Portal | India | Uttar Pradesh | INR(₹) | 1582000 | Yearly | INR(₹) | 1956000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 37 | Day(s) |  |  |  | Admin Ayan Sengupta | Alexei Morozov | 7 |
      | aadvik.ghosal2026de@yopmail.com | +91 | 9123405019 | Aadvik | Ghosal | https://www.linkedin.com/in/aadvik-ghosal-2026-de | Consultancy | India | Rajasthan | INR(₹) | 1006000 | Yearly | INR(₹) | 1309000 | Yearly |  |  | 3 | Year(s) | 4 | Year(s) | 40 | Day(s) |  |  |  | Alexei Morozov | Guest Alexei Sokolov | 8 |
      | miroslav.yudin2026df@yopmail.com | +91 | 9123405020 | Miroslav | Yudin | https://www.linkedin.com/in/miroslav-yudin-2026-df | Email | India | Madhya Pradesh | INR(₹) | 1539000 | Yearly | INR(₹) | 1974000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 43 | Day(s) |  |  |  | Guest Alexei Sokolov | Interviewer Ivan Orlov | 9 |
      | arhan.biswas2026dg@yopmail.com | +91 | 9123405021 | Arhan | Biswas | https://www.linkedin.com/in/arhan-biswas-2026-dg | Import | India | Haryana | INR(₹) | 1262000 | Yearly | INR(₹) | 1621000 | Yearly |  |  | 5 | Year(s) | 6 | Year(s) | 46 | Day(s) |  |  |  | Interviewer Ivan Orlov | Nikolai Sidorov | 10 |
      | taras.lukashin2026dh@yopmail.com | +91 | 9123405022 | Taras | Lukashin | https://www.linkedin.com/in/taras-lukashin-2026-dh | Indeed | India | Punjab | INR(₹) | 1709000 | Yearly | INR(₹) | 2093000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 49 | Day(s) |  |  |  | Nikolai Sidorov | Owner Mikhail Volkov | 11 |
      | divit.sengupta2026di@yopmail.com | +91 | 9123405023 | Divit | Sengupta | https://www.linkedin.com/in/divit-sengupta-2026-di | LinkedIn | India | Odisha | INR(₹) | 1857000 | Yearly | INR(₹) | 2304000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 52 | Day(s) |  |  |  | Owner Mikhail Volkov | Rahul Chatterjee | 12 |
      | gavriil.turin2026dj@yopmail.com | +91 | 9123405024 | Gavriil | Turin | https://www.linkedin.com/in/gavriil-turin-2026-dj | Naukri | India | Bihar | INR(₹) | 1752000 | Yearly | INR(₹) | 2141000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 55 | Day(s) |  |  |  | Rahul Chatterjee | Admin Ayan Sengupta | 13 |
      | vihaan.porel2026dk@yopmail.com | +91 | 9123405025 | Vihaan | Porel | https://www.linkedin.com/in/vihaan-porel-2026-dk | Candidate Portal | India | Kerala | INR(₹) | 1204000 | Yearly | INR(₹) | 1538000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 58 | Day(s) |  |  |  | Admin Ayan Sengupta | Guest Alexei Sokolov | 14 |
      | yaroslavin.fokin2026dl@yopmail.com | +91 | 9123405026 | Yaroslavin | Fokin | https://www.linkedin.com/in/yaroslavin-fokin-2026-dl | Consultancy | India | Andhra Pradesh | INR(₹) | 1614000 | Yearly | INR(₹) | 1989000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 61 | Day(s) |  |  |  | Alexei Morozov | Interviewer Ivan Orlov | 15 |
      | ridoy.roy2026dm@yopmail.com | +91 | 9123405027 | Ridoy | Roy | https://www.linkedin.com/in/ridoy-roy-2026-dm | Email | India | Jharkhand | INR(₹) | 1501000 | Yearly | INR(₹) | 1916000 | Yearly |  |  | 6 | Year(s) | 7 | Year(s) | 64 | Day(s) |  |  |  | Guest Alexei Sokolov | Nikolai Sidorov | 16 |
      | svyatopolk.garin2026dn@yopmail.com | +91 | 9123405028 | Svyatopolk | Garin | https://www.linkedin.com/in/svyatopolk-garin-2026-dn | Import | India | Assam | INR(₹) | 1691000 | Yearly | INR(₹) | 2088000 | Yearly |  |  | 7 | Year(s) | 8 | Year(s) | 67 | Day(s) |  |  |  | Interviewer Ivan Orlov | Owner Mikhail Volkov | 17 |
      | ranadip.kundu2026do@yopmail.com | +91 | 9123405029 | Ranadip | Kundu | https://www.linkedin.com/in/ranadip-kundu-2026-do | Indeed | India | Chhattisgarh | INR(₹) | 1048000 | Yearly | INR(₹) | 1387000 | Yearly |  |  | 4 | Year(s) | 5 | Year(s) | 70 | Day(s) |  |  |  | Nikolai Sidorov | Rahul Chatterjee | 18 |
      | rodion.starov2026dp@yopmail.com | +91 | 9123405030 | Rodion | Starov | https://www.linkedin.com/in/rodion-starov-2026-dp | LinkedIn | India | Goa | INR(₹) | 1961000 | Yearly | INR(₹) | 2408000 | Yearly |  |  | 8 | Year(s) | 9 | Year(s) | 76 | Day(s) |  |  |  | Owner Mikhail Volkov | Admin Ayan Sengupta | 19 |

  @CandidateCVUpload
  Scenario Outline: Upload Candidate CV file type <CV_File_Type>
    Given upload Candidate CV using the following feature data
      | File Type | <CV_File_Type> |
      | File Path | <CV_File_Path> |

    Examples:
      | CV_File_Type | CV_File_Path |
      | Valid PDF | ${user.dir}\\Dummy Cvs\\candidate_resume_valid.pdf |

  @CandidateCount
  Scenario: Fetch total Candidate count
    Given fetch total Candidate count from Candidate module
