@Job
Feature: Jobs module feature-driven workflows

  @JobAdd
  Scenario Outline: Add Job posting <Job_Job_Posting_Name>
    Given add Job using the following feature data
      | Select Template | <Job_Select_Template> |
      | Job Posting Name | <Job_Job_Posting_Name> |
      | Expiry Date | <Job_Expiry_Date> |
      | Job Urgency | <Job_Job_Urgency> |
      | Job Title | <Job_Job_Title> |
      | Department / Division | <Job_Department_Division> |
      | Employment Type | <Job_Employment_Type> |
      | Category | <Job_Category> |
      | Required Education | <Job_Required_Education> |
      | Required Experience | <Job_Required_Experience> |
      | Expected Hiring Date | <Job_Expected_Hiring_Date> |
      | Number of Positions | <Job_Number_of_Positions> |
      | When Positions Fulfilled | <Job_When_Positions_Fulfilled> |
      | Job Description | <Job_Job_Description> |
      | Job Requirements | <Job_Job_Requirements> |
      | Benefits | <Job_Benefits> |
      | Country | <Job_Country> |
      | City / State | <Job_City_State> |
      | Remote | <Job_Remote> |
      | Salary From 1 | <Job_Salary_From_1> |
      | Salary To 1 | <Job_Salary_To_1> |
      | Unit 1 | <Job_Unit_1> |
      | Currency 1 | <Job_Currency_1> |
      | Salary From 2 | <Job_Salary_From_2> |
      | Salary To 2 | <Job_Salary_To_2> |
      | Unit 2 | <Job_Unit_2> |
      | Currency 2 | <Job_Currency_2> |
      | Salary From 3 | <Job_Salary_From_3> |
      | Salary To 3 | <Job_Salary_To_3> |
      | Unit 3 | <Job_Unit_3> |
      | Currency 3 | <Job_Currency_3> |
      | Screening Question 1 | <Job_Screening_Question_1> |
      | Screening Question 2 | <Job_Screening_Question_2> |
      | Screening Question 3 | <Job_Screening_Question_3> |
      | Save As Job Posting Template | <Job_Save_As_Job_Posting_Template> |
      | JobRequirements | <Job_JobRequirements> |

    Examples:
      | Job_Select_Template | Job_Job_Posting_Name | Job_Expiry_Date | Job_Job_Urgency | Job_Job_Title | Job_Department_Division | Job_Employment_Type | Job_Category | Job_Required_Education | Job_Required_Experience | Job_Expected_Hiring_Date | Job_Number_of_Positions | Job_When_Positions_Fulfilled | Job_Job_Description | Job_Job_Requirements | Job_Benefits | Job_Country | Job_City_State | Job_Remote | Job_Salary_From_1 | Job_Salary_To_1 | Job_Unit_1 | Job_Currency_1 | Job_Salary_From_2 | Job_Salary_To_2 | Job_Unit_2 | Job_Currency_2 | Job_Salary_From_3 | Job_Salary_To_3 | Job_Unit_3 | Job_Currency_3 | Job_Screening_Question_1 | Job_Screening_Question_2 | Job_Screening_Question_3 | Job_Save_As_Job_Posting_Template | Job_JobRequirements |
      | Custom Template | Autonomous Swarm Orchestration Drive 01 | 11-07-2026 | High | Autonomous Swarm Orchestration Engineer | Artificial Intelligence and Autonomy | Full Time | Information Technology | M.Tech | Senior | 21-08-2026 | 1 | Enable Waitlist | Develop autonomous strike logic, mission behavior, and smart decision systems for UAV platforms. | Experience in autonomy logic, AI systems, mission workflows, and intelligent control. | Insurance, defense R&D exposure, innovation work, and long term technical growth. | India | Karnataka | Yes | 1900000 | 2500000 | Per Annum | INR(₹) | 2500001 | 3300000 | Per Annum | INR(₹) | 3300001 | 4100000 | Per Annum | INR(₹) | Do you have autonomy or intelligent control experience in UAV or robotics systems? | Have you worked on mission logic, automated response, or autonomous behaviors? | Which AI or autonomy frameworks have you used? | No |  |
      | Custom Template | Avionics Power Distribution Drive 02 | 13-07-2026 | High | Avionics Power Distribution Engineer | Avionics | Full Time | Information Technology | B.Tech | Mid-senior | 25-08-2026 | 2 | Close Job | Support power electronics, onboard wiring, and avionics subsystem health for UAV platforms. | Experience in avionics electronics, power distribution, and onboard system troubleshooting. | Insurance, hardware exposure, mission systems role, and technical learning. | India | Telangana | No | 950000 | 1350000 | Per Annum | INR(₹) | 1350001 | 1750000 | Per Annum | INR(₹) | 1750001 | 2150000 | Per Annum | INR(₹) | Do you have avionics or onboard power electronics experience? | Have you handled UAV electronics integration or troubleshooting? | Which avionics or power modules have you worked on? | No |  |
      | Custom Template | Flight Envelope Control Drive 03 | 15-07-2026 | High | Flight Envelope Control Engineer | Flight Control Systems | Full Time | Information Technology | B.Tech | Senior | 29-08-2026 | 1 | Enable Waitlist | Improve flight stability, response tuning, and control law performance for drone platforms. | Experience in flight control, stability tuning, control systems, and response validation. | Insurance, mission critical role, systems depth, and strong growth path. | India | Maharashtra | No | 1650000 | 2250000 | Per Annum | INR(₹) | 2250001 | 2850000 | Per Annum | INR(₹) | 2850001 | 3450000 | Per Annum | INR(₹) | Do you have flight control or stability tuning experience? | Have you worked on controller tuning or response optimization? | Which tools have you used for control analysis? | No |  |
      | Custom Template | Tactical Perception Fusion Drive 04 | 17-07-2026 | High | Tactical Perception Fusion Engineer | Computer Vision | Full Time | Information Technology | M.Tech | Mid-senior | 02-09-2026 | 2 | Enable Waitlist | Develop image intelligence, target recognition, and tracking systems for ISR drones. | Experience in computer vision, image analytics, detection pipelines, and deployment. | Insurance, AI mission work, research exposure, and strong technical growth. | India | Haryana | Yes | 1450000 | 1950000 | Per Annum | INR(₹) | 1950001 | 2550000 | Per Annum | INR(₹) | 2550001 | 3150000 | Per Annum | INR(₹) | Do you have vision analytics or target detection experience? | Have you built image tracking or scene intelligence pipelines? | Which vision tools or frameworks have you used? | No |  |
      | Custom Template | Real-Time Flight Stack Drive 05 | 19-07-2026 | High | Real-Time Flight Stack Engineer | Embedded Systems | Full Time | Information Technology | B.Tech | Mid-senior | 05-09-2026 | 2 | Close Job | Develop flight firmware, hardware interfaces, and low level real time UAV functions. | Experience in embedded C, RTOS, microcontrollers, and debugging. | Insurance, firmware ownership, core systems exposure, and career growth. | India | West Bengal | No | 950000 | 1350000 | Per Annum | INR(₹) | 1350001 | 1800000 | Per Annum | INR(₹) | 1800001 | 2250000 | Per Annum | INR(₹) | Do you have embedded firmware or flight stack experience? | Have you worked with RTOS or real time systems? | Which MCU or debugging tools have you used? | No |  |
      | Custom Template | Secure Airborne Data Links Drive 06 | 21-07-2026 | High | Secure Airborne Data Links Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 07-09-2026 | 1 | Enable Waitlist | Design secure telemetry channels, communication validation, and UAV link reliability. | Experience in RF systems, telemetry links, antennas, and communication testing. | Insurance, communications specialization, hardware exposure, and growth. | India | Tamil Nadu | No | 1450000 | 1950000 | Per Annum | INR(₹) | 1950001 | 2550000 | Per Annum | INR(₹) | 2550001 | 3150000 | Per Annum | INR(₹) | Do you have telemetry or RF communication experience? | Have you worked on secure or reliable UAV links? | Which RF validation tools have you used? | No |  |
      | Custom Template | Inertial Navigation Fusion Drive 07 | 23-07-2026 | High | Inertial Navigation Fusion Engineer | UAV Engineering | Full Time | Information Technology | M.Tech | Senior | 09-09-2026 | 1 | Close Job | Develop guidance algorithms, navigation fusion, and route precision for UAV missions. | Experience in navigation logic, GPS INS fusion, and guidance algorithms. | Insurance, mission systems role, technical depth, and strong growth. | India | Uttar Pradesh | No | 1750000 | 2350000 | Per Annum | INR(₹) | 2350001 | 2950000 | Per Annum | INR(₹) | 2950001 | 3550000 | Per Annum | INR(₹) | Do you have guidance or navigation algorithm experience? | Have you worked on route control or navigation fusion? | Which algorithms or tools have you used? | No |  |
      | Custom Template | EO-IR Mission Payload Drive 08 | 25-07-2026 | High | EO-IR Mission Payload Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Mid-senior | 12-09-2026 | 2 | Enable Waitlist | Integrate targeting payloads, EO IR sensors, and mission camera packages. | Experience in payload mounting, sensor integration, and validation workflows. | Insurance, tactical systems role, field relevance, and growth. | India | Gujarat | No | 1050000 | 1500000 | Per Annum | INR(₹) | 1500001 | 1950000 | Per Annum | INR(₹) | 1950001 | 2450000 | Per Annum | INR(₹) | Do you have payload or EO IR integration experience? | Have you worked on targeting or mission sensor packages? | What payload types have you integrated? | No |  |
      | Custom Template | Ground Command Interface Drive 09 | 27-07-2026 | High | Ground Command Interface Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Mid-senior | 14-09-2026 | 2 | Close Job | Build operator dashboards, telemetry consoles, and mission control workflows. | Experience in control console software, telemetry UI, and mission systems. | Insurance, defense software role, systems exposure, and growth. | India | Odisha | Yes | 1050000 | 1550000 | Per Annum | INR(₹) | 1550001 | 2150000 | Per Annum | INR(₹) | 2150001 | 2750000 | Per Annum | INR(₹) | Do you have operator console or telemetry software experience? | Have you built monitoring or mission interfaces? | Which software stack have you used? | No |  |
      | Custom Template | Combat Mission Planning Drive 10 | 29-07-2026 | High | Combat Mission Planning Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 16-09-2026 | 1 | Enable Waitlist | Build tactical route planning, mission tasking, and waypoint management software. | Experience in planning systems, mapping logic, and mission software workflows. | Insurance, strategic mission role, systems exposure, and growth. | India | Kerala | Yes | 1450000 | 1950000 | Per Annum | INR(₹) | 1950001 | 2550000 | Per Annum | INR(₹) | 2550001 | 3150000 | Per Annum | INR(₹) | Do you have mission software or mapping experience? | Have you worked on route logic or waypoint planning? | Which backend or mission stack have you used? | No |  |
      | Custom Template | Synthetic Battlespace Modeling Drive 11 | 31-07-2026 | Medium | Synthetic Battlespace Modeling Engineer | Research and Development | Full Time | Information Technology | M.Tech | Mid-senior | 18-09-2026 | 1 | Close Job | Create digital twin simulations, mission scenarios, and virtual test environments. | Experience in simulation, modeling, and scenario based validation. | Insurance, technical depth, research exposure, and long term learning. | India | Rajasthan | Yes | 1050000 | 1500000 | Per Annum | INR(₹) | 1500001 | 2000000 | Per Annum | INR(₹) | 2000001 | 2500000 | Per Annum | INR(₹) | Do you have simulation or digital twin experience? | Have you built UAV or robotics test scenarios? | Which simulation tools have you used? | No | Experience in simulation, modeling, and scenario based validation. |
      | Custom Template | UAV Test Range Assurance Drive 12 | 02-08-2026 | High | UAV Test Range Assurance Engineer | Testing and Validation | Full Time | Quality Analysis | B.Tech | Mid-senior | 20-09-2026 | 2 | Close Job | Run trials, validate subsystems, log defects, and verify field readiness. | Experience in validation planning, test execution, and result analysis. | Insurance, range testing exposure, systems work, and growth. | India | Madhya Pradesh | No | 950000 | 1350000 | Per Annum | INR(₹) | 1350001 | 1750000 | Per Annum | INR(₹) | 1750001 | 2150000 | Per Annum | INR(₹) | Do you have validation or range testing experience? | Have you worked on integration or field validation? | How do you document failures and deviations? | No |  |
      | Custom Template | Defense Software Reliability Drive 13 | 04-08-2026 | Medium | Defense Software Reliability Engineer | Quality Assurance | Full Time | Quality Analysis | B.Tech | Junior | 22-09-2026 | 2 | Enable Waitlist | Validate mission workflows, regression coverage, and UAV software quality. | Experience in functional testing, regression, and detailed defect reporting. | Insurance, QA exposure, product learning, and career growth. | India | Bihar | Yes | 650000 | 900000 | Per Annum | INR(₹) | 900001 | 1150000 | Per Annum | INR(₹) | 1150001 | 1400000 | Per Annum | INR(₹) | Do you have functional and regression testing experience? | Have you validated complete business or mission workflows? | Which QA tools have you used? | No |  |
      | Custom Template | Drone Assembly Process Excellence Drive 14 | 06-08-2026 | High | Drone Assembly Process Excellence Engineer | Manufacturing | Full Time | Professional Service | B.Tech | Mid-senior | 24-09-2026 | 2 | Close Job | Support assembly flow, tooling, production quality, and build performance. | Experience in manufacturing operations, process improvement, and assembly workflows. | Insurance, production exposure, assembly ownership, and role growth. | India | Maharashtra | No | 850000 | 1200000 | Per Annum | INR(₹) | 1200001 | 1550000 | Per Annum | INR(₹) | 1550001 | 1950000 | Per Annum | INR(₹) | Do you have assembly line or drone manufacturing experience? | Have you improved build quality or production efficiency? | What hardware manufacturing environment have you worked in? | No |  |
      | Custom Template | Composite Airframe Architecture Drive 15 | 08-08-2026 | High | Composite Airframe Architecture Engineer | Mechanical Design | Full Time | Information Technology | B.Tech | Mid-senior | 26-09-2026 | 2 | Enable Waitlist | Design UAV structures, housings, and lightweight mission ready assemblies. | Experience in CAD, structural design, and lightweight mechanical systems. | Insurance, prototype exposure, design ownership, and growth. | India | Jharkhand | No | 950000 | 1350000 | Per Annum | INR(₹) | 1350001 | 1800000 | Per Annum | INR(₹) | 1800001 | 2250000 | Per Annum | INR(₹) | Do you have mechanical or structural UAV design experience? | Have you worked on lightweight or airframe assemblies? | Which CAD tools have you used most? | No |  |
      | Custom Template | High-Endurance Powertrain Drive 16 | 10-08-2026 | High | High-Endurance Powertrain Engineer | UAV Engineering | Full Time | Information Technology | B.Tech | Senior | 28-09-2026 | 1 | Close Job | Improve propulsion efficiency, endurance, motor control, and powertrain reliability. | Experience in propulsion systems, ESCs, motors, endurance analysis, and testing. | Insurance, deep hardware role, performance optimization, and growth. | India | Uttar Pradesh | No | 1350000 | 1850000 | Per Annum | INR(₹) | 1850001 | 2450000 | Per Annum | INR(₹) | 2450001 | 3050000 | Per Annum | INR(₹) | Do you have propulsion or endurance engineering experience? | Have you worked on motors, ESCs, or performance tuning? | What propulsion systems have you optimized? | No |  |
      | Custom Template | UAV Capability Portfolio Drive 17 | 12-08-2026 | Medium | UAV Capability Portfolio Manager | Product Management | Full Time | Information Technology | MBA | Senior | 30-09-2026 | 1 | Enable Waitlist | Own product planning, roadmap priorities, and platform strategy for defense UAVs. | Experience in product planning, stakeholder management, and platform prioritization. | Insurance, strategic ownership, defense product exposure, and leadership growth. | India | Gujarat | Yes | 1550000 | 2150000 | Per Annum | INR(₹) | 2150001 | 2750000 | Per Annum | INR(₹) | 2750001 | 3350000 | Per Annum | INR(₹) | Do you have product strategy or platform planning experience? | Have you worked with engineering and defense stakeholders? | How do you balance mission need and technical feasibility? | No |  |
      | Custom Template | Defense Program Growth Strategy Drive 18 | 14-08-2026 | Medium | Defense Program Growth Strategy Manager | Sales and Business Development | Full Time | Marketing | MBA | Senior | 02-10-2026 | 1 | Close Job | Drive defense engagement, growth programs, and strategic UAV solution expansion. | Experience in B2B sales, defense accounts, proposal work, and solution pitching. | Insurance, strategic role, client exposure, and long term growth. | India | Tamil Nadu | No | 1250000 | 1750000 | Per Annum | INR(₹) | 1750001 | 2250000 | Per Annum | INR(₹) | 2250001 | 2850000 | Per Annum | INR(₹) | Do you have B2B or defense growth experience? | Have you worked on proposals or strategic client discussions? | How do you qualify high value defense leads? | No |  |
      | Custom Template | Deployed Flight Operations Drive 19 | 16-08-2026 | High | Deployed Flight Operations Engineer | Field Deployment | Full Time | Professional Service | B.Tech | Mid-senior | 04-10-2026 | 2 | Enable Waitlist | Support live field trials, deployment checks, and mission issue troubleshooting. | Experience in field testing, operational support, and trial reporting. | Insurance, mission field exposure, operations learning, and growth. | India | Kerala | No | 900000 | 1250000 | Per Annum | INR(₹) | 1250001 | 1650000 | Per Annum | INR(₹) | 1650001 | 2050000 | Per Annum | INR(₹) | Do you have field deployment or trial support experience? | Are you comfortable with site work and travel? | Have you handled mission issues during testing? | No |  |
      | Custom Template | Experimental Air Systems Drive 20 | 18-08-2026 | Medium | Experimental Air Systems Engineer | Research and Development | Full Time | Information Technology | M.Tech | Senior | 06-10-2026 | 1 | Close Job | Drive advanced UAV concepts, prototypes, and next generation system research. | Experience in research engineering, experimentation, and prototype evaluation. | Insurance, deep R&D exposure, innovation ownership, and leadership growth. | India | Andhra Pradesh | Yes | 1450000 | 1950000 | Per Annum | INR(₹) | 1950001 | 2550000 | Per Annum | INR(₹) | 2550001 | 3150000 | Per Annum | INR(₹) | Do you have R&D or prototype engineering experience? | Have you worked on concept evaluation or experimentation? | How do you document research findings and next steps? | No |  |

  @ActiveJobCount
  Scenario: Fetch total Active Jobs count
    Given fetch total Active Jobs count from Jobs module
