@SaasAdmin
Feature: SaaS Admin feature-driven account and lead workflows

  @SaasAdminLogin
  Scenario: Login to SaaS Admin
    Given login to SaaS Admin portal

  @DraftAccount
  Scenario Outline: Create draft account for <Account_Company_Name>
    Given create SaaS Admin draft account using the following feature data
      | First Name | <Account_First_Name> |
      | Middle Name | <Account_Middle_Name> |
      | Last Name | <Account_Last_Name> |
      | Company Name | <Account_Company_Name> |
      | Country | <Account_Country> |
      | Email | <Account_Email> |
      | Subscribe News | <Account_Subscribe_News> |
      | Country Code | <Account_Country_Code> |
      | Phone Number | <Account_Phone_Number> |
      | App Type | <Account_App_Type> |
      | App Name | <Account_App_Name> |
      | App Enabled | <Account_App_Enabled> |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name | <Account_Spaces_Plan_Name> |
      | Hire Plan Name | <Account_Hire_Plan_Name> |
      | Hr Plan Name | <Account_Hr_Plan_Name> |
      | Users | <Account_Users> |
      | Group | <Account_Group> |
      | Account Manager | <Account_Account_Manager> |
      | Staff Notes | <Account_Staff_Notes> |
      | Plan Name | <Account_Plan_Name> |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lorenz | Matthias | Baumgartner | Baumgartner Unified Systems GmbH | Germany | lorenz.matthias.baumgartner.account166@yopmail.com | Yes | +49 | 15728493610 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 47 | Gold II | Ayan Test Manager | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |  |
      | Elise | Marion | Chastain | Chastain Checkout Advisory SAS | France | elise.marion.chastain.account167@yopmail.com | No | +33 | 756293841 | checkout | Simplified Checkout | Yes |  |  |  |  | 21 | Daimond | Ayan Test Manager | Testing France-based checkout account creation with monthly checkout business plan selection, users value, newsletter disabled state, valid group selection, and new customer contact details. | Ayan Monthly Checkout Business Plan |
      | Henrik | Olav | Strandheim | Strandheim Integrated Operations AS | Norway | henrik.olav.strandheim.account168@yopmail.com | Yes | +47 | 47936182 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 58 | Silver | Ayan Test Manager | Validating Norway-based all app account creation with weekly checkout, monthly spaces, monthly hire, and yearly HR plan selections, including users field value, valid group selection, and account manager mapping. |  |
      | Serena | Carlotta | Vitale | Vitale Workspace Services SRL | Italy | serena.carlotta.vitale.account169@yopmail.com | No | +39 | 3517946820 | spaces | Simplified Spaces | Yes |  |  |  |  | 30 | Gold | Ayan Test Manager | Creating this Italy-based spaces account to verify monthly spaces business plan assignment, users value, newsletter disabled state, valid group selection, and staff note capture. | Ayan Monthly Spaces Business Plan |
      | Edmund | Laurence | Whitmore | Whitmore Multi Product Services Ltd | United Kingdom | edmund.laurence.whitmore.account170@yopmail.com | Yes | +44 | 7526849130 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 64 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and monthly HR plans together, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Annelies | Margriet | Timmermans | Timmermans Employee Systems BV | Netherlands | annelies.margriet.timmermans.account171@yopmail.com | No | +31 | 682941573 | hr | Simplified HR | Yes |  |  |  |  | 39 | Daimond | Ayan Test Manager | Creating this Netherlands-based HR account to verify monthly HR business plan assignment, users field value, newsletter disabled state, valid group selection, and account manager mapping. | Ayan Monthly HR Business Plan |
      | Gregor | Valentin | Hinterberger | Hinterberger Complete SaaS GmbH | Austria | gregor.valentin.hinterberger.account172@yopmail.com | Yes | +43 | 6765812943 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Space Weekly Plan 99 | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 50 | Silver | Ayan Test Manager | Testing Austria-based all app account creation with weekly checkout, weekly spaces, monthly hire, and weekly HR plans, including users value, newsletter selection, group assignment, and account manager mapping. |  |
      | Dorota | Izabela | Wasilewska | Wasilewska Recruitment Systems Sp z oo | Poland | dorota.izabela.wasilewska.account173@yopmail.com | No | +48 | 516928473 | hire | Simplified Hire | Yes |  |  |  |  | 32 | Gold | Ayan Test Manager | This Poland-based hire account is used to validate monthly hire business plan assignment, users value, newsletter disabled condition, valid group selection, and customer profile details. | Ayan Monthly Hire Business Plan |
      | Mateo | Alejandro | Carrasco | Carrasco Multi App Operations SL | Spain | mateo.alejandro.carrasco.account174@yopmail.com | Yes | +34 | 632784915 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 67 | Gold II | Ayan Test Manager | Verifying Spain-based all app account creation with monthly checkout, yearly spaces, yearly hire, and monthly HR plans, users value, newsletter subscription, valid group, and staff note coverage. |  |
      | Elian | Marco | Rothen | Rothen Checkout Solutions AG | Switzerland | elian.marco.rothen.account175@yopmail.com | No | +41 | 762581493 | checkout | Simplified Checkout | Yes |  |  |  |  | 34 | Daimond | Ayan Test Manager | Creating this Switzerland-based checkout account to verify monthly checkout business plan assignment, users value, newsletter disabled condition, valid group, and staff note save flow. | Ayan Monthly Checkout Business Plan |
      | Linus | Viktor | Dahlstrom | Dahlstrom Unified People Services AB | Sweden | linus.viktor.dahlstrom.account176@yopmail.com | Yes | +46 | 706381492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 56 | Silver | Ayan Test Manager | Testing Sweden-based all app account creation with weekly checkout, weekly spaces, monthly hire, and monthly HR plans, users count, newsletter subscription enabled, and group selection. |  |
      | Romain | Sylvain | Gauthier | Gauthier Workspace Advisory SAS | France | romain.sylvain.gauthier.account177@yopmail.com | No | +33 | 752681943 | spaces | Simplified Spaces | Yes |  |  |  |  | 29 | Gold | Ayan Test Manager | Creating this France-based spaces account to validate monthly spaces business plan selection, users value, newsletter unchecked condition, valid group selection, and internal staff note coverage. | Ayan Monthly Spaces Business Plan |
      | Livia | Mariella | Contarini | Contarini Enterprise SaaS SRL | Italy | livia.mariella.contarini.account178@yopmail.com | Yes | +39 | 3492815763 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan HR New Weekly Plan | 61 | Gold II | Ayan Test Manager | Validating Italy-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans, users value, newsletter subscription, valid group selection, and account manager assignment. |  |
      | Sjoerd | Maarten | Velthuizen | Velthuizen Employee Operations BV | Netherlands | sjoerd.maarten.velthuizen.account179@yopmail.com | No | +31 | 685217493 | hr | Simplified HR | Yes |  |  |  |  | 44 | Daimond | Ayan Test Manager | Testing Netherlands-based HR account creation with weekly HR growth plan assignment, users field value, newsletter disabled state, valid group selection, and staff note entry. | Ayan Weekly HR Growth Plan |
      | Vlad | Teodor | Georgescu | Georgescu Unified Business Operations SRL | Romania | vlad.teodor.georgescu.account180@yopmail.com | Yes | +40 | 735681492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 73 | Silver | Ayan Test Manager | Creating Romania-based all app account to verify monthly checkout, monthly spaces, monthly hire, and monthly HR plan assignment, users field entry, newsletter subscription, and valid group selection. |  |
      | Justyna | Helena | Baranowska | Baranowska Talent Advisory Sp z oo | Poland | justyna.helena.baranowska.account181@yopmail.com | No | +48 | 519628437 | hire | Simplified Hire | Yes |  |  |  |  | 35 | Gold | Ayan Test Manager | Creating this Poland-based hire account to verify monthly hire business plan selection, users value, newsletter disabled condition, valid group assignment, and internal account manager mapping. | Ayan Monthly Hire Business Plan |
      | Nathaniel | Arthur | Wycliffe | Wycliffe Multi Product Services Ltd | United Kingdom | nathaniel.arthur.wycliffe.account182@yopmail.com | Yes | +44 | 7463819250 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 59 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans together, users value, newsletter subscription, and valid group selection. |  |
      | Sindre | Aksel | Vikstrom | Vikstrom Unified Operations AS | Norway | sindre.aksel.vikstrom.account183@yopmail.com | No | +47 | 47829136 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 63 | Daimond | Ayan Test Manager | Creating Norway-based all app account with monthly checkout, yearly spaces, yearly hire, and monthly HR plan selection, users value, newsletter disabled state, and group mapping. |  |
      | Claudia | Theresia | Waldstein | Waldstein Complete SaaS GmbH | Germany | claudia.theresia.waldstein.account184@yopmail.com | Yes | +49 | 15286497310 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 68 | Silver | Ayan Test Manager | Validating Germany-based all app account with yearly checkout, monthly spaces, monthly hire, and yearly HR plans, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Anais | Florence | Lemaire | Lemaire Enterprise Coordination SAS | France | anais.florence.lemaire.account185@yopmail.com | No | +33 | 763581492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 55 | Gold | Ayan Test Manager | Creating France-based all app account to verify weekly checkout, monthly spaces, monthly hire, and monthly HR plans together, users field value, newsletter disabled state, and valid group selection. |  |

  @CreateAccount
  Scenario Outline: Create and invite account for <Account_Company_Name>
    Given create SaaS Admin account using the following feature data
      | First Name | <Account_First_Name> |
      | Middle Name | <Account_Middle_Name> |
      | Last Name | <Account_Last_Name> |
      | Company Name | <Account_Company_Name> |
      | Country | <Account_Country> |
      | Email | <Account_Email> |
      | Subscribe News | <Account_Subscribe_News> |
      | Country Code | <Account_Country_Code> |
      | Phone Number | <Account_Phone_Number> |
      | App Type | <Account_App_Type> |
      | App Name | <Account_App_Name> |
      | App Enabled | <Account_App_Enabled> |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name | <Account_Spaces_Plan_Name> |
      | Hire Plan Name | <Account_Hire_Plan_Name> |
      | Hr Plan Name | <Account_Hr_Plan_Name> |
      | Users | <Account_Users> |
      | Group | <Account_Group> |
      | Account Manager | <Account_Account_Manager> |
      | Staff Notes | <Account_Staff_Notes> |
      | Plan Name | <Account_Plan_Name> |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lorenz | Matthias | Baumgartner | Baumgartner Unified Systems GmbH | Germany | lorenz.matthias.baumgartner.account166@yopmail.com | Yes | +49 | 15728493610 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 47 | Gold II | Ayan Test Manager | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |  |
      | Elise | Marion | Chastain | Chastain Checkout Advisory SAS | France | elise.marion.chastain.account167@yopmail.com | No | +33 | 756293841 | checkout | Simplified Checkout | Yes |  |  |  |  | 21 | Daimond | Ayan Test Manager | Testing France-based checkout account creation with monthly checkout business plan selection, users value, newsletter disabled state, valid group selection, and new customer contact details. | Ayan Monthly Checkout Business Plan |
      | Henrik | Olav | Strandheim | Strandheim Integrated Operations AS | Norway | henrik.olav.strandheim.account168@yopmail.com | Yes | +47 | 47936182 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 58 | Silver | Ayan Test Manager | Validating Norway-based all app account creation with weekly checkout, monthly spaces, monthly hire, and yearly HR plan selections, including users field value, valid group selection, and account manager mapping. |  |
      | Serena | Carlotta | Vitale | Vitale Workspace Services SRL | Italy | serena.carlotta.vitale.account169@yopmail.com | No | +39 | 3517946820 | spaces | Simplified Spaces | Yes |  |  |  |  | 30 | Gold | Ayan Test Manager | Creating this Italy-based spaces account to verify monthly spaces business plan assignment, users value, newsletter disabled state, valid group selection, and staff note capture. | Ayan Monthly Spaces Business Plan |
      | Edmund | Laurence | Whitmore | Whitmore Multi Product Services Ltd | United Kingdom | edmund.laurence.whitmore.account170@yopmail.com | Yes | +44 | 7526849130 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 64 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and monthly HR plans together, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Annelies | Margriet | Timmermans | Timmermans Employee Systems BV | Netherlands | annelies.margriet.timmermans.account171@yopmail.com | No | +31 | 682941573 | hr | Simplified HR | Yes |  |  |  |  | 39 | Daimond | Ayan Test Manager | Creating this Netherlands-based HR account to verify monthly HR business plan assignment, users field value, newsletter disabled state, valid group selection, and account manager mapping. | Ayan Monthly HR Business Plan |
      | Gregor | Valentin | Hinterberger | Hinterberger Complete SaaS GmbH | Austria | gregor.valentin.hinterberger.account172@yopmail.com | Yes | +43 | 6765812943 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Space Weekly Plan 99 | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 50 | Silver | Ayan Test Manager | Testing Austria-based all app account creation with weekly checkout, weekly spaces, monthly hire, and weekly HR plans, including users value, newsletter selection, group assignment, and account manager mapping. |  |
      | Dorota | Izabela | Wasilewska | Wasilewska Recruitment Systems Sp z oo | Poland | dorota.izabela.wasilewska.account173@yopmail.com | No | +48 | 516928473 | hire | Simplified Hire | Yes |  |  |  |  | 32 | Gold | Ayan Test Manager | This Poland-based hire account is used to validate monthly hire business plan assignment, users value, newsletter disabled condition, valid group selection, and customer profile details. | Ayan Monthly Hire Business Plan |
      | Mateo | Alejandro | Carrasco | Carrasco Multi App Operations SL | Spain | mateo.alejandro.carrasco.account174@yopmail.com | Yes | +34 | 632784915 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 67 | Gold II | Ayan Test Manager | Verifying Spain-based all app account creation with monthly checkout, yearly spaces, yearly hire, and monthly HR plans, users value, newsletter subscription, valid group, and staff note coverage. |  |
      | Elian | Marco | Rothen | Rothen Checkout Solutions AG | Switzerland | elian.marco.rothen.account175@yopmail.com | No | +41 | 762581493 | checkout | Simplified Checkout | Yes |  |  |  |  | 34 | Daimond | Ayan Test Manager | Creating this Switzerland-based checkout account to verify monthly checkout business plan assignment, users value, newsletter disabled condition, valid group, and staff note save flow. | Ayan Monthly Checkout Business Plan |
      | Linus | Viktor | Dahlstrom | Dahlstrom Unified People Services AB | Sweden | linus.viktor.dahlstrom.account176@yopmail.com | Yes | +46 | 706381492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 56 | Silver | Ayan Test Manager | Testing Sweden-based all app account creation with weekly checkout, weekly spaces, monthly hire, and monthly HR plans, users count, newsletter subscription enabled, and group selection. |  |
      | Romain | Sylvain | Gauthier | Gauthier Workspace Advisory SAS | France | romain.sylvain.gauthier.account177@yopmail.com | No | +33 | 752681943 | spaces | Simplified Spaces | Yes |  |  |  |  | 29 | Gold | Ayan Test Manager | Creating this France-based spaces account to validate monthly spaces business plan selection, users value, newsletter unchecked condition, valid group selection, and internal staff note coverage. | Ayan Monthly Spaces Business Plan |
      | Livia | Mariella | Contarini | Contarini Enterprise SaaS SRL | Italy | livia.mariella.contarini.account178@yopmail.com | Yes | +39 | 3492815763 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan HR New Weekly Plan | 61 | Gold II | Ayan Test Manager | Validating Italy-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans, users value, newsletter subscription, valid group selection, and account manager assignment. |  |
      | Sjoerd | Maarten | Velthuizen | Velthuizen Employee Operations BV | Netherlands | sjoerd.maarten.velthuizen.account179@yopmail.com | No | +31 | 685217493 | hr | Simplified HR | Yes |  |  |  |  | 44 | Daimond | Ayan Test Manager | Testing Netherlands-based HR account creation with weekly HR growth plan assignment, users field value, newsletter disabled state, valid group selection, and staff note entry. | Ayan Weekly HR Growth Plan |
      | Vlad | Teodor | Georgescu | Georgescu Unified Business Operations SRL | Romania | vlad.teodor.georgescu.account180@yopmail.com | Yes | +40 | 735681492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 73 | Silver | Ayan Test Manager | Creating Romania-based all app account to verify monthly checkout, monthly spaces, monthly hire, and monthly HR plan assignment, users field entry, newsletter subscription, and valid group selection. |  |
      | Justyna | Helena | Baranowska | Baranowska Talent Advisory Sp z oo | Poland | justyna.helena.baranowska.account181@yopmail.com | No | +48 | 519628437 | hire | Simplified Hire | Yes |  |  |  |  | 35 | Gold | Ayan Test Manager | Creating this Poland-based hire account to verify monthly hire business plan selection, users value, newsletter disabled condition, valid group assignment, and internal account manager mapping. | Ayan Monthly Hire Business Plan |
      | Nathaniel | Arthur | Wycliffe | Wycliffe Multi Product Services Ltd | United Kingdom | nathaniel.arthur.wycliffe.account182@yopmail.com | Yes | +44 | 7463819250 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 59 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans together, users value, newsletter subscription, and valid group selection. |  |
      | Sindre | Aksel | Vikstrom | Vikstrom Unified Operations AS | Norway | sindre.aksel.vikstrom.account183@yopmail.com | No | +47 | 47829136 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 63 | Daimond | Ayan Test Manager | Creating Norway-based all app account with monthly checkout, yearly spaces, yearly hire, and monthly HR plan selection, users value, newsletter disabled state, and group mapping. |  |
      | Claudia | Theresia | Waldstein | Waldstein Complete SaaS GmbH | Germany | claudia.theresia.waldstein.account184@yopmail.com | Yes | +49 | 15286497310 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 68 | Silver | Ayan Test Manager | Validating Germany-based all app account with yearly checkout, monthly spaces, monthly hire, and yearly HR plans, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Anais | Florence | Lemaire | Lemaire Enterprise Coordination SAS | France | anais.florence.lemaire.account185@yopmail.com | No | +33 | 763581492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 55 | Gold | Ayan Test Manager | Creating France-based all app account to verify weekly checkout, monthly spaces, monthly hire, and monthly HR plans together, users field value, newsletter disabled state, and valid group selection. |  |

  @VerifyAccount
  Scenario Outline: Verify account for <Account_Company_Name>
    Given verify SaaS Admin account using the following feature data
      | First Name | <Account_First_Name> |
      | Middle Name | <Account_Middle_Name> |
      | Last Name | <Account_Last_Name> |
      | Company Name | <Account_Company_Name> |
      | Country | <Account_Country> |
      | Email | <Account_Email> |
      | Subscribe News | <Account_Subscribe_News> |
      | Country Code | <Account_Country_Code> |
      | Phone Number | <Account_Phone_Number> |
      | App Type | <Account_App_Type> |
      | App Name | <Account_App_Name> |
      | App Enabled | <Account_App_Enabled> |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name | <Account_Spaces_Plan_Name> |
      | Hire Plan Name | <Account_Hire_Plan_Name> |
      | Hr Plan Name | <Account_Hr_Plan_Name> |
      | Users | <Account_Users> |
      | Group | <Account_Group> |
      | Account Manager | <Account_Account_Manager> |
      | Staff Notes | <Account_Staff_Notes> |
      | Plan Name | <Account_Plan_Name> |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lorenz | Matthias | Baumgartner | Baumgartner Unified Systems GmbH | Germany | lorenz.matthias.baumgartner.account166@yopmail.com | Yes | +49 | 15728493610 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 47 | Gold II | Ayan Test Manager | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |  |
      | Elise | Marion | Chastain | Chastain Checkout Advisory SAS | France | elise.marion.chastain.account167@yopmail.com | No | +33 | 756293841 | checkout | Simplified Checkout | Yes |  |  |  |  | 21 | Daimond | Ayan Test Manager | Testing France-based checkout account creation with monthly checkout business plan selection, users value, newsletter disabled state, valid group selection, and new customer contact details. | Ayan Monthly Checkout Business Plan |
      | Henrik | Olav | Strandheim | Strandheim Integrated Operations AS | Norway | henrik.olav.strandheim.account168@yopmail.com | Yes | +47 | 47936182 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 58 | Silver | Ayan Test Manager | Validating Norway-based all app account creation with weekly checkout, monthly spaces, monthly hire, and yearly HR plan selections, including users field value, valid group selection, and account manager mapping. |  |
      | Serena | Carlotta | Vitale | Vitale Workspace Services SRL | Italy | serena.carlotta.vitale.account169@yopmail.com | No | +39 | 3517946820 | spaces | Simplified Spaces | Yes |  |  |  |  | 30 | Gold | Ayan Test Manager | Creating this Italy-based spaces account to verify monthly spaces business plan assignment, users value, newsletter disabled state, valid group selection, and staff note capture. | Ayan Monthly Spaces Business Plan |
      | Edmund | Laurence | Whitmore | Whitmore Multi Product Services Ltd | United Kingdom | edmund.laurence.whitmore.account170@yopmail.com | Yes | +44 | 7526849130 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 64 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and monthly HR plans together, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Annelies | Margriet | Timmermans | Timmermans Employee Systems BV | Netherlands | annelies.margriet.timmermans.account171@yopmail.com | No | +31 | 682941573 | hr | Simplified HR | Yes |  |  |  |  | 39 | Daimond | Ayan Test Manager | Creating this Netherlands-based HR account to verify monthly HR business plan assignment, users field value, newsletter disabled state, valid group selection, and account manager mapping. | Ayan Monthly HR Business Plan |
      | Gregor | Valentin | Hinterberger | Hinterberger Complete SaaS GmbH | Austria | gregor.valentin.hinterberger.account172@yopmail.com | Yes | +43 | 6765812943 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Space Weekly Plan 99 | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 50 | Silver | Ayan Test Manager | Testing Austria-based all app account creation with weekly checkout, weekly spaces, monthly hire, and weekly HR plans, including users value, newsletter selection, group assignment, and account manager mapping. |  |
      | Dorota | Izabela | Wasilewska | Wasilewska Recruitment Systems Sp z oo | Poland | dorota.izabela.wasilewska.account173@yopmail.com | No | +48 | 516928473 | hire | Simplified Hire | Yes |  |  |  |  | 32 | Gold | Ayan Test Manager | This Poland-based hire account is used to validate monthly hire business plan assignment, users value, newsletter disabled condition, valid group selection, and customer profile details. | Ayan Monthly Hire Business Plan |
      | Mateo | Alejandro | Carrasco | Carrasco Multi App Operations SL | Spain | mateo.alejandro.carrasco.account174@yopmail.com | Yes | +34 | 632784915 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 67 | Gold II | Ayan Test Manager | Verifying Spain-based all app account creation with monthly checkout, yearly spaces, yearly hire, and monthly HR plans, users value, newsletter subscription, valid group, and staff note coverage. |  |
      | Elian | Marco | Rothen | Rothen Checkout Solutions AG | Switzerland | elian.marco.rothen.account175@yopmail.com | No | +41 | 762581493 | checkout | Simplified Checkout | Yes |  |  |  |  | 34 | Daimond | Ayan Test Manager | Creating this Switzerland-based checkout account to verify monthly checkout business plan assignment, users value, newsletter disabled condition, valid group, and staff note save flow. | Ayan Monthly Checkout Business Plan |
      | Linus | Viktor | Dahlstrom | Dahlstrom Unified People Services AB | Sweden | linus.viktor.dahlstrom.account176@yopmail.com | Yes | +46 | 706381492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 56 | Silver | Ayan Test Manager | Testing Sweden-based all app account creation with weekly checkout, weekly spaces, monthly hire, and monthly HR plans, users count, newsletter subscription enabled, and group selection. |  |
      | Romain | Sylvain | Gauthier | Gauthier Workspace Advisory SAS | France | romain.sylvain.gauthier.account177@yopmail.com | No | +33 | 752681943 | spaces | Simplified Spaces | Yes |  |  |  |  | 29 | Gold | Ayan Test Manager | Creating this France-based spaces account to validate monthly spaces business plan selection, users value, newsletter unchecked condition, valid group selection, and internal staff note coverage. | Ayan Monthly Spaces Business Plan |
      | Livia | Mariella | Contarini | Contarini Enterprise SaaS SRL | Italy | livia.mariella.contarini.account178@yopmail.com | Yes | +39 | 3492815763 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan HR New Weekly Plan | 61 | Gold II | Ayan Test Manager | Validating Italy-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans, users value, newsletter subscription, valid group selection, and account manager assignment. |  |
      | Sjoerd | Maarten | Velthuizen | Velthuizen Employee Operations BV | Netherlands | sjoerd.maarten.velthuizen.account179@yopmail.com | No | +31 | 685217493 | hr | Simplified HR | Yes |  |  |  |  | 44 | Daimond | Ayan Test Manager | Testing Netherlands-based HR account creation with weekly HR growth plan assignment, users field value, newsletter disabled state, valid group selection, and staff note entry. | Ayan Weekly HR Growth Plan |
      | Vlad | Teodor | Georgescu | Georgescu Unified Business Operations SRL | Romania | vlad.teodor.georgescu.account180@yopmail.com | Yes | +40 | 735681492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 73 | Silver | Ayan Test Manager | Creating Romania-based all app account to verify monthly checkout, monthly spaces, monthly hire, and monthly HR plan assignment, users field entry, newsletter subscription, and valid group selection. |  |
      | Justyna | Helena | Baranowska | Baranowska Talent Advisory Sp z oo | Poland | justyna.helena.baranowska.account181@yopmail.com | No | +48 | 519628437 | hire | Simplified Hire | Yes |  |  |  |  | 35 | Gold | Ayan Test Manager | Creating this Poland-based hire account to verify monthly hire business plan selection, users value, newsletter disabled condition, valid group assignment, and internal account manager mapping. | Ayan Monthly Hire Business Plan |
      | Nathaniel | Arthur | Wycliffe | Wycliffe Multi Product Services Ltd | United Kingdom | nathaniel.arthur.wycliffe.account182@yopmail.com | Yes | +44 | 7463819250 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 59 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans together, users value, newsletter subscription, and valid group selection. |  |
      | Sindre | Aksel | Vikstrom | Vikstrom Unified Operations AS | Norway | sindre.aksel.vikstrom.account183@yopmail.com | No | +47 | 47829136 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 63 | Daimond | Ayan Test Manager | Creating Norway-based all app account with monthly checkout, yearly spaces, yearly hire, and monthly HR plan selection, users value, newsletter disabled state, and group mapping. |  |
      | Claudia | Theresia | Waldstein | Waldstein Complete SaaS GmbH | Germany | claudia.theresia.waldstein.account184@yopmail.com | Yes | +49 | 15286497310 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 68 | Silver | Ayan Test Manager | Validating Germany-based all app account with yearly checkout, monthly spaces, monthly hire, and yearly HR plans, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Anais | Florence | Lemaire | Lemaire Enterprise Coordination SAS | France | anais.florence.lemaire.account185@yopmail.com | No | +33 | 763581492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 55 | Gold | Ayan Test Manager | Creating France-based all app account to verify weekly checkout, monthly spaces, monthly hire, and monthly HR plans together, users field value, newsletter disabled state, and valid group selection. |  |

  @DeleteLead
  Scenario Outline: Delete SaaS Admin lead for <Contact_Email>
    Given delete SaaS Admin lead using the following feature data
      | Selected Product | <Contact_Selected_Product> |
      | First Name | <Contact_First_Name> |
      | Last Name | <Contact_Last_Name> |
      | Email | <Contact_Email> |
      | Company Name | <Contact_Company_Name> |
      | Country Code | <Contact_Country_Code> |
      | Phone Number | <Contact_Phone_Number> |
      | Message | <Contact_Message> |

    Examples:
      | Contact_Selected_Product | Contact_First_Name | Contact_Last_Name | Contact_Email | Contact_Company_Name | Contact_Country_Code | Contact_Phone_Number | Contact_Message |
      | Simplified HR | Onni Kalevi | Nieminen | onni.kalevi.nieminen.hr308@yopmail.com | Nieminen People Operations Oy | +358 | 459682731 | We are evaluating Simplified HR for employee information management, attendance monitoring, leave approval workflows, department mapping, administrator permissions, internal communication, and workforce reporting. |

  @ApproveLead
  Scenario Outline: Approve SaaS Admin lead with Hire plan <Plan_Hire_Plan_Name>
    Given approve SaaS Admin lead using the following feature data
      | Checkout App Type | <Plan_Checkout_App_Type> |
      | Checkout Plan Name | <Plan_Checkout_Plan_Name> |
      | Spaces App Type | <Plan_Spaces_App_Type> |
      | Spaces Plan Name | <Plan_Spaces_Plan_Name> |
      | Hr App Type | <Plan_Hr_App_Type> |
      | Hr Plan Name | <Plan_Hr_Plan_Name> |
      | Hire App Type | <Plan_Hire_App_Type> |
      | Hire Plan Name | <Plan_Hire_Plan_Name> |

    Examples:
      | Plan_Checkout_App_Type | Plan_Checkout_Plan_Name | Plan_Spaces_App_Type | Plan_Spaces_Plan_Name | Plan_Hr_App_Type | Plan_Hr_Plan_Name | Plan_Hire_App_Type | Plan_Hire_Plan_Name |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | AYan 5 day biilling plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | AYan 5 day biilling plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Custom Weeks Hire Flex Plan |

  @UpgradeAccountPlan
  Scenario Outline: Upgrade SaaS Admin account plan for <Account_Company_Name>
    Given SaaS Admin account upgrade data is provided from the feature file
      | First Name | <Account_First_Name> |
      | Middle Name | <Account_Middle_Name> |
      | Last Name | <Account_Last_Name> |
      | Company Name | <Account_Company_Name> |
      | Country | <Account_Country> |
      | Email | <Account_Email> |
      | Subscribe News | <Account_Subscribe_News> |
      | Country Code | <Account_Country_Code> |
      | Phone Number | <Account_Phone_Number> |
      | App Type | <Account_App_Type> |
      | App Name | <Account_App_Name> |
      | App Enabled | <Account_App_Enabled> |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name | <Account_Spaces_Plan_Name> |
      | Hire Plan Name | <Account_Hire_Plan_Name> |
      | Hr Plan Name | <Account_Hr_Plan_Name> |
      | Users | <Account_Users> |
      | Group | <Account_Group> |
      | Account Manager | <Account_Account_Manager> |
      | Staff Notes | <Account_Staff_Notes> |
      | Plan Name | <Account_Plan_Name> |
    When the SaaS Admin account plan is upgraded using the following billing feature data
      | First Name | <Billing_First_Name> |
      | Last Name | <Billing_Last_Name> |
      | Address | <Billing_Address> |
      | Country | <Billing_Country> |
      | City | <Billing_City> |
      | State | <Billing_State> |
      | Zip | <Billing_Zip> |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name | Billing_First_Name | Billing_Last_Name | Billing_Address | Billing_Country | Billing_City | Billing_State | Billing_Zip |
      | Lorenz | Matthias | Baumgartner | Baumgartner Unified Systems GmbH | Germany | lorenz.matthias.baumgartner.account166@yopmail.com | Yes | +49 | 15728493610 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 47 | Gold II | Ayan Test Manager | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |  | Adrian | Keller | 18 Lindenstrasse, Business Tower 4 | Germany | Berlin | Berlin | 10115 |
      | Elise | Marion | Chastain | Chastain Checkout Advisory SAS | France | elise.marion.chastain.account167@yopmail.com | No | +33 | 756293841 | checkout | Simplified Checkout | Yes |  |  |  |  | 21 | Daimond | Ayan Test Manager | Testing France-based checkout account creation with monthly checkout business plan selection, users value, newsletter disabled state, valid group selection, and new customer contact details. | Ayan Monthly Checkout Business Plan | Claire | Morel | 42 Rue Lafayette, Suite 305 | France | Paris | Ile-de-France | 75009 |
      | Henrik | Olav | Strandheim | Strandheim Integrated Operations AS | Norway | henrik.olav.strandheim.account168@yopmail.com | Yes | +47 | 47936182 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 58 | Silver | Ayan Test Manager | Validating Norway-based all app account creation with weekly checkout, monthly spaces, monthly hire, and yearly HR plan selections, including users field value, valid group selection, and account manager mapping. |  | Matteo | Ricci | 27 Via Torino, Floor 2 | Italy | Milan | Lombardy | 20123 |
      | Serena | Carlotta | Vitale | Vitale Workspace Services SRL | Italy | serena.carlotta.vitale.account169@yopmail.com | No | +39 | 3517946820 | spaces | Simplified Spaces | Yes |  |  |  |  | 30 | Gold | Ayan Test Manager | Creating this Italy-based spaces account to verify monthly spaces business plan assignment, users value, newsletter disabled state, valid group selection, and staff note capture. | Ayan Monthly Spaces Business Plan | Sophie | Van Dijk | 64 Herengracht, Office 12B | Netherlands | Amsterdam | North Holland | 1015BN |
      | Edmund | Laurence | Whitmore | Whitmore Multi Product Services Ltd | United Kingdom | edmund.laurence.whitmore.account170@yopmail.com | Yes | +44 | 7526849130 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 64 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and monthly HR plans together, users value, newsletter subscription, valid group selection, and staff notes. |  | Oliver | Whitfield | 91 King Street, Unit 7 | United Kingdom | London | England | SW1A 1AA |
      | Annelies | Margriet | Timmermans | Timmermans Employee Systems BV | Netherlands | annelies.margriet.timmermans.account171@yopmail.com | No | +31 | 682941573 | hr | Simplified HR | Yes |  |  |  |  | 39 | Daimond | Ayan Test Manager | Creating this Netherlands-based HR account to verify monthly HR business plan assignment, users field value, newsletter disabled state, valid group selection, and account manager mapping. | Ayan Monthly HR Business Plan | Isabella | Martinez | 35 Calle de Alcala, Planta 4 | Spain | Madrid | Community of Madrid | 28014 |
      | Gregor | Valentin | Hinterberger | Hinterberger Complete SaaS GmbH | Austria | gregor.valentin.hinterberger.account172@yopmail.com | Yes | +43 | 6765812943 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Space Weekly Plan 99 | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 50 | Silver | Ayan Test Manager | Testing Austria-based all app account creation with weekly checkout, weekly spaces, monthly hire, and weekly HR plans, including users value, newsletter selection, group assignment, and account manager mapping. |  | Erik | Lundgren | 22 Drottninggatan, Workspace 8 | Sweden | Stockholm | Stockholm County | 11151 |
      | Dorota | Izabela | Wasilewska | Wasilewska Recruitment Systems Sp z oo | Poland | dorota.izabela.wasilewska.account173@yopmail.com | No | +48 | 516928473 | hire | Simplified Hire | Yes |  |  |  |  | 32 | Gold | Ayan Test Manager | This Poland-based hire account is used to validate monthly hire business plan assignment, users value, newsletter disabled condition, valid group selection, and customer profile details. | Ayan Monthly Hire Business Plan | Nora | Bergheim | 14 Karl Johans Gate, Office 6 | Norway | Oslo | Oslo | 0154 |
      | Mateo | Alejandro | Carrasco | Carrasco Multi App Operations SL | Spain | mateo.alejandro.carrasco.account174@yopmail.com | Yes | +34 | 632784915 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 67 | Gold II | Ayan Test Manager | Verifying Spain-based all app account creation with monthly checkout, yearly spaces, yearly hire, and monthly HR plans, users value, newsletter subscription, valid group, and staff note coverage. |  | Lukas | Meier | 58 Bahnhofstrasse, Level 3 | Switzerland | Zurich | Zurich | 8001 |
      | Elian | Marco | Rothen | Rothen Checkout Solutions AG | Switzerland | elian.marco.rothen.account175@yopmail.com | No | +41 | 762581493 | checkout | Simplified Checkout | Yes |  |  |  |  | 34 | Daimond | Ayan Test Manager | Creating this Switzerland-based checkout account to verify monthly checkout business plan assignment, users value, newsletter disabled condition, valid group, and staff note save flow. | Ayan Monthly Checkout Business Plan | Emily | Anderson | 120 Madison Avenue, Suite 904 | United States | New York | New York | 10016 |
      | Linus | Viktor | Dahlstrom | Dahlstrom Unified People Services AB | Sweden | linus.viktor.dahlstrom.account176@yopmail.com | Yes | +46 | 706381492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 56 | Silver | Ayan Test Manager | Testing Sweden-based all app account creation with weekly checkout, weekly spaces, monthly hire, and monthly HR plans, users count, newsletter subscription enabled, and group selection. |  | Henrik | Schneider | 73 Maximilianstrasse, Office 210 | Germany | Munich | Bavaria | 80539 |
      | Romain | Sylvain | Gauthier | Gauthier Workspace Advisory SAS | France | romain.sylvain.gauthier.account177@yopmail.com | No | +33 | 752681943 | spaces | Simplified Spaces | Yes |  |  |  |  | 29 | Gold | Ayan Test Manager | Creating this France-based spaces account to validate monthly spaces business plan selection, users value, newsletter unchecked condition, valid group selection, and internal staff note coverage. | Ayan Monthly Spaces Business Plan | Juliette | Bernard | 16 Rue Victor Hugo, Batiment B | France | Lyon | Auvergne-Rhone-Alpes | 69002 |
      | Livia | Mariella | Contarini | Contarini Enterprise SaaS SRL | Italy | livia.mariella.contarini.account178@yopmail.com | Yes | +39 | 3492815763 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan HR New Weekly Plan | 61 | Gold II | Ayan Test Manager | Validating Italy-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans, users value, newsletter subscription, valid group selection, and account manager assignment. |  | Alessandro | Ferrari | 49 Via Nazionale, Scala A | Italy | Rome | Lazio | 00184 |
      | Sjoerd | Maarten | Velthuizen | Velthuizen Employee Operations BV | Netherlands | sjoerd.maarten.velthuizen.account179@yopmail.com | No | +31 | 685217493 | hr | Simplified HR | Yes |  |  |  |  | 44 | Daimond | Ayan Test Manager | Testing Netherlands-based HR account creation with weekly HR growth plan assignment, users field value, newsletter disabled state, valid group selection, and staff note entry. | Ayan Weekly HR Growth Plan | Mila | Jansen | 31 Coolsingel, Business Center | Netherlands | Rotterdam | South Holland | 3012AD |
      | Vlad | Teodor | Georgescu | Georgescu Unified Business Operations SRL | Romania | vlad.teodor.georgescu.account180@yopmail.com | Yes | +40 | 735681492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 73 | Silver | Ayan Test Manager | Creating Romania-based all app account to verify monthly checkout, monthly spaces, monthly hire, and monthly HR plan assignment, users field entry, newsletter subscription, and valid group selection. |  | George | Harrington | 77 Deansgate, Floor 5 | United Kingdom | Manchester | England | M3 2BW |
      | Justyna | Helena | Baranowska | Baranowska Talent Advisory Sp z oo | Poland | justyna.helena.baranowska.account181@yopmail.com | No | +48 | 519628437 | hire | Simplified Hire | Yes |  |  |  |  | 35 | Gold | Ayan Test Manager | Creating this Poland-based hire account to verify monthly hire business plan selection, users value, newsletter disabled condition, valid group assignment, and internal account manager mapping. | Ayan Monthly Hire Business Plan | Lucia | Navarro | 88 Passeig de Gracia, Oficina 9 | Spain | Barcelona | Catalonia | 08008 |
      | Nathaniel | Arthur | Wycliffe | Wycliffe Multi Product Services Ltd | United Kingdom | nathaniel.arthur.wycliffe.account182@yopmail.com | Yes | +44 | 7463819250 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 59 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans together, users value, newsletter subscription, and valid group selection. |  | Astrid | Nyström | 45 Sodra Forstadsgatan, Unit 11 | Sweden | Malmo | Skane County | 21143 |
      | Sindre | Aksel | Vikstrom | Vikstrom Unified Operations AS | Norway | sindre.aksel.vikstrom.account183@yopmail.com | No | +47 | 47829136 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 63 | Daimond | Ayan Test Manager | Creating Norway-based all app account with monthly checkout, yearly spaces, yearly hire, and monthly HR plan selection, users value, newsletter disabled state, and group mapping. |  | Magnus | Haukeland | 9 Bryggen, Office 3 | Norway | Bergen | Vestland | 5003 |
      | Claudia | Theresia | Waldstein | Waldstein Complete SaaS GmbH | Germany | claudia.theresia.waldstein.account184@yopmail.com | Yes | +49 | 15286497310 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 68 | Silver | Ayan Test Manager | Validating Germany-based all app account with yearly checkout, monthly spaces, monthly hire, and yearly HR plans, users value, newsletter subscription, valid group selection, and staff notes. |  | Elena | Vogel | 26 Rue du Rhone, Suite 15 | Switzerland | Geneva | Geneva | 1204 |
      | Anais | Florence | Lemaire | Lemaire Enterprise Coordination SAS | France | anais.florence.lemaire.account185@yopmail.com | No | +33 | 763581492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 55 | Gold | Ayan Test Manager | Creating France-based all app account to verify weekly checkout, monthly spaces, monthly hire, and monthly HR plans together, users field value, newsletter disabled state, and valid group selection. |  | Daniel | Carter | 430 North Michigan Avenue, Suite 1200 | United States | Chicago | Illinois | 60611 |

  @ActivateAccount
  Scenario Outline: Activate SaaS Admin account for <Account_Company_Name>
    Given activate SaaS Admin account using the following feature data
      | First Name | <Account_First_Name> |
      | Middle Name | <Account_Middle_Name> |
      | Last Name | <Account_Last_Name> |
      | Company Name | <Account_Company_Name> |
      | Country | <Account_Country> |
      | Email | <Account_Email> |
      | Subscribe News | <Account_Subscribe_News> |
      | Country Code | <Account_Country_Code> |
      | Phone Number | <Account_Phone_Number> |
      | App Type | <Account_App_Type> |
      | App Name | <Account_App_Name> |
      | App Enabled | <Account_App_Enabled> |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name | <Account_Spaces_Plan_Name> |
      | Hire Plan Name | <Account_Hire_Plan_Name> |
      | Hr Plan Name | <Account_Hr_Plan_Name> |
      | Users | <Account_Users> |
      | Group | <Account_Group> |
      | Account Manager | <Account_Account_Manager> |
      | Staff Notes | <Account_Staff_Notes> |
      | Plan Name | <Account_Plan_Name> |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lorenz | Matthias | Baumgartner | Baumgartner Unified Systems GmbH | Germany | lorenz.matthias.baumgartner.account166@yopmail.com | Yes | +49 | 15728493610 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 47 | Gold II | Ayan Test Manager | Creating this Germany-based all app account to validate monthly checkout, monthly spaces, monthly hire, and monthly HR plans together with users value, group selection, newsletter subscription, and account manager mapping. |  |
      | Elise | Marion | Chastain | Chastain Checkout Advisory SAS | France | elise.marion.chastain.account167@yopmail.com | No | +33 | 756293841 | checkout | Simplified Checkout | Yes |  |  |  |  | 21 | Daimond | Ayan Test Manager | Testing France-based checkout account creation with monthly checkout business plan selection, users value, newsletter disabled state, valid group selection, and new customer contact details. | Ayan Monthly Checkout Business Plan |
      | Henrik | Olav | Strandheim | Strandheim Integrated Operations AS | Norway | henrik.olav.strandheim.account168@yopmail.com | Yes | +47 | 47936182 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 58 | Silver | Ayan Test Manager | Validating Norway-based all app account creation with weekly checkout, monthly spaces, monthly hire, and yearly HR plan selections, including users field value, valid group selection, and account manager mapping. |  |
      | Serena | Carlotta | Vitale | Vitale Workspace Services SRL | Italy | serena.carlotta.vitale.account169@yopmail.com | No | +39 | 3517946820 | spaces | Simplified Spaces | Yes |  |  |  |  | 30 | Gold | Ayan Test Manager | Creating this Italy-based spaces account to verify monthly spaces business plan assignment, users value, newsletter disabled state, valid group selection, and staff note capture. | Ayan Monthly Spaces Business Plan |
      | Edmund | Laurence | Whitmore | Whitmore Multi Product Services Ltd | United Kingdom | edmund.laurence.whitmore.account170@yopmail.com | Yes | +44 | 7526849130 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 64 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and monthly HR plans together, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Annelies | Margriet | Timmermans | Timmermans Employee Systems BV | Netherlands | annelies.margriet.timmermans.account171@yopmail.com | No | +31 | 682941573 | hr | Simplified HR | Yes |  |  |  |  | 39 | Daimond | Ayan Test Manager | Creating this Netherlands-based HR account to verify monthly HR business plan assignment, users field value, newsletter disabled state, valid group selection, and account manager mapping. | Ayan Monthly HR Business Plan |
      | Gregor | Valentin | Hinterberger | Hinterberger Complete SaaS GmbH | Austria | gregor.valentin.hinterberger.account172@yopmail.com | Yes | +43 | 6765812943 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Space Weekly Plan 99 | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 50 | Silver | Ayan Test Manager | Testing Austria-based all app account creation with weekly checkout, weekly spaces, monthly hire, and weekly HR plans, including users value, newsletter selection, group assignment, and account manager mapping. |  |
      | Dorota | Izabela | Wasilewska | Wasilewska Recruitment Systems Sp z oo | Poland | dorota.izabela.wasilewska.account173@yopmail.com | No | +48 | 516928473 | hire | Simplified Hire | Yes |  |  |  |  | 32 | Gold | Ayan Test Manager | This Poland-based hire account is used to validate monthly hire business plan assignment, users value, newsletter disabled condition, valid group selection, and customer profile details. | Ayan Monthly Hire Business Plan |
      | Mateo | Alejandro | Carrasco | Carrasco Multi App Operations SL | Spain | mateo.alejandro.carrasco.account174@yopmail.com | Yes | +34 | 632784915 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 67 | Gold II | Ayan Test Manager | Verifying Spain-based all app account creation with monthly checkout, yearly spaces, yearly hire, and monthly HR plans, users value, newsletter subscription, valid group, and staff note coverage. |  |
      | Elian | Marco | Rothen | Rothen Checkout Solutions AG | Switzerland | elian.marco.rothen.account175@yopmail.com | No | +41 | 762581493 | checkout | Simplified Checkout | Yes |  |  |  |  | 34 | Daimond | Ayan Test Manager | Creating this Switzerland-based checkout account to verify monthly checkout business plan assignment, users value, newsletter disabled condition, valid group, and staff note save flow. | Ayan Monthly Checkout Business Plan |
      | Linus | Viktor | Dahlstrom | Dahlstrom Unified People Services AB | Sweden | linus.viktor.dahlstrom.account176@yopmail.com | Yes | +46 | 706381492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Checkout Weekly 999 | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 56 | Silver | Ayan Test Manager | Testing Sweden-based all app account creation with weekly checkout, weekly spaces, monthly hire, and monthly HR plans, users count, newsletter subscription enabled, and group selection. |  |
      | Romain | Sylvain | Gauthier | Gauthier Workspace Advisory SAS | France | romain.sylvain.gauthier.account177@yopmail.com | No | +33 | 752681943 | spaces | Simplified Spaces | Yes |  |  |  |  | 29 | Gold | Ayan Test Manager | Creating this France-based spaces account to validate monthly spaces business plan selection, users value, newsletter unchecked condition, valid group selection, and internal staff note coverage. | Ayan Monthly Spaces Business Plan |
      | Livia | Mariella | Contarini | Contarini Enterprise SaaS SRL | Italy | livia.mariella.contarini.account178@yopmail.com | Yes | +39 | 3492815763 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan HR New Weekly Plan | 61 | Gold II | Ayan Test Manager | Validating Italy-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans, users value, newsletter subscription, valid group selection, and account manager assignment. |  |
      | Sjoerd | Maarten | Velthuizen | Velthuizen Employee Operations BV | Netherlands | sjoerd.maarten.velthuizen.account179@yopmail.com | No | +31 | 685217493 | hr | Simplified HR | Yes |  |  |  |  | 44 | Daimond | Ayan Test Manager | Testing Netherlands-based HR account creation with weekly HR growth plan assignment, users field value, newsletter disabled state, valid group selection, and staff note entry. | Ayan Weekly HR Growth Plan |
      | Vlad | Teodor | Georgescu | Georgescu Unified Business Operations SRL | Romania | vlad.teodor.georgescu.account180@yopmail.com | Yes | +40 | 735681492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 73 | Silver | Ayan Test Manager | Creating Romania-based all app account to verify monthly checkout, monthly spaces, monthly hire, and monthly HR plan assignment, users field entry, newsletter subscription, and valid group selection. |  |
      | Justyna | Helena | Baranowska | Baranowska Talent Advisory Sp z oo | Poland | justyna.helena.baranowska.account181@yopmail.com | No | +48 | 519628437 | hire | Simplified Hire | Yes |  |  |  |  | 35 | Gold | Ayan Test Manager | Creating this Poland-based hire account to verify monthly hire business plan selection, users value, newsletter disabled condition, valid group assignment, and internal account manager mapping. | Ayan Monthly Hire Business Plan |
      | Nathaniel | Arthur | Wycliffe | Wycliffe Multi Product Services Ltd | United Kingdom | nathaniel.arthur.wycliffe.account182@yopmail.com | Yes | +44 | 7463819250 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 59 | Gold II | Ayan Test Manager | Testing UK-based all app account creation with yearly checkout, monthly spaces, monthly hire, and weekly HR plans together, users value, newsletter subscription, and valid group selection. |  |
      | Sindre | Aksel | Vikstrom | Vikstrom Unified Operations AS | Norway | sindre.aksel.vikstrom.account183@yopmail.com | No | +47 | 47829136 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | testyearly | Ayan Monthly HR Business Plan | 63 | Daimond | Ayan Test Manager | Creating Norway-based all app account with monthly checkout, yearly spaces, yearly hire, and monthly HR plan selection, users value, newsletter disabled state, and group mapping. |  |
      | Claudia | Theresia | Waldstein | Waldstein Complete SaaS GmbH | Germany | claudia.theresia.waldstein.account184@yopmail.com | Yes | +49 | 15286497310 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Yearly HR Enterprise Plan | 68 | Silver | Ayan Test Manager | Validating Germany-based all app account with yearly checkout, monthly spaces, monthly hire, and yearly HR plans, users value, newsletter subscription, valid group selection, and staff notes. |  |
      | Anais | Florence | Lemaire | Lemaire Enterprise Coordination SAS | France | anais.florence.lemaire.account185@yopmail.com | No | +33 | 763581492 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | test weekly checkout plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Monthly HR Business Plan | 55 | Gold | Ayan Test Manager | Creating France-based all app account to verify weekly checkout, monthly spaces, monthly hire, and monthly HR plans together, users field value, newsletter disabled state, and valid group selection. |  |
