@SaasAdmin
Feature: SaaS Admin feature-driven account and lead workflows

  @SaasAdminLogin
  Scenario: Login to SaaS Admin
    Given login to SaaS Admin portal


  @DraftAccount
  Scenario Outline: Create draft account for <Account_Company_Name>

    Given create SaaS Admin draft account using the following feature data
      | First Name         | <Account_First_Name>         |
      | Middle Name        | <Account_Middle_Name>        |
      | Last Name          | <Account_Last_Name>          |
      | Company Name       | <Account_Company_Name>       |
      | Country            | <Account_Country>            |
      | Email              | <Account_Email>              |
      | Subscribe News     | <Account_Subscribe_News>     |
      | Country Code       | <Account_Country_Code>       |
      | Phone Number       | <Account_Phone_Number>       |
      | App Type           | <Account_App_Type>           |
      | App Name           | <Account_App_Name>           |
      | App Enabled        | <Account_App_Enabled>        |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name   | <Account_Spaces_Plan_Name>   |
      | Hire Plan Name     | <Account_Hire_Plan_Name>     |
      | Hr Plan Name       | <Account_Hr_Plan_Name>       |
      | Users              | <Account_Users>              |
      | Group              | <Account_Group>              |
      | Account Manager    | <Account_Account_Manager>    |
      | Staff Notes        | <Account_Staff_Notes>        |
      | Plan Name          | <Account_Plan_Name>          |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lothar | Severinus | Eisenhardt | Eisenhardt Unified Commerce GmbH | Germany | lothar.severinus.eisenhardt.saasaccount406@yopmail.com | Yes | +49 | 17160483295 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 66 | Gold II | Ayan Test Manager | Creating this Germany-based all-app account with newly generated identity, email, phone, users, plans, group, newsletter preference, and account manager data. |  |
      | Clemence | Aurelie | Fontenay | Fontenay Checkout Technologies SAS | France | clemence.aurelie.fontenay.saasaccount407@yopmail.com | No | +33 | 612984735 | checkout | Simplified Checkout | Yes |  |  |  |  | 29 | Diamond | Ayan Test Manager | Validating this France-based Checkout account with fresh customer details, a unique email address, a new phone number, user allocation, group mapping, and staff notes. | Ayan Daily Checkout Starter Plan |
      | Bjorn | Hallstein | Myklebust | Myklebust Enterprise Platforms AS | Norway | bjorn.hallstein.myklebust.saasaccount408@yopmail.com | Yes | +47 | 93618427 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan New Professional Diamond Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 71 | Silver | Ayan Test Manager | Testing this Norway-based all-app account using newly generated contact information, application plans, user count, subscription preference, and group assignment. |  |
      | Ewelina | Jadwiga | Przybysz | Przybysz Talent Systems Sp z oo | Poland | ewelina.jadwiga.przybysz.saasaccount409@yopmail.com | No | +48 | 607294183 | hire | Simplified Hire | Yes |  |  |  |  | 38 | Gold | Ayan Test Manager | Creating this Poland-based Hire account with a new name, email, phone number, recruitment plan, users, group, account manager, and staff-note value. | Ayan Monthly Hire Business Plan |
      | Cosimo | Leandro | Ventresca | Ventresca Integrated Operations SRL | Italy | cosimo.leandro.ventresca.saasaccount410@yopmail.com | Yes | +39 | 3207481956 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 62 | Gold II | Ayan Test Manager | Validating this Italy-based all-app account with fresh identity and contact values across account creation, plan assignment, upgrade, and activation workflows. |  |
      | Willemijn | Katelijne | Van Breukelen | Van Breukelen Workspace Solutions BV | Netherlands | willemijn.katelijne.vanbreukelen.saasaccount411@yopmail.com | No | +31 | 615827439 | spaces | Simplified Spaces | Yes |  |  |  |  | 35 | Diamond | Ayan Test Manager | Creating this Netherlands-based Spaces account using a completely new name, email address, phone number, workspace plan, users, group, and notes. | Ayan Weekly Spaces Growth Plan |
      | Arttu | Samuli | Hietala | Hietala Complete Business Oy | Finland | arttu.samuli.hietala.saasaccount412@yopmail.com | Yes | +358 | 401936275 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Advance Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 74 | Silver | Ayan Test Manager | Testing this Finland-based all-app account with newly generated identity, contact details, plan combinations, user allocation, newsletter state, and manager mapping. |  |
      | Gaspard | Etienne | Rouxel | Rouxel Digital Checkout SRL | Belgium | gaspard.etienne.rouxel.saasaccount413@yopmail.com | No | +32 | 468723195 | checkout | Simplified Checkout | Yes |  |  |  |  | 26 | Gold | Ayan Test Manager | Creating this Belgium-based Checkout account with fresh customer data, unique email and phone values, a custom plan, user count, group, and staff notes. | Ayan Monthly Checkout Business Plan |
      | Niklas | Antero | Holmqvist | Holmqvist Unified Cloud AB | Sweden | niklas.antero.holmqvist.saasaccount414@yopmail.com | Yes | +46 | 735918264 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Daily Checkout Starter Plan | Ayan Daily Spaces Starter Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 68 | Gold II | Ayan Test Manager | Validating this Sweden-based all-app account using new personal details, contact data, application plans, users, subscription choice, and Gold II group mapping. |  |
      | Sorina | Otilia | Cernat | Cernat Human Capital SRL | Romania | sorina.otilia.cernat.saasaccount415@yopmail.com | No | +40 | 746193825 | hr | Simplified HR | Yes |  |  |  |  | 43 | Diamond | Ayan Test Manager | Creating this Romania-based HR account with a never-reused name, email address, phone number, HR plan, users, group selection, manager, and notes. | Ayan Custom Days HR Flex Plan |
      | Karel | Vojtech | Benes | Benes Enterprise Services sro | Czech Republic | karel.vojtech.benes.saasaccount416@yopmail.com | Yes | +420 | 602817394 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Premium Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 57 | Silver | Ayan Test Manager | Testing this Czech Republic-based all-app account with completely fresh identity, phone, email, plan mapping, users, newsletter preference, and staff notes. |  |
      | Ainhoa | Leire | Mendizabal | Mendizabal Workspace Management SL | Spain | ainhoa.leire.mendizabal.saasaccount417@yopmail.com | No | +34 | 672839145 | spaces | Simplified Spaces | Yes |  |  |  |  | 31 | Gold | Ayan Test Manager | Creating this Spain-based Spaces account with newly generated contact details, workspace subscription, users, group, account manager, and internal notes. | Ayan Monthly Spaces Business Plan |
      | Sigrid | Thora | Enevoldsen | Enevoldsen Integrated Systems ApS | Denmark | sigrid.thora.enevoldsen.saasaccount418@yopmail.com | Yes | +45 | 51827364 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan New Professional Diamond Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 76 | Gold II | Ayan Test Manager | Validating this Denmark-based all-app account with a fresh name, email, phone, application plans, user allocation, subscription status, and group mapping. |  |
      | Levente | Zoltan | Berczi | Berczi Recruitment Platforms Kft | Hungary | levente.zoltan.berczi.saasaccount419@yopmail.com | No | +36 | 209483761 | hire | Simplified Hire | Yes |  |  |  |  | 40 | Diamond | Ayan Test Manager | Creating this Hungary-based Hire account with new identity and contact values, a custom Hire plan, users, group, account manager, and staff notes. | Ayan Custom Weeks Hire Flex Plan |
      | Freydis | Solvej | Munkholm | Munkholm Complete Operations GmbH | Austria | freydis.solvej.munkholm.saasaccount420@yopmail.com | Yes | +43 | 6762941835 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 63 | Silver | Ayan Test Manager | Testing this Austria-based all-app account using newly generated identity, email, phone, plan values, users, newsletter preference, and Silver group assignment. |  |
      | Radoslaw | Ignacy | Milewski | Milewski Checkout Services Sp z oo | Poland | radoslaw.ignacy.milewski.saasaccount421@yopmail.com | No | +48 | 695381247 | checkout | Simplified Checkout | Yes |  |  |  |  | 24 | Gold | Ayan Test Manager | Creating this Poland-based Checkout account with a completely fresh name, email address, phone number, Checkout plan, users, group, and manager data. | Ayan Daily Checkout Starter Plan |
      | Vedrana | Danica | Vrbancic | Vrbancic Unified Enterprise doo | Croatia | vedrana.danica.vrbancic.saasaccount422@yopmail.com | Yes | +385 | 992746381 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 69 | Gold II | Ayan Test Manager | Validating this Croatia-based all-app account with newly generated customer identity, contact details, application plans, users, group, and newsletter state. |  |
      | Baptiste | Loic | Giraudon | Giraudon People Operations SAS | France | baptiste.loic.giraudon.saasaccount423@yopmail.com | No | +33 | 645927381 | hr | Simplified HR | Yes |  |  |  |  | 45 | Diamond | Ayan Test Manager | Creating this France-based HR account with fresh identity, a unique email address, a new phone number, HR plan, users, group selection, and staff notes. | Ayan HR New Weekly Plan |
      | Aafke | Rosalinde | Ten Broeke | Ten Broeke Integrated Cloud BV | Netherlands | aafke.rosalinde.tenbroeke.saasaccount424@yopmail.com | Yes | +31 | 642918357 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Daily Spaces Starter Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 72 | Silver | Ayan Test Manager | Testing this Netherlands-based all-app account with completely new name, email, phone, application plans, users, account manager, and subscription preference. |  |
      | Eero | Jalmari | Kuusisto | Kuusisto Complete Platforms Oy | Finland | eero.jalmari.kuusisto.saasaccount425@yopmail.com | No | +358 | 509284736 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Daily HR Starter Plan | 54 | Gold | Ayan Test Manager | Creating this Finland-based all-app account using fresh personal and contact data, unique plan combinations, user count, group assignment, and staff notes. |  |


  @CreateAccount
  Scenario Outline: Create, upgrade, and activate SaaS Admin account for <Account_Company_Name>

    Given SaaS Admin account plan data is provided from the feature file
      | Checkout App Type  | <Plan_Checkout_App_Type>  |
      | Checkout Plan Name | <Plan_Checkout_Plan_Name> |
      | Spaces App Type    | <Plan_Spaces_App_Type>    |
      | Spaces Plan Name   | <Plan_Spaces_Plan_Name>   |
      | Hr App Type        | <Plan_Hr_App_Type>        |
      | Hr Plan Name       | <Plan_Hr_Plan_Name>       |
      | Hire App Type      | <Plan_Hire_App_Type>      |
      | Hire Plan Name     | <Plan_Hire_Plan_Name>     |

    And SaaS Admin account billing data is provided from the feature file
      | First Name | <Billing_First_Name> |
      | Last Name  | <Billing_Last_Name>  |
      | Address    | <Billing_Address>    |
      | Country    | <Billing_Country>    |
      | City       | <Billing_City>       |
      | State      | <Billing_State>      |
      | Zip        | <Billing_Zip>        |

    And create SaaS Admin account using the following feature data
      | First Name         | <Account_First_Name>         |
      | Middle Name        | <Account_Middle_Name>        |
      | Last Name          | <Account_Last_Name>          |
      | Company Name       | <Account_Company_Name>       |
      | Country            | <Account_Country>            |
      | Email              | <Account_Email>              |
      | Subscribe News     | <Account_Subscribe_News>     |
      | Country Code       | <Account_Country_Code>       |
      | Phone Number       | <Account_Phone_Number>       |
      | App Type           | <Account_App_Type>           |
      | App Name           | <Account_App_Name>           |
      | App Enabled        | <Account_App_Enabled>        |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name   | <Account_Spaces_Plan_Name>   |
      | Hire Plan Name     | <Account_Hire_Plan_Name>     |
      | Hr Plan Name       | <Account_Hr_Plan_Name>       |
      | Users              | <Account_Users>              |
      | Group              | <Account_Group>              |
      | Account Manager    | <Account_Account_Manager>    |
      | Staff Notes        | <Account_Staff_Notes>        |
      | Plan Name          | <Account_Plan_Name>          |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name | Plan_Checkout_App_Type | Plan_Checkout_Plan_Name | Plan_Spaces_App_Type | Plan_Spaces_Plan_Name | Plan_Hr_App_Type | Plan_Hr_Plan_Name | Plan_Hire_App_Type | Plan_Hire_Plan_Name | Billing_First_Name | Billing_Last_Name | Billing_Address | Billing_Country | Billing_City | Billing_State | Billing_Zip |
      | Lothar | Severinus | Eisenhardt | Eisenhardt Unified Commerce GmbH | Germany | lothar.severinus.eisenhardt.saasaccount406@yopmail.com | Yes | +49 | 17160483295 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 66 | Gold II | Ayan Test Manager | Creating this Germany-based all-app account with newly generated identity, email, phone, users, plans, group, newsletter preference, and account manager data. |  | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Weeks Hire Flex Plan | Oskar | Feldmann | 23 Friedrichstrasse, Office 7 | Germany | Hamburg | Hamburg | 20095 |
      | Clemence | Aurelie | Fontenay | Fontenay Checkout Technologies SAS | France | clemence.aurelie.fontenay.saasaccount407@yopmail.com | No | +33 | 612984735 | checkout | Simplified Checkout | Yes |  |  |  |  | 29 | Diamond | Ayan Test Manager | Validating this France-based Checkout account with fresh customer details, a unique email address, a new phone number, user allocation, group mapping, and staff notes. | Ayan Daily Checkout Starter Plan | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Months Hire Premium Plan | Lucie | Perrin | 58 Avenue de Wagram, Suite 12 | France | Paris | Ile-de-France | 75017 |
      | Bjorn | Hallstein | Myklebust | Myklebust Enterprise Platforms AS | Norway | bjorn.hallstein.myklebust.saasaccount408@yopmail.com | Yes | +47 | 93618427 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan New Professional Diamond Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 71 | Silver | Ayan Test Manager | Testing this Norway-based all-app account using newly generated contact information, application plans, user count, subscription preference, and group assignment. |  | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan | Anders | Ravnvik | 11 Storgata, Floor 4 | Norway | Trondheim | Trondelag | 7010 |
      | Ewelina | Jadwiga | Przybysz | Przybysz Talent Systems Sp z oo | Poland | ewelina.jadwiga.przybysz.saasaccount409@yopmail.com | No | +48 | 607294183 | hire | Simplified Hire | Yes |  |  |  |  | 38 | Gold | Ayan Test Manager | Creating this Poland-based Hire account with a new name, email, phone number, recruitment plan, users, group, account manager, and staff-note value. | Ayan Monthly Hire Business Plan | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Weeks Hire Flex Plan | Tomasz | Bielecki | 72 Marszalkowska, Office 18 | Poland | Warsaw | Masovian | 00-545 |
      | Cosimo | Leandro | Ventresca | Ventresca Integrated Operations SRL | Italy | cosimo.leandro.ventresca.saasaccount410@yopmail.com | Yes | +39 | 3207481956 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 62 | Gold II | Ayan Test Manager | Validating this Italy-based all-app account with fresh identity and contact values across account creation, plan assignment, upgrade, and activation workflows. |  | checkout | AYan 5 day biilling plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Months Hire Premium Plan | Bianca | Moretti | 36 Via Dante, Scala C | Italy | Florence | Tuscany | 50122 |
      | Willemijn | Katelijne | Van Breukelen | Van Breukelen Workspace Solutions BV | Netherlands | willemijn.katelijne.vanbreukelen.saasaccount411@yopmail.com | No | +31 | 615827439 | spaces | Simplified Spaces | Yes |  |  |  |  | 35 | Diamond | Ayan Test Manager | Creating this Netherlands-based Spaces account using a completely new name, email address, phone number, workspace plan, users, group, and notes. | Ayan Weekly Spaces Growth Plan | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan | Jeroen | Koster | 81 Keizersgracht, Unit 9 | Netherlands | Utrecht | Utrecht | 3511AA |
      | Arttu | Samuli | Hietala | Hietala Complete Business Oy | Finland | arttu.samuli.hietala.saasaccount412@yopmail.com | Yes | +358 | 401936275 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Advance Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 74 | Silver | Ayan Test Manager | Testing this Finland-based all-app account with newly generated identity, contact details, plan combinations, user allocation, newsletter state, and manager mapping. |  | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Weeks Hire Flex Plan | Sanna | Heikkinen | 14 Mannerheimintie, Level 6 | Finland | Helsinki | Uusimaa | 00100 |
      | Gaspard | Etienne | Rouxel | Rouxel Digital Checkout SRL | Belgium | gaspard.etienne.rouxel.saasaccount413@yopmail.com | No | +32 | 468723195 | checkout | Simplified Checkout | Yes |  |  |  |  | 26 | Gold | Ayan Test Manager | Creating this Belgium-based Checkout account with fresh customer data, unique email and phone values, a custom plan, user count, group, and staff notes. | Ayan Monthly Checkout Business Plan | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Months Hire Premium Plan | Arnaud | Lambert | 29 Boulevard Anspach, Bureau 5 | Belgium | Brussels | Brussels-Capital | 1000 |
      | Niklas | Antero | Holmqvist | Holmqvist Unified Cloud AB | Sweden | niklas.antero.holmqvist.saasaccount414@yopmail.com | Yes | +46 | 735918264 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Daily Checkout Starter Plan | Ayan Daily Spaces Starter Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 68 | Gold II | Ayan Test Manager | Validating this Sweden-based all-app account using new personal details, contact data, application plans, users, subscription choice, and Gold II group mapping. |  | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan | Ebba | Sjostrom | 44 Vasagatan, Workspace 3 | Sweden | Gothenburg | Vastra Gotaland | 41124 |
      | Sorina | Otilia | Cernat | Cernat Human Capital SRL | Romania | sorina.otilia.cernat.saasaccount415@yopmail.com | No | +40 | 746193825 | hr | Simplified HR | Yes |  |  |  |  | 43 | Diamond | Ayan Test Manager | Creating this Romania-based HR account with a never-reused name, email address, phone number, HR plan, users, group selection, manager, and notes. | Ayan Custom Days HR Flex Plan | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Weeks Hire Flex Plan | Mircea | Ionescu | 19 Calea Victoriei, Floor 8 | Romania | Bucharest | Bucharest | 010061 |
      | Karel | Vojtech | Benes | Benes Enterprise Services sro | Czech Republic | karel.vojtech.benes.saasaccount416@yopmail.com | Yes | +420 | 602817394 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Premium Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 57 | Silver | Ayan Test Manager | Testing this Czech Republic-based all-app account with completely fresh identity, phone, email, plan mapping, users, newsletter preference, and staff notes. |  | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Months Hire Premium Plan | Pavel | Dvorak | 63 Vaclavske Namesti, Office 14 | Czech Republic | Prague | Prague | 11000 |
      | Ainhoa | Leire | Mendizabal | Mendizabal Workspace Management SL | Spain | ainhoa.leire.mendizabal.saasaccount417@yopmail.com | No | +34 | 672839145 | spaces | Simplified Spaces | Yes |  |  |  |  | 31 | Gold | Ayan Test Manager | Creating this Spain-based Spaces account with newly generated contact details, workspace subscription, users, group, account manager, and internal notes. | Ayan Monthly Spaces Business Plan | checkout | AYan 5 day biilling plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan | Iker | Salcedo | 47 Gran Via, Planta 6 | Spain | Bilbao | Basque Country | 48011 |
      | Sigrid | Thora | Enevoldsen | Enevoldsen Integrated Systems ApS | Denmark | sigrid.thora.enevoldsen.saasaccount418@yopmail.com | Yes | +45 | 51827364 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan New Professional Diamond Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 76 | Gold II | Ayan Test Manager | Validating this Denmark-based all-app account with a fresh name, email, phone, application plans, user allocation, subscription status, and group mapping. |  | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Weeks Hire Flex Plan | Mads | Nissen | 25 Vesterbrogade, Office 10 | Denmark | Aarhus | Central Denmark | 8000 |
      | Levente | Zoltan | Berczi | Berczi Recruitment Platforms Kft | Hungary | levente.zoltan.berczi.saasaccount419@yopmail.com | No | +36 | 209483761 | hire | Simplified Hire | Yes |  |  |  |  | 40 | Diamond | Ayan Test Manager | Creating this Hungary-based Hire account with new identity and contact values, a custom Hire plan, users, group, account manager, and staff notes. | Ayan Custom Weeks Hire Flex Plan | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Months Hire Premium Plan | Bence | Toth | 31 Andrassy ut, Suite 4 | Hungary | Budapest | Budapest | 1061 |
      | Freydis | Solvej | Munkholm | Munkholm Complete Operations GmbH | Austria | freydis.solvej.munkholm.saasaccount420@yopmail.com | Yes | +43 | 6762941835 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 63 | Silver | Ayan Test Manager | Testing this Austria-based all-app account using newly generated identity, email, phone, plan values, users, newsletter preference, and Silver group assignment. |  | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan | Klara | Hofer | 52 Mariahilfer Strasse, Level 5 | Austria | Vienna | Vienna | 1070 |
      | Radoslaw | Ignacy | Milewski | Milewski Checkout Services Sp z oo | Poland | radoslaw.ignacy.milewski.saasaccount421@yopmail.com | No | +48 | 695381247 | checkout | Simplified Checkout | Yes |  |  |  |  | 24 | Gold | Ayan Test Manager | Creating this Poland-based Checkout account with a completely fresh name, email address, phone number, Checkout plan, users, group, and manager data. | Ayan Daily Checkout Starter Plan | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Weeks Hire Flex Plan | Alicja | Dabrowska | 88 Dluga Street, Office 21 | Poland | Gdansk | Pomeranian | 80-831 |
      | Vedrana | Danica | Vrbancic | Vrbancic Unified Enterprise doo | Croatia | vedrana.danica.vrbancic.saasaccount422@yopmail.com | Yes | +385 | 992746381 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 69 | Gold II | Ayan Test Manager | Validating this Croatia-based all-app account with newly generated customer identity, contact details, application plans, users, group, and newsletter state. |  | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Months Hire Premium Plan | Marko | Kovacevic | 16 Ilica Street, Floor 3 | Croatia | Zagreb | City of Zagreb | 10000 |
      | Baptiste | Loic | Giraudon | Giraudon People Operations SAS | France | baptiste.loic.giraudon.saasaccount423@yopmail.com | No | +33 | 645927381 | hr | Simplified HR | Yes |  |  |  |  | 45 | Diamond | Ayan Test Manager | Creating this France-based HR account with fresh identity, a unique email address, a new phone number, HR plan, users, group selection, and staff notes. | Ayan HR New Weekly Plan | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan | Hugo | Pelletier | 41 Rue de la Republique, Bureau 8 | France | Marseille | Provence-Alpes-Cote d'Azur | 13001 |
      | Aafke | Rosalinde | Ten Broeke | Ten Broeke Integrated Cloud BV | Netherlands | aafke.rosalinde.tenbroeke.saasaccount424@yopmail.com | Yes | +31 | 642918357 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Daily Spaces Starter Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 72 | Silver | Ayan Test Manager | Testing this Netherlands-based all-app account with completely new name, email, phone, application plans, users, account manager, and subscription preference. |  | checkout | AYan 5 day biilling plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Weeks Hire Flex Plan | Thijs | Meulenberg | 67 Weena, Business Center 11 | Netherlands | Rotterdam | South Holland | 3013AL |
      | Eero | Jalmari | Kuusisto | Kuusisto Complete Platforms Oy | Finland | eero.jalmari.kuusisto.saasaccount425@yopmail.com | No | +358 | 509284736 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Daily HR Starter Plan | 54 | Gold | Ayan Test Manager | Creating this Finland-based all-app account using fresh personal and contact data, unique plan combinations, user count, group assignment, and staff notes. |  | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Months Hire Premium Plan | Kaisa | Niemela | 28 Aleksanterinkatu, Office 15 | Finland | Turku | Southwest Finland | 20100 |


  @VerifyAccount
  Scenario Outline: Verify account for <Account_Company_Name>

    Given verify SaaS Admin account using the following feature data
      | First Name         | <Account_First_Name>         |
      | Middle Name        | <Account_Middle_Name>        |
      | Last Name          | <Account_Last_Name>          |
      | Company Name       | <Account_Company_Name>       |
      | Country            | <Account_Country>            |
      | Email              | <Account_Email>              |
      | Subscribe News     | <Account_Subscribe_News>     |
      | Country Code       | <Account_Country_Code>       |
      | Phone Number       | <Account_Phone_Number>       |
      | App Type           | <Account_App_Type>           |
      | App Name           | <Account_App_Name>           |
      | App Enabled        | <Account_App_Enabled>        |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name   | <Account_Spaces_Plan_Name>   |
      | Hire Plan Name     | <Account_Hire_Plan_Name>     |
      | Hr Plan Name       | <Account_Hr_Plan_Name>       |
      | Users              | <Account_Users>              |
      | Group              | <Account_Group>              |
      | Account Manager    | <Account_Account_Manager>    |
      | Staff Notes        | <Account_Staff_Notes>        |
      | Plan Name          | <Account_Plan_Name>          |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lothar | Severinus | Eisenhardt | Eisenhardt Unified Commerce GmbH | Germany | lothar.severinus.eisenhardt.saasaccount406@yopmail.com | Yes | +49 | 17160483295 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 66 | Gold II | Ayan Test Manager | Creating this Germany-based all-app account with newly generated identity, email, phone, users, plans, group, newsletter preference, and account manager data. |  |
      | Clemence | Aurelie | Fontenay | Fontenay Checkout Technologies SAS | France | clemence.aurelie.fontenay.saasaccount407@yopmail.com | No | +33 | 612984735 | checkout | Simplified Checkout | Yes |  |  |  |  | 29 | Diamond | Ayan Test Manager | Validating this France-based Checkout account with fresh customer details, a unique email address, a new phone number, user allocation, group mapping, and staff notes. | Ayan Daily Checkout Starter Plan |
      | Bjorn | Hallstein | Myklebust | Myklebust Enterprise Platforms AS | Norway | bjorn.hallstein.myklebust.saasaccount408@yopmail.com | Yes | +47 | 93618427 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan New Professional Diamond Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 71 | Silver | Ayan Test Manager | Testing this Norway-based all-app account using newly generated contact information, application plans, user count, subscription preference, and group assignment. |  |
      | Ewelina | Jadwiga | Przybysz | Przybysz Talent Systems Sp z oo | Poland | ewelina.jadwiga.przybysz.saasaccount409@yopmail.com | No | +48 | 607294183 | hire | Simplified Hire | Yes |  |  |  |  | 38 | Gold | Ayan Test Manager | Creating this Poland-based Hire account with a new name, email, phone number, recruitment plan, users, group, account manager, and staff-note value. | Ayan Monthly Hire Business Plan |
      | Cosimo | Leandro | Ventresca | Ventresca Integrated Operations SRL | Italy | cosimo.leandro.ventresca.saasaccount410@yopmail.com | Yes | +39 | 3207481956 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 62 | Gold II | Ayan Test Manager | Validating this Italy-based all-app account with fresh identity and contact values across account creation, plan assignment, upgrade, and activation workflows. |  |
      | Willemijn | Katelijne | Van Breukelen | Van Breukelen Workspace Solutions BV | Netherlands | willemijn.katelijne.vanbreukelen.saasaccount411@yopmail.com | No | +31 | 615827439 | spaces | Simplified Spaces | Yes |  |  |  |  | 35 | Diamond | Ayan Test Manager | Creating this Netherlands-based Spaces account using a completely new name, email address, phone number, workspace plan, users, group, and notes. | Ayan Weekly Spaces Growth Plan |
      | Arttu | Samuli | Hietala | Hietala Complete Business Oy | Finland | arttu.samuli.hietala.saasaccount412@yopmail.com | Yes | +358 | 401936275 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Advance Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 74 | Silver | Ayan Test Manager | Testing this Finland-based all-app account with newly generated identity, contact details, plan combinations, user allocation, newsletter state, and manager mapping. |  |
      | Gaspard | Etienne | Rouxel | Rouxel Digital Checkout SRL | Belgium | gaspard.etienne.rouxel.saasaccount413@yopmail.com | No | +32 | 468723195 | checkout | Simplified Checkout | Yes |  |  |  |  | 26 | Gold | Ayan Test Manager | Creating this Belgium-based Checkout account with fresh customer data, unique email and phone values, a custom plan, user count, group, and staff notes. | Ayan Monthly Checkout Business Plan |
      | Niklas | Antero | Holmqvist | Holmqvist Unified Cloud AB | Sweden | niklas.antero.holmqvist.saasaccount414@yopmail.com | Yes | +46 | 735918264 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Daily Checkout Starter Plan | Ayan Daily Spaces Starter Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 68 | Gold II | Ayan Test Manager | Validating this Sweden-based all-app account using new personal details, contact data, application plans, users, subscription choice, and Gold II group mapping. |  |
      | Sorina | Otilia | Cernat | Cernat Human Capital SRL | Romania | sorina.otilia.cernat.saasaccount415@yopmail.com | No | +40 | 746193825 | hr | Simplified HR | Yes |  |  |  |  | 43 | Diamond | Ayan Test Manager | Creating this Romania-based HR account with a never-reused name, email address, phone number, HR plan, users, group selection, manager, and notes. | Ayan Custom Days HR Flex Plan |
      | Karel | Vojtech | Benes | Benes Enterprise Services sro | Czech Republic | karel.vojtech.benes.saasaccount416@yopmail.com | Yes | +420 | 602817394 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Premium Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 57 | Silver | Ayan Test Manager | Testing this Czech Republic-based all-app account with completely fresh identity, phone, email, plan mapping, users, newsletter preference, and staff notes. |  |
      | Ainhoa | Leire | Mendizabal | Mendizabal Workspace Management SL | Spain | ainhoa.leire.mendizabal.saasaccount417@yopmail.com | No | +34 | 672839145 | spaces | Simplified Spaces | Yes |  |  |  |  | 31 | Gold | Ayan Test Manager | Creating this Spain-based Spaces account with newly generated contact details, workspace subscription, users, group, account manager, and internal notes. | Ayan Monthly Spaces Business Plan |
      | Sigrid | Thora | Enevoldsen | Enevoldsen Integrated Systems ApS | Denmark | sigrid.thora.enevoldsen.saasaccount418@yopmail.com | Yes | +45 | 51827364 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan New Professional Diamond Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 76 | Gold II | Ayan Test Manager | Validating this Denmark-based all-app account with a fresh name, email, phone, application plans, user allocation, subscription status, and group mapping. |  |
      | Levente | Zoltan | Berczi | Berczi Recruitment Platforms Kft | Hungary | levente.zoltan.berczi.saasaccount419@yopmail.com | No | +36 | 209483761 | hire | Simplified Hire | Yes |  |  |  |  | 40 | Diamond | Ayan Test Manager | Creating this Hungary-based Hire account with new identity and contact values, a custom Hire plan, users, group, account manager, and staff notes. | Ayan Custom Weeks Hire Flex Plan |
      | Freydis | Solvej | Munkholm | Munkholm Complete Operations GmbH | Austria | freydis.solvej.munkholm.saasaccount420@yopmail.com | Yes | +43 | 6762941835 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 63 | Silver | Ayan Test Manager | Testing this Austria-based all-app account using newly generated identity, email, phone, plan values, users, newsletter preference, and Silver group assignment. |  |
      | Radoslaw | Ignacy | Milewski | Milewski Checkout Services Sp z oo | Poland | radoslaw.ignacy.milewski.saasaccount421@yopmail.com | No | +48 | 695381247 | checkout | Simplified Checkout | Yes |  |  |  |  | 24 | Gold | Ayan Test Manager | Creating this Poland-based Checkout account with a completely fresh name, email address, phone number, Checkout plan, users, group, and manager data. | Ayan Daily Checkout Starter Plan |
      | Vedrana | Danica | Vrbancic | Vrbancic Unified Enterprise doo | Croatia | vedrana.danica.vrbancic.saasaccount422@yopmail.com | Yes | +385 | 992746381 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 69 | Gold II | Ayan Test Manager | Validating this Croatia-based all-app account with newly generated customer identity, contact details, application plans, users, group, and newsletter state. |  |
      | Baptiste | Loic | Giraudon | Giraudon People Operations SAS | France | baptiste.loic.giraudon.saasaccount423@yopmail.com | No | +33 | 645927381 | hr | Simplified HR | Yes |  |  |  |  | 45 | Diamond | Ayan Test Manager | Creating this France-based HR account with fresh identity, a unique email address, a new phone number, HR plan, users, group selection, and staff notes. | Ayan HR New Weekly Plan |
      | Aafke | Rosalinde | Ten Broeke | Ten Broeke Integrated Cloud BV | Netherlands | aafke.rosalinde.tenbroeke.saasaccount424@yopmail.com | Yes | +31 | 642918357 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Daily Spaces Starter Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 72 | Silver | Ayan Test Manager | Testing this Netherlands-based all-app account with completely new name, email, phone, application plans, users, account manager, and subscription preference. |  |
      | Eero | Jalmari | Kuusisto | Kuusisto Complete Platforms Oy | Finland | eero.jalmari.kuusisto.saasaccount425@yopmail.com | No | +358 | 509284736 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Daily HR Starter Plan | 54 | Gold | Ayan Test Manager | Creating this Finland-based all-app account using fresh personal and contact data, unique plan combinations, user count, group assignment, and staff notes. |  |


  @DeleteLead
  Scenario Outline: Delete SaaS Admin lead for <Contact_Email>

    Given delete SaaS Admin lead using the following feature data
      | Selected Product | <Contact_Selected_Product> |
      | First Name       | <Contact_First_Name>       |
      | Last Name        | <Contact_Last_Name>        |
      | Email            | <Contact_Email>            |
      | Company Name     | <Contact_Company_Name>     |
      | Country Code     | <Contact_Country_Code>     |
      | Phone Number     | <Contact_Phone_Number>     |
      | Message          | <Contact_Message>          |

    Examples:
      | Contact_Selected_Product | Contact_First_Name | Contact_Last_Name | Contact_Email | Contact_Company_Name | Contact_Country_Code | Contact_Phone_Number | Contact_Message |
      | Simplified HR | Onni Kalevi | Nieminen | onni.kalevi.nieminen.hr308@yopmail.com | Nieminen People Operations Oy | +358 | 459682731 | We are evaluating Simplified HR for employee information management, attendance monitoring, leave approval workflows, department mapping, administrator permissions, internal communication, and workforce reporting. |


  @ApproveLead
  Scenario Outline: Approve SaaS Admin lead with Hire plan <Plan_Hire_Plan_Name>

    Given approve SaaS Admin lead using the following feature data
      | Checkout App Type  | <Plan_Checkout_App_Type>  |
      | Checkout Plan Name | <Plan_Checkout_Plan_Name> |
      | Spaces App Type    | <Plan_Spaces_App_Type>    |
      | Spaces Plan Name   | <Plan_Spaces_Plan_Name>   |
      | Hr App Type        | <Plan_Hr_App_Type>        |
      | Hr Plan Name       | <Plan_Hr_Plan_Name>       |
      | Hire App Type      | <Plan_Hire_App_Type>      |
      | Hire Plan Name     | <Plan_Hire_Plan_Name>     |

    Examples:
      | Plan_Checkout_App_Type | Plan_Checkout_Plan_Name | Plan_Spaces_App_Type | Plan_Spaces_Plan_Name | Plan_Hr_App_Type | Plan_Hr_Plan_Name | Plan_Hire_App_Type | Plan_Hire_Plan_Name |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | AYan 5 day biilling plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | AYan 5 day biilling plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan Daily HR Starter Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Checkout New Yearly Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Weekly HR Growth Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Daily Checkout Starter Plan | spaces | Ayan New Professional Diamond Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Monthly Checkout Business Plan | spaces | Ayan Monthly Spaces Business Plan | hr | Ayan Yearly HR Enterprise Plan | hire | Ayan Custom Weeks Hire Flex Plan |
      | checkout | Ayan Yearly Checkout Enterprise Plan | spaces | Ayan Daily Spaces Starter Plan | hr | Ayan Custom Days HR Flex Plan | hire | Ayan Custom Months Hire Premium Plan |
      | checkout | Ayan Custom Days Checkout Premium Plan | spaces | Ayan Weekly Spaces Growth Plan | hr | Ayan HR New Weekly Plan | hire | Ayan Monthly Hire Business Plan |
      | checkout | Ayan Custom Days Checkout Advance Plan | spaces | Ayan Yearly Spaces Enterprise Plan | hr | Ayan Monthly HR Business Plan | hire | Ayan Custom Weeks Hire Flex Plan |


  @UpgradeAccountPlan
  Scenario Outline: Upgrade SaaS Admin account plan for <Account_Company_Name>

    Given SaaS Admin account upgrade data is provided from the feature file
      | First Name         | <Account_First_Name>         |
      | Middle Name        | <Account_Middle_Name>        |
      | Last Name          | <Account_Last_Name>          |
      | Company Name       | <Account_Company_Name>       |
      | Country            | <Account_Country>            |
      | Email              | <Account_Email>              |
      | Subscribe News     | <Account_Subscribe_News>     |
      | Country Code       | <Account_Country_Code>       |
      | Phone Number       | <Account_Phone_Number>       |
      | App Type           | <Account_App_Type>           |
      | App Name           | <Account_App_Name>           |
      | App Enabled        | <Account_App_Enabled>        |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name   | <Account_Spaces_Plan_Name>   |
      | Hire Plan Name     | <Account_Hire_Plan_Name>     |
      | Hr Plan Name       | <Account_Hr_Plan_Name>       |
      | Users              | <Account_Users>              |
      | Group              | <Account_Group>              |
      | Account Manager    | <Account_Account_Manager>    |
      | Staff Notes        | <Account_Staff_Notes>        |
      | Plan Name          | <Account_Plan_Name>          |

    When the SaaS Admin account plan is upgraded using the following billing feature data
      | First Name | <Billing_First_Name> |
      | Last Name  | <Billing_Last_Name>  |
      | Address    | <Billing_Address>    |
      | Country    | <Billing_Country>    |
      | City       | <Billing_City>       |
      | State      | <Billing_State>      |
      | Zip        | <Billing_Zip>        |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name | Billing_First_Name | Billing_Last_Name | Billing_Address | Billing_Country | Billing_City | Billing_State | Billing_Zip |
      | Lothar | Severinus | Eisenhardt | Eisenhardt Unified Commerce GmbH | Germany | lothar.severinus.eisenhardt.saasaccount406@yopmail.com | Yes | +49 | 17160483295 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 66 | Gold II | Ayan Test Manager | Creating this Germany-based all-app account with newly generated identity, email, phone, users, plans, group, newsletter preference, and account manager data. |  | Oskar | Feldmann | 23 Friedrichstrasse, Office 7 | Germany | Hamburg | Hamburg | 20095 |
      | Clemence | Aurelie | Fontenay | Fontenay Checkout Technologies SAS | France | clemence.aurelie.fontenay.saasaccount407@yopmail.com | No | +33 | 612984735 | checkout | Simplified Checkout | Yes |  |  |  |  | 29 | Diamond | Ayan Test Manager | Validating this France-based Checkout account with fresh customer details, a unique email address, a new phone number, user allocation, group mapping, and staff notes. | Ayan Daily Checkout Starter Plan | Lucie | Perrin | 58 Avenue de Wagram, Suite 12 | France | Paris | Ile-de-France | 75017 |
      | Bjorn | Hallstein | Myklebust | Myklebust Enterprise Platforms AS | Norway | bjorn.hallstein.myklebust.saasaccount408@yopmail.com | Yes | +47 | 93618427 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan New Professional Diamond Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 71 | Silver | Ayan Test Manager | Testing this Norway-based all-app account using newly generated contact information, application plans, user count, subscription preference, and group assignment. |  | Anders | Ravnvik | 11 Storgata, Floor 4 | Norway | Trondheim | Trondelag | 7010 |
      | Ewelina | Jadwiga | Przybysz | Przybysz Talent Systems Sp z oo | Poland | ewelina.jadwiga.przybysz.saasaccount409@yopmail.com | No | +48 | 607294183 | hire | Simplified Hire | Yes |  |  |  |  | 38 | Gold | Ayan Test Manager | Creating this Poland-based Hire account with a new name, email, phone number, recruitment plan, users, group, account manager, and staff-note value. | Ayan Monthly Hire Business Plan | Tomasz | Bielecki | 72 Marszalkowska, Office 18 | Poland | Warsaw | Masovian | 00-545 |
      | Cosimo | Leandro | Ventresca | Ventresca Integrated Operations SRL | Italy | cosimo.leandro.ventresca.saasaccount410@yopmail.com | Yes | +39 | 3207481956 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 62 | Gold II | Ayan Test Manager | Validating this Italy-based all-app account with fresh identity and contact values across account creation, plan assignment, upgrade, and activation workflows. |  | Bianca | Moretti | 36 Via Dante, Scala C | Italy | Florence | Tuscany | 50122 |
      | Willemijn | Katelijne | Van Breukelen | Van Breukelen Workspace Solutions BV | Netherlands | willemijn.katelijne.vanbreukelen.saasaccount411@yopmail.com | No | +31 | 615827439 | spaces | Simplified Spaces | Yes |  |  |  |  | 35 | Diamond | Ayan Test Manager | Creating this Netherlands-based Spaces account using a completely new name, email address, phone number, workspace plan, users, group, and notes. | Ayan Weekly Spaces Growth Plan | Jeroen | Koster | 81 Keizersgracht, Unit 9 | Netherlands | Utrecht | Utrecht | 3511AA |
      | Arttu | Samuli | Hietala | Hietala Complete Business Oy | Finland | arttu.samuli.hietala.saasaccount412@yopmail.com | Yes | +358 | 401936275 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Advance Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 74 | Silver | Ayan Test Manager | Testing this Finland-based all-app account with newly generated identity, contact details, plan combinations, user allocation, newsletter state, and manager mapping. |  | Sanna | Heikkinen | 14 Mannerheimintie, Level 6 | Finland | Helsinki | Uusimaa | 00100 |
      | Gaspard | Etienne | Rouxel | Rouxel Digital Checkout SRL | Belgium | gaspard.etienne.rouxel.saasaccount413@yopmail.com | No | +32 | 468723195 | checkout | Simplified Checkout | Yes |  |  |  |  | 26 | Gold | Ayan Test Manager | Creating this Belgium-based Checkout account with fresh customer data, unique email and phone values, a custom plan, user count, group, and staff notes. | Ayan Monthly Checkout Business Plan | Arnaud | Lambert | 29 Boulevard Anspach, Bureau 5 | Belgium | Brussels | Brussels-Capital | 1000 |
      | Niklas | Antero | Holmqvist | Holmqvist Unified Cloud AB | Sweden | niklas.antero.holmqvist.saasaccount414@yopmail.com | Yes | +46 | 735918264 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Daily Checkout Starter Plan | Ayan Daily Spaces Starter Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 68 | Gold II | Ayan Test Manager | Validating this Sweden-based all-app account using new personal details, contact data, application plans, users, subscription choice, and Gold II group mapping. |  | Ebba | Sjostrom | 44 Vasagatan, Workspace 3 | Sweden | Gothenburg | Vastra Gotaland | 41124 |
      | Sorina | Otilia | Cernat | Cernat Human Capital SRL | Romania | sorina.otilia.cernat.saasaccount415@yopmail.com | No | +40 | 746193825 | hr | Simplified HR | Yes |  |  |  |  | 43 | Diamond | Ayan Test Manager | Creating this Romania-based HR account with a never-reused name, email address, phone number, HR plan, users, group selection, manager, and notes. | Ayan Custom Days HR Flex Plan | Mircea | Ionescu | 19 Calea Victoriei, Floor 8 | Romania | Bucharest | Bucharest | 010061 |
      | Karel | Vojtech | Benes | Benes Enterprise Services sro | Czech Republic | karel.vojtech.benes.saasaccount416@yopmail.com | Yes | +420 | 602817394 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Premium Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 57 | Silver | Ayan Test Manager | Testing this Czech Republic-based all-app account with completely fresh identity, phone, email, plan mapping, users, newsletter preference, and staff notes. |  | Pavel | Dvorak | 63 Vaclavske Namesti, Office 14 | Czech Republic | Prague | Prague | 11000 |
      | Ainhoa | Leire | Mendizabal | Mendizabal Workspace Management SL | Spain | ainhoa.leire.mendizabal.saasaccount417@yopmail.com | No | +34 | 672839145 | spaces | Simplified Spaces | Yes |  |  |  |  | 31 | Gold | Ayan Test Manager | Creating this Spain-based Spaces account with newly generated contact details, workspace subscription, users, group, account manager, and internal notes. | Ayan Monthly Spaces Business Plan | Iker | Salcedo | 47 Gran Via, Planta 6 | Spain | Bilbao | Basque Country | 48011 |
      | Sigrid | Thora | Enevoldsen | Enevoldsen Integrated Systems ApS | Denmark | sigrid.thora.enevoldsen.saasaccount418@yopmail.com | Yes | +45 | 51827364 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan New Professional Diamond Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 76 | Gold II | Ayan Test Manager | Validating this Denmark-based all-app account with a fresh name, email, phone, application plans, user allocation, subscription status, and group mapping. |  | Mads | Nissen | 25 Vesterbrogade, Office 10 | Denmark | Aarhus | Central Denmark | 8000 |
      | Levente | Zoltan | Berczi | Berczi Recruitment Platforms Kft | Hungary | levente.zoltan.berczi.saasaccount419@yopmail.com | No | +36 | 209483761 | hire | Simplified Hire | Yes |  |  |  |  | 40 | Diamond | Ayan Test Manager | Creating this Hungary-based Hire account with new identity and contact values, a custom Hire plan, users, group, account manager, and staff notes. | Ayan Custom Weeks Hire Flex Plan | Bence | Toth | 31 Andrassy ut, Suite 4 | Hungary | Budapest | Budapest | 1061 |
      | Freydis | Solvej | Munkholm | Munkholm Complete Operations GmbH | Austria | freydis.solvej.munkholm.saasaccount420@yopmail.com | Yes | +43 | 6762941835 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 63 | Silver | Ayan Test Manager | Testing this Austria-based all-app account using newly generated identity, email, phone, plan values, users, newsletter preference, and Silver group assignment. |  | Klara | Hofer | 52 Mariahilfer Strasse, Level 5 | Austria | Vienna | Vienna | 1070 |
      | Radoslaw | Ignacy | Milewski | Milewski Checkout Services Sp z oo | Poland | radoslaw.ignacy.milewski.saasaccount421@yopmail.com | No | +48 | 695381247 | checkout | Simplified Checkout | Yes |  |  |  |  | 24 | Gold | Ayan Test Manager | Creating this Poland-based Checkout account with a completely fresh name, email address, phone number, Checkout plan, users, group, and manager data. | Ayan Daily Checkout Starter Plan | Alicja | Dabrowska | 88 Dluga Street, Office 21 | Poland | Gdansk | Pomeranian | 80-831 |
      | Vedrana | Danica | Vrbancic | Vrbancic Unified Enterprise doo | Croatia | vedrana.danica.vrbancic.saasaccount422@yopmail.com | Yes | +385 | 992746381 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 69 | Gold II | Ayan Test Manager | Validating this Croatia-based all-app account with newly generated customer identity, contact details, application plans, users, group, and newsletter state. |  | Marko | Kovacevic | 16 Ilica Street, Floor 3 | Croatia | Zagreb | City of Zagreb | 10000 |
      | Baptiste | Loic | Giraudon | Giraudon People Operations SAS | France | baptiste.loic.giraudon.saasaccount423@yopmail.com | No | +33 | 645927381 | hr | Simplified HR | Yes |  |  |  |  | 45 | Diamond | Ayan Test Manager | Creating this France-based HR account with fresh identity, a unique email address, a new phone number, HR plan, users, group selection, and staff notes. | Ayan HR New Weekly Plan | Hugo | Pelletier | 41 Rue de la Republique, Bureau 8 | France | Marseille | Provence-Alpes-Cote d'Azur | 13001 |
      | Aafke | Rosalinde | Ten Broeke | Ten Broeke Integrated Cloud BV | Netherlands | aafke.rosalinde.tenbroeke.saasaccount424@yopmail.com | Yes | +31 | 642918357 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Daily Spaces Starter Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 72 | Silver | Ayan Test Manager | Testing this Netherlands-based all-app account with completely new name, email, phone, application plans, users, account manager, and subscription preference. |  | Thijs | Meulenberg | 67 Weena, Business Center 11 | Netherlands | Rotterdam | South Holland | 3013AL |
      | Eero | Jalmari | Kuusisto | Kuusisto Complete Platforms Oy | Finland | eero.jalmari.kuusisto.saasaccount425@yopmail.com | No | +358 | 509284736 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Daily HR Starter Plan | 54 | Gold | Ayan Test Manager | Creating this Finland-based all-app account using fresh personal and contact data, unique plan combinations, user count, group assignment, and staff notes. |  | Kaisa | Niemela | 28 Aleksanterinkatu, Office 15 | Finland | Turku | Southwest Finland | 20100 |


  @ActivateAccount
  Scenario Outline: Activate SaaS Admin account for <Account_Company_Name>

    Given activate SaaS Admin account using the following feature data
      | First Name         | <Account_First_Name>         |
      | Middle Name        | <Account_Middle_Name>        |
      | Last Name          | <Account_Last_Name>          |
      | Company Name       | <Account_Company_Name>       |
      | Country            | <Account_Country>            |
      | Email              | <Account_Email>              |
      | Subscribe News     | <Account_Subscribe_News>     |
      | Country Code       | <Account_Country_Code>       |
      | Phone Number       | <Account_Phone_Number>       |
      | App Type           | <Account_App_Type>           |
      | App Name           | <Account_App_Name>           |
      | App Enabled        | <Account_App_Enabled>        |
      | Checkout Plan Name | <Account_Checkout_Plan_Name> |
      | Spaces Plan Name   | <Account_Spaces_Plan_Name>   |
      | Hire Plan Name     | <Account_Hire_Plan_Name>     |
      | Hr Plan Name       | <Account_Hr_Plan_Name>       |
      | Users              | <Account_Users>              |
      | Group              | <Account_Group>              |
      | Account Manager    | <Account_Account_Manager>    |
      | Staff Notes        | <Account_Staff_Notes>        |
      | Plan Name          | <Account_Plan_Name>          |

    Examples:
      | Account_First_Name | Account_Middle_Name | Account_Last_Name | Account_Company_Name | Account_Country | Account_Email | Account_Subscribe_News | Account_Country_Code | Account_Phone_Number | Account_App_Type | Account_App_Name | Account_App_Enabled | Account_Checkout_Plan_Name | Account_Spaces_Plan_Name | Account_Hire_Plan_Name | Account_Hr_Plan_Name | Account_Users | Account_Group | Account_Account_Manager | Account_Staff_Notes | Account_Plan_Name |
      | Lothar | Severinus | Eisenhardt | Eisenhardt Unified Commerce GmbH | Germany | lothar.severinus.eisenhardt.saasaccount406@yopmail.com | Yes | +49 | 17160483295 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Weekly Spaces Growth Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 66 | Gold II | Ayan Test Manager | Creating this Germany-based all-app account with newly generated identity, email, phone, users, plans, group, newsletter preference, and account manager data. |  |
      | Clemence | Aurelie | Fontenay | Fontenay Checkout Technologies SAS | France | clemence.aurelie.fontenay.saasaccount407@yopmail.com | No | +33 | 612984735 | checkout | Simplified Checkout | Yes |  |  |  |  | 29 | Diamond | Ayan Test Manager | Validating this France-based Checkout account with fresh customer details, a unique email address, a new phone number, user allocation, group mapping, and staff notes. | Ayan Daily Checkout Starter Plan |
      | Bjorn | Hallstein | Myklebust | Myklebust Enterprise Platforms AS | Norway | bjorn.hallstein.myklebust.saasaccount408@yopmail.com | Yes | +47 | 93618427 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan New Professional Diamond Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 71 | Silver | Ayan Test Manager | Testing this Norway-based all-app account using newly generated contact information, application plans, user count, subscription preference, and group assignment. |  |
      | Ewelina | Jadwiga | Przybysz | Przybysz Talent Systems Sp z oo | Poland | ewelina.jadwiga.przybysz.saasaccount409@yopmail.com | No | +48 | 607294183 | hire | Simplified Hire | Yes |  |  |  |  | 38 | Gold | Ayan Test Manager | Creating this Poland-based Hire account with a new name, email, phone number, recruitment plan, users, group, account manager, and staff-note value. | Ayan Monthly Hire Business Plan |
      | Cosimo | Leandro | Ventresca | Ventresca Integrated Operations SRL | Italy | cosimo.leandro.ventresca.saasaccount410@yopmail.com | Yes | +39 | 3207481956 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 62 | Gold II | Ayan Test Manager | Validating this Italy-based all-app account with fresh identity and contact values across account creation, plan assignment, upgrade, and activation workflows. |  |
      | Willemijn | Katelijne | Van Breukelen | Van Breukelen Workspace Solutions BV | Netherlands | willemijn.katelijne.vanbreukelen.saasaccount411@yopmail.com | No | +31 | 615827439 | spaces | Simplified Spaces | Yes |  |  |  |  | 35 | Diamond | Ayan Test Manager | Creating this Netherlands-based Spaces account using a completely new name, email address, phone number, workspace plan, users, group, and notes. | Ayan Weekly Spaces Growth Plan |
      | Arttu | Samuli | Hietala | Hietala Complete Business Oy | Finland | arttu.samuli.hietala.saasaccount412@yopmail.com | Yes | +358 | 401936275 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Advance Plan | Ayan Monthly Spaces Business Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 74 | Silver | Ayan Test Manager | Testing this Finland-based all-app account with newly generated identity, contact details, plan combinations, user allocation, newsletter state, and manager mapping. |  |
      | Gaspard | Etienne | Rouxel | Rouxel Digital Checkout SRL | Belgium | gaspard.etienne.rouxel.saasaccount413@yopmail.com | No | +32 | 468723195 | checkout | Simplified Checkout | Yes |  |  |  |  | 26 | Gold | Ayan Test Manager | Creating this Belgium-based Checkout account with fresh customer data, unique email and phone values, a custom plan, user count, group, and staff notes. | Ayan Monthly Checkout Business Plan |
      | Niklas | Antero | Holmqvist | Holmqvist Unified Cloud AB | Sweden | niklas.antero.holmqvist.saasaccount414@yopmail.com | Yes | +46 | 735918264 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Daily Checkout Starter Plan | Ayan Daily Spaces Starter Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 68 | Gold II | Ayan Test Manager | Validating this Sweden-based all-app account using new personal details, contact data, application plans, users, subscription choice, and Gold II group mapping. |  |
      | Sorina | Otilia | Cernat | Cernat Human Capital SRL | Romania | sorina.otilia.cernat.saasaccount415@yopmail.com | No | +40 | 746193825 | hr | Simplified HR | Yes |  |  |  |  | 43 | Diamond | Ayan Test Manager | Creating this Romania-based HR account with a never-reused name, email address, phone number, HR plan, users, group selection, manager, and notes. | Ayan Custom Days HR Flex Plan |
      | Karel | Vojtech | Benes | Benes Enterprise Services sro | Czech Republic | karel.vojtech.benes.saasaccount416@yopmail.com | Yes | +420 | 602817394 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Custom Days Checkout Premium Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 57 | Silver | Ayan Test Manager | Testing this Czech Republic-based all-app account with completely fresh identity, phone, email, plan mapping, users, newsletter preference, and staff notes. |  |
      | Ainhoa | Leire | Mendizabal | Mendizabal Workspace Management SL | Spain | ainhoa.leire.mendizabal.saasaccount417@yopmail.com | No | +34 | 672839145 | spaces | Simplified Spaces | Yes |  |  |  |  | 31 | Gold | Ayan Test Manager | Creating this Spain-based Spaces account with newly generated contact details, workspace subscription, users, group, account manager, and internal notes. | Ayan Monthly Spaces Business Plan |
      | Sigrid | Thora | Enevoldsen | Enevoldsen Integrated Systems ApS | Denmark | sigrid.thora.enevoldsen.saasaccount418@yopmail.com | Yes | +45 | 51827364 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan New Professional Diamond Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 76 | Gold II | Ayan Test Manager | Validating this Denmark-based all-app account with a fresh name, email, phone, application plans, user allocation, subscription status, and group mapping. |  |
      | Levente | Zoltan | Berczi | Berczi Recruitment Platforms Kft | Hungary | levente.zoltan.berczi.saasaccount419@yopmail.com | No | +36 | 209483761 | hire | Simplified Hire | Yes |  |  |  |  | 40 | Diamond | Ayan Test Manager | Creating this Hungary-based Hire account with new identity and contact values, a custom Hire plan, users, group, account manager, and staff notes. | Ayan Custom Weeks Hire Flex Plan |
      | Freydis | Solvej | Munkholm | Munkholm Complete Operations GmbH | Austria | freydis.solvej.munkholm.saasaccount420@yopmail.com | Yes | +43 | 6762941835 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Monthly Checkout Business Plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Months Hire Premium Plan | Ayan Monthly HR Business Plan | 63 | Silver | Ayan Test Manager | Testing this Austria-based all-app account using newly generated identity, email, phone, plan values, users, newsletter preference, and Silver group assignment. |  |
      | Radoslaw | Ignacy | Milewski | Milewski Checkout Services Sp z oo | Poland | radoslaw.ignacy.milewski.saasaccount421@yopmail.com | No | +48 | 695381247 | checkout | Simplified Checkout | Yes |  |  |  |  | 24 | Gold | Ayan Test Manager | Creating this Poland-based Checkout account with a completely fresh name, email address, phone number, Checkout plan, users, group, and manager data. | Ayan Daily Checkout Starter Plan |
      | Vedrana | Danica | Vrbancic | Vrbancic Unified Enterprise doo | Croatia | vedrana.danica.vrbancic.saasaccount422@yopmail.com | Yes | +385 | 992746381 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Yearly Checkout Enterprise Plan | Ayan Monthly Spaces Business Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Yearly HR Enterprise Plan | 69 | Gold II | Ayan Test Manager | Validating this Croatia-based all-app account with newly generated customer identity, contact details, application plans, users, group, and newsletter state. |  |
      | Baptiste | Loic | Giraudon | Giraudon People Operations SAS | France | baptiste.loic.giraudon.saasaccount423@yopmail.com | No | +33 | 645927381 | hr | Simplified HR | Yes |  |  |  |  | 45 | Diamond | Ayan Test Manager | Creating this France-based HR account with fresh identity, a unique email address, a new phone number, HR plan, users, group selection, and staff notes. | Ayan HR New Weekly Plan |
      | Aafke | Rosalinde | Ten Broeke | Ten Broeke Integrated Cloud BV | Netherlands | aafke.rosalinde.tenbroeke.saasaccount424@yopmail.com | Yes | +31 | 642918357 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | Ayan Checkout New Yearly Plan | Ayan Daily Spaces Starter Plan | Ayan Monthly Hire Business Plan | Ayan Weekly HR Growth Plan | 72 | Silver | Ayan Test Manager | Testing this Netherlands-based all-app account with completely new name, email, phone, application plans, users, account manager, and subscription preference. |  |
      | Eero | Jalmari | Kuusisto | Kuusisto Complete Platforms Oy | Finland | eero.jalmari.kuusisto.saasaccount425@yopmail.com | No | +358 | 509284736 | all | Simplified Checkout, Simplified Spaces, Simplified HR, Simplified Hire | Yes | AYan 5 day biilling plan | Ayan Yearly Spaces Enterprise Plan | Ayan Custom Weeks Hire Flex Plan | Ayan Daily HR Starter Plan | 54 | Gold | Ayan Test Manager | Creating this Finland-based all-app account using fresh personal and contact data, unique plan combinations, user count, group assignment, and staff notes. |  |